/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbc.business.core.kogaku;

import java.io.Serializable;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HihokenshaNo;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HokenshaNo;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYear;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYearMonth;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import jp.co.ndensan.reams.uz.uza.math.Decimal;

/**
 * 高額合算自己負担額補正保持Entityです。
 *
 * @reamsid_L DBC-2080-030 jianglaisheng
 */
@lombok.Getter
@lombok.Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class KogakuGassanJikofutangakuHosei implements Serializable {

    private HihokenshaNo 被保険者番号;
    private FlexibleYear 対象年度;
    private HokenshaNo 保険者番号;
    private RString 支給申請書整理番号;
    private RString 履歴番号;
    private FlexibleDate 生年月日;
    private RString 算定区分;
    private HokenshaNo 証記載保険者番号;
    private FlexibleYearMonth 受取年月;
    private RString 再送区分;
    private RString 送付対象外;
    private FlexibleDate 補正日_括;
    private FlexibleDate 補正日_単;
    private RString 異動区分;
    private RString 所得区分;
    private RString 係る所得区分_70歳以上;
    private RString 被保険者名;
    private HokenshaNo 突合用後期高齢者医療_保険者番号;
    private HihokenshaNo 突合用後期高齢者医療_被保番号;
    private HokenshaNo 突合用国民健康保険_保険者番号;
    private HihokenshaNo 突合用国民健康保険_被保険者個人番号;
    private HihokenshaNo 突合用国民健康保険_被保険者証番号;
    private FlexibleDate 申請日;
    private FlexibleDate 対象計算期間_開始;
    private FlexibleDate 対象計算期間_終了;
    private FlexibleDate 被保険者期間_開始;
    private FlexibleDate 被保険者期間_終了;
    private RString 宛先情報_氏名;
    private YubinNo 宛先情報_郵便番号;
    private RString 宛先情報_住所;
    private RString 窓口払情報_対象者判定;
    private RString 窓口払情報_支払場所;
    private FlexibleDate 窓口払情報_開始日_年月日;
    private RString 窓口払情報_開始日_曜日;
    private RString 窓口払情報_開始日_開始時間_時間;
    private RString 窓口払情報_開始日_開始時間_分;
    private FlexibleDate 窓口払情報_終了日_年月日;
    private RString 窓口払情報_終了日_曜日;
    private RString 窓口払情報_終了日_開始時間_時間;
    private RString 窓口払情報_終了日_開始時間_分;
    private RString 呼び出しフラグ;
    private RString 変更フラグ;

    private Decimal 補正前_自己負担額_4月分;
    private Decimal 補正前_自己負担額_5月分;
    private Decimal 補正前_自己負担額_6月分;
    private Decimal 補正前_自己負担額_7月分;
    private Decimal 補正前_自己負担額_8月分;
    private Decimal 補正前_自己負担額_9月分;
    private Decimal 補正前_自己負担額_10月分;
    private Decimal 補正前_自己負担額_11月分;
    private Decimal 補正前_自己負担額_12月分;
    private Decimal 補正前_自己負担額_翌年1月分;
    private Decimal 補正前_自己負担額_翌年2月分;
    private Decimal 補正前_自己負担額_翌年3月分;
    private Decimal 補正前_自己負担額_翌年4月分;
    private Decimal 補正前_自己負担額_翌年5月分;
    private Decimal 補正前_自己負担額_翌年6月分;
    private Decimal 補正前_自己負担額_翌年7月分;
    private Decimal 補正前_うち70_74歳に係る負担額_4月分;
    private Decimal 補正前_うち70_74歳に係る負担額_5月分;
    private Decimal 補正前_うち70_74歳に係る負担額_6月分;
    private Decimal 補正前_うち70_74歳に係る負担額_7月分;
    private Decimal 補正前_うち70_74歳に係る負担額_8月分;
    private Decimal 補正前_うち70_74歳に係る負担額_9月分;
    private Decimal 補正前_うち70_74歳に係る負担額_10月分;
    private Decimal 補正前_うち70_74歳に係る負担額_11月分;
    private Decimal 補正前_うち70_74歳に係る負担額_12月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年1月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年2月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年3月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年4月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年5月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年6月分;
    private Decimal 補正前_うち70_74歳に係る負担額_翌年7月分;
    private Decimal 補正前_高額介護_予防_サービス費_4月分;
    private Decimal 補正前_高額介護_予防_サービス費_5月分;
    private Decimal 補正前_高額介護_予防_サービス費_6月分;
    private Decimal 補正前_高額介護_予防_サービス費_7月分;
    private Decimal 補正前_高額介護_予防_サービス費_8月分;
    private Decimal 補正前_高額介護_予防_サービス費_9月分;
    private Decimal 補正前_高額介護_予防_サービス費_10月分;
    private Decimal 補正前_高額介護_予防_サービス費_11月分;
    private Decimal 補正前_高額介護_予防_サービス費_12月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年1月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年2月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年3月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年4月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年5月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年6月分;
    private Decimal 補正前_高額介護_予防_サービス費_翌年7月分;
    private Decimal 補正前_実際の自己負担額_4月分;
    private Decimal 補正前_実際の自己負担額_5月分;
    private Decimal 補正前_実際の自己負担額_6月分;
    private Decimal 補正前_実際の自己負担額_7月分;
    private Decimal 補正前_実際の自己負担額_8月分;
    private Decimal 補正前_実際の自己負担額_9月分;
    private Decimal 補正前_実際の自己負担額_10月分;
    private Decimal 補正前_実際の自己負担額_11月分;
    private Decimal 補正前_実際の自己負担額_12月分;
    private Decimal 補正前_実際の自己負担額_翌年1月分;
    private Decimal 補正前_実際の自己負担額_翌年2月分;
    private Decimal 補正前_実際の自己負担額_翌年3月分;
    private Decimal 補正前_実際の自己負担額_翌年4月分;
    private Decimal 補正前_実際の自己負担額_翌年5月分;
    private Decimal 補正前_実際の自己負担額_翌年6月分;
    private Decimal 補正前_実際の自己負担額_翌年7月分;
    private Decimal 変更前_補正後_自己負担額_4月分;
    private Decimal 変更前_補正後_自己負担額_5月分;
    private Decimal 変更前_補正後_自己負担額_6月分;
    private Decimal 変更前_補正後_自己負担額_7月分;
    private Decimal 変更前_補正後_自己負担額_8月分;
    private Decimal 変更前_補正後_自己負担額_9月分;
    private Decimal 変更前_補正後_自己負担額_10月分;
    private Decimal 変更前_補正後_自己負担額_11月分;
    private Decimal 変更前_補正後_自己負担額_12月分;
    private Decimal 変更前_補正後_自己負担額_翌年1月分;
    private Decimal 変更前_補正後_自己負担額_翌年2月分;
    private Decimal 変更前_補正後_自己負担額_翌年3月分;
    private Decimal 変更前_補正後_自己負担額_翌年4月分;
    private Decimal 変更前_補正後_自己負担額_翌年5月分;
    private Decimal 変更前_補正後_自己負担額_翌年6月分;
    private Decimal 変更前_補正後_自己負担額_翌年7月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_4月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_5月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_6月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_7月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_8月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_9月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_10月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_11月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_12月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年1月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年2月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年3月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年4月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年5月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年6月分;
    private Decimal 変更前_補正後_うち70_74歳に係る負担額_翌年7月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_4月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_5月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_6月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_7月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_8月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_9月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_10月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_11月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_12月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年1月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年2月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年3月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年4月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年5月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年6月分;
    private Decimal 変更前_補正後_高額介護_予防_サービス費_翌年7月分;
    private Decimal 変更前_補正後_実際の自己負担額_4月分;
    private Decimal 変更前_補正後_実際の自己負担額_5月分;
    private Decimal 変更前_補正後_実際の自己負担額_6月分;
    private Decimal 変更前_補正後_実際の自己負担額_7月分;
    private Decimal 変更前_補正後_実際の自己負担額_8月分;
    private Decimal 変更前_補正後_実際の自己負担額_9月分;
    private Decimal 変更前_補正後_実際の自己負担額_10月分;
    private Decimal 変更前_補正後_実際の自己負担額_11月分;
    private Decimal 変更前_補正後_実際の自己負担額_12月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年1月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年2月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年3月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年4月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年5月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年6月分;
    private Decimal 変更前_補正後_実際の自己負担額_翌年7月分;
    private Decimal 変更後_補正後_自己負担額_4月分;
    private Decimal 変更後_補正後_自己負担額_5月分;
    private Decimal 変更後_補正後_自己負担額_6月分;
    private Decimal 変更後_補正後_自己負担額_7月分;
    private Decimal 変更後_補正後_自己負担額_8月分;
    private Decimal 変更後_補正後_自己負担額_9月分;
    private Decimal 変更後_補正後_自己負担額_10月分;
    private Decimal 変更後_補正後_自己負担額_11月分;
    private Decimal 変更後_補正後_自己負担額_12月分;
    private Decimal 変更後_補正後_自己負担額_翌年1月分;
    private Decimal 変更後_補正後_自己負担額_翌年2月分;
    private Decimal 変更後_補正後_自己負担額_翌年3月分;
    private Decimal 変更後_補正後_自己負担額_翌年4月分;
    private Decimal 変更後_補正後_自己負担額_翌年5月分;
    private Decimal 変更後_補正後_自己負担額_翌年6月分;
    private Decimal 変更後_補正後_自己負担額_翌年7月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_4月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_5月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_6月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_7月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_8月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_9月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_10月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_11月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_12月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年1月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年2月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年3月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年4月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年5月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年6月分;
    private Decimal 変更後_補正後_うち70_74歳に係る負担額_翌年7月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_4月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_5月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_6月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_7月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_8月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_9月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_10月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_11月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_12月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年1月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年2月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年3月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年4月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年5月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年6月分;
    private Decimal 変更後_補正後_高額介護_予防_サービス費_翌年7月分;
    private Decimal 変更後_補正後_実際の自己負担額_4月分;
    private Decimal 変更後_補正後_実際の自己負担額_5月分;
    private Decimal 変更後_補正後_実際の自己負担額_6月分;
    private Decimal 変更後_補正後_実際の自己負担額_7月分;
    private Decimal 変更後_補正後_実際の自己負担額_8月分;
    private Decimal 変更後_補正後_実際の自己負担額_9月分;
    private Decimal 変更後_補正後_実際の自己負担額_10月分;
    private Decimal 変更後_補正後_実際の自己負担額_11月分;
    private Decimal 変更後_補正後_実際の自己負担額_12月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年1月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年2月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年3月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年4月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年5月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年6月分;
    private Decimal 変更後_補正後_実際の自己負担額_翌年7月分;
    private Decimal 変更後_合計_補正後_自己負担額;
    private Decimal 変更後_合計_補正後_うち70_74歳に係る負担額;
    private Decimal 変更後_合計_補正後_高額介護_予防_サービス費;
    private Decimal 変更後_合計_補正後_実際の自己負担額;
    private Decimal 変更前_合計_自己負担額;
    private Decimal 変更前_合計_うち70_74歳に係る負担額;
    private Decimal 変更前_合計_高額介護_予防_サービス費;
    private Decimal 変更前_合計_実際の自己負担額;

}
