package jp.co.ndensan.reams.db.dbu.entity.db.relate.hihokenshasho;

import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HihokenshaNo;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HokenKyufuRitsu;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.JigyoshaNo;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.ServiceShuruiCode;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.ShinseishoKanriNo;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.ShoKisaiHokenshaNo;
import jp.co.ndensan.reams.uz.uza.biz.AtenaBanchi;
import jp.co.ndensan.reams.uz.uza.biz.AtenaJusho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaKanaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.Code;
import jp.co.ndensan.reams.uz.uza.biz.Katagaki;
import jp.co.ndensan.reams.uz.uza.biz.LasdecCode;
import jp.co.ndensan.reams.uz.uza.biz.ShikibetsuCode;
import jp.co.ndensan.reams.uz.uza.biz.TelNo;
import jp.co.ndensan.reams.uz.uza.biz.YMDHMS;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYearMonth;
import jp.co.ndensan.reams.uz.uza.lang.RDateTime;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import jp.co.ndensan.reams.uz.uza.math.Decimal;
import jp.co.ndensan.reams.uz.uza.util.db.IDbAccessable;

/**
 * 被保険者証一括発行情報のエンティティクラスです。
 *
 * @reamsid_L DBU-0420-020 duanzhanli
 *
 */
@SuppressWarnings("PMD.UnusedPrivateField")
@lombok.Getter
@lombok.Setter
public class IkkatsuHakkoRelateEntity implements IDbAccessable {

    private HihokenshaNo hihokenshaNo;
    private LasdecCode shichosonCode;
    private ShikibetsuCode shikibetsuCode;
    private RDateTime insertTimestamp;
    private RDateTime lastUpdateTimestamp;
    private FlexibleDate idoYMD;
    private RString edaNo;
    private RString idoJiyuCode;
    private RString shikakuShutokuJiyuCode;
    private FlexibleDate shikakuShutokuYMD;
    private FlexibleDate shikakuShutokuTodokedeYMD;
    private FlexibleDate ichigoShikakuShutokuYMD;
    private RString hihokennshaKubunCode;
    private RString shikakuSoshitsuJiyuCode;
    private FlexibleDate shikakuSoshitsuYMD;
    private FlexibleDate shikakuSoshitsuTodokedeYMD;
    private RString shikakuHenkoJiyuCode;
    private FlexibleDate shikakuHenkoYMD;
    private FlexibleDate shikakuHenkoTodokedeYMD;
    private RString jushochitokureiTekiyoJiyuCode;
    private FlexibleDate jushochitokureiTekiyoYMD;
    private FlexibleDate tekiyoTodokedeYMD;
    private RString jushochitokureiKaijoJiyuCode;
    private FlexibleDate jushochitokureiKaijoYMD;
    private FlexibleDate kaijoTodokedeYMD;
    private RString jushochiTokureiFlag;
    private RString koikinaiJushochiTokureiFlag;
    private LasdecCode sochimotoShichosonCode;
    private LasdecCode kyuShichosonCode;
    private boolean logicalDeletedFlag;
    private RString daichoShubetsu;
    private RString nyushoShisetsuShurui;
    private JigyoshaNo nyushoShisetsuCode;
    private FlexibleDate nyushoShoriYMD;
    private FlexibleDate nyushoYMD;
    private FlexibleDate taishoShoriYMD;
    private FlexibleDate taishoYMD;
    private RString roomKigoNo;
    private YMDHMS hakkoShoriTimestamp;
    private RString rirekiNo;
    private ShinseishoKanriNo shinseishoKanriNo;
    private RString shinseiJokyoKubun;
    private RString shishoCode;
    private boolean chokkinFlag;
    private Code jukyuShinseiJiyu;
    private RString shinseiRiyu;
    private Code shinseishaKankeiCode;
    private RString homninKankei;
    private FlexibleDate jukyuShinseiYMD;
    private Code nigoTokuteiShippeiCode;
    private FlexibleDate shinsakaiIraiYMD;
    private Code yokaigoJotaiKubunCode;
    private FlexibleDate ninteiYukoKikanKaishiYMD;
    private FlexibleDate ninteiYukoKikanShuryoYMD;
    private FlexibleDate ninteiYMD;
    private ServiceShuruiCode shiteiServiceShurui01;
    private ServiceShuruiCode shiteiServiceShurui02;
    private ServiceShuruiCode shiteiServiceShurui03;
    private ServiceShuruiCode shiteiServiceShurui04;
    private ServiceShuruiCode shiteiServiceShurui05;
    private ServiceShuruiCode shiteiServiceShurui06;
    private ServiceShuruiCode shiteiServiceShurui07;
    private ServiceShuruiCode shiteiServiceShurui08;
    private ServiceShuruiCode shiteiServiceShurui09;
    private ServiceShuruiCode shiteiServiceShurui10;
    private ServiceShuruiCode shiteiServiceShurui11;
    private ServiceShuruiCode shiteiServiceShurui12;
    private ServiceShuruiCode shiteiServiceShurui13;
    private ServiceShuruiCode shiteiServiceShurui14;
    private ServiceShuruiCode shiteiServiceShurui15;
    private ServiceShuruiCode shiteiServiceShurui16;
    private ServiceShuruiCode shiteiServiceShurui17;
    private ServiceShuruiCode shiteiServiceShurui18;
    private ServiceShuruiCode shiteiServiceShurui19;
    private ServiceShuruiCode shiteiServiceShurui20;
    private ServiceShuruiCode shiteiServiceShurui21;
    private ServiceShuruiCode shiteiServiceShurui22;
    private ServiceShuruiCode shiteiServiceShurui23;
    private ServiceShuruiCode shiteiServiceShurui24;
    private ServiceShuruiCode shiteiServiceShurui25;
    private ServiceShuruiCode shiteiServiceShurui26;
    private ServiceShuruiCode shiteiServiceShurui27;
    private ServiceShuruiCode shiteiServiceShurui28;
    private ServiceShuruiCode shiteiServiceShurui29;
    private ServiceShuruiCode shiteiServiceShurui30;
    private FlexibleDate soshitsuYMD;
    private FlexibleDate chokkinIdoYMD;
    private Code chokkinIdoJiyuCode;
    private Code yukoMukoKubun;
    private Code dataKubun;
    private RString remban;
    private RString idoRiyu;
    private Code shinseishoKubun;
    private Code sakujoJiyuCode;
    private boolean yoshienshaNinteiShinseiFlag;
    private Decimal shikyuGendoTanisu;
    private FlexibleDate shikyuGendoKaishiYMD;
    private FlexibleDate shikyuGendoShuryoYMD;
    private int tankiSikyuGendoNissu;
    private FlexibleDate tankiShikyuGendoKaishiYMD;
    private FlexibleDate tankiShikyuGendoShuryoYMD;
    private FlexibleDate toshoNinteiYukoKaishiYMD;
    private FlexibleDate toshoNinteiYukoShuryoYMD;
    private FlexibleDate jukyuShikakuShomeishoHakkoYMD1;
    private FlexibleDate jukyuShikakuShomeishoHakkoYMD2;
    private FlexibleDate shindanMeireishoHakkoYMD;
    private FlexibleDate hakkoYMD;
    private FlexibleDate ninteiKekkaTsuchishoHakkoYMD;
    private FlexibleDate kubunHenkoTsuchishoHakkoYMD;
    private FlexibleDate serviceHenkoTsuchishoHakkoYMD;
    private FlexibleDate ninteiKyakkaTsuchishoHakkoYMD;
    private FlexibleDate torikeshiTsuchishoHakkoYMD;
    private boolean shikakuShutokuMaeShinseiFlag;
    private boolean kyuSochishaFlag;
    private FlexibleDate nijiHanteiYMD;
    private Code kaigoJotaiKubunCode;
    private int nijiHanteiNinteiYukoKikan;
    private FlexibleDate nijiHanteiNinteiYukoKaishiYMD;
    private FlexibleDate nijiHanteiNinteiYukoShuryoYMD;
    private FlexibleDate shinsakaiShiryoSakuseiYMD;
    private RString shinsakaiKaisaiNo;
    private RString shinsakaiIken;
    private RString ichijiHanteiKekkaHenkoRiyu;
    private Code yokaigoJotaizoReiCode;
    private RString ninteishinsakaiIkenShurui;
    private RString shinsakaiMemo;
    private Code nijiHanteiKekkaInputHoho;
    private FlexibleDate nijiHanteiKekkaInputYMD;
    private ShoKisaiHokenshaNo shoKisaiHokenshaNo;
    private RString kanriKubun;
    private RString torokuKubun;
    private FlexibleDate tekiyoKaishiYMD;
    private FlexibleDate tekiyoShuryoYMD;
    private RString shuryoKubun;
    private FlexibleDate yokoku_TorokuYMD;
    private FlexibleDate sashitome_IraiJuriYMD;
    private FlexibleDate yokoku_TsuchiHakkoYMD;
    private boolean yokoku_TsuchiSaiHakkoFlag;
    private FlexibleDate bemmei_TeishutsuYMD;
    private FlexibleDate bemmei_UketsukeYMD;
    private RString bemmei_RiyuCode;
    private FlexibleDate bemmei_ShinsaKetteiYMD;
    private RString bemmei_ShinsaKekkaKubun;
    private FlexibleDate shokan_KetteiYMD;
    private FlexibleDate shokan_TsuchiHakkoYMD;
    private boolean shokan_TsuchiSaiHakkoFlag;
    private FlexibleDate hihokenshaShoTeishutsuYMD;
    private boolean sashitome_Flag;
    private FlexibleDate sashitome_KetteiYMD;
    private FlexibleDate sashitome_KaijoYMD;
    private FlexibleDate gemmen_KetteiYMD;
    private FlexibleDate gemmen_TsuchiHakkoYMD;
    private boolean gemmen_TsuchiSaiHakkoFlag;
    private HokenKyufuRitsu kyufuRitsu;
    private FlexibleDate shuryoShinsei_UketsukeYMD;
    private FlexibleDate shuryoShinsei_YMD;
    private RString shuryoShinsei_RiyuCode;
    private FlexibleDate shuryoShinsei_ShinsaKetteiYMD;
    private RString shuryoShinsei_ShinsaKekkaKubun;
    private boolean mukoKubun;
    private FlexibleYearMonth taishoYM;
    private RString todokedeKubun;
    private FlexibleDate todokedeYMD;
    private AtenaMeisho todokedeshaShimei;
    private AtenaKanaMeisho todokedeshaShimeiKana;
    private YubinNo todokedeshaYubinNo;
    private RString todokedeshaJusho;
    private TelNo todokedeshaTelNo;
    private RString todokedeshaKankeiKubun;
    private RString zanteiKubun;
    private JigyoshaNo keikakuJigyoshaNo;
    private JigyoshaNo itakusakiJigyoshaNo;
    private AtenaMeisho meisho;
    private FlexibleDate seinengappiYMD;
    private RString kannaiKangaiKubun;
    private AtenaJusho jusho;
    private AtenaBanchi banchi;
    private Katagaki katagaki;
    private boolean shisetyuJotaiFlag;
    private RString juminShubetsuCode;
    private RString juminJotaiCode;
    private RString gyoseikuName;
    private AtenaKanaMeisho kanaMeisho;
    private YubinNo yubinNo;
    private RString seibetsuCode;
    private RString jukyuKubun;
    private RString seinengappiFushoKubun;
    private RString taisyoKubun;
}
