/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbc.entity.db.relate.futanwariaishohakko;

import java.util.UUID;
import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HihokenshaNo;
import jp.co.ndensan.reams.ur.urz.definition.core.shikibetsutaisho.TorokuNo;
import jp.co.ndensan.reams.uz.uza.biz.AtenaBanchi;
import jp.co.ndensan.reams.uz.uza.biz.AtenaJusho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaKanaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.BanchiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChikuCode;
import jp.co.ndensan.reams.uz.uza.biz.ChoikiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChugakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.Code;
import jp.co.ndensan.reams.uz.uza.biz.GyomuCode;
import jp.co.ndensan.reams.uz.uza.biz.GyoseikuCode;
import jp.co.ndensan.reams.uz.uza.biz.HojinNo;
import jp.co.ndensan.reams.uz.uza.biz.KamokuCode;
import jp.co.ndensan.reams.uz.uza.biz.Katagaki;
import jp.co.ndensan.reams.uz.uza.biz.KojinNo;
import jp.co.ndensan.reams.uz.uza.biz.LasdecCode;
import jp.co.ndensan.reams.uz.uza.biz.MailAddress;
import jp.co.ndensan.reams.uz.uza.biz.SetaiCode;
import jp.co.ndensan.reams.uz.uza.biz.ShikibetsuCode;
import jp.co.ndensan.reams.uz.uza.biz.ShogakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.SubGyomuCode;
import jp.co.ndensan.reams.uz.uza.biz.TelNo;
import jp.co.ndensan.reams.uz.uza.biz.TohyokuCode;
import jp.co.ndensan.reams.uz.uza.biz.TsuzukigaraCode;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.biz.ZenkokuJushoCode;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYear;
import jp.co.ndensan.reams.uz.uza.lang.RDateTime;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import jp.co.ndensan.reams.uz.uza.util.db.DbTableEntityBase;
import jp.co.ndensan.reams.uz.uza.util.db.IDbAccessable;

/**
 * 利用者負担割合証TempのEntityです。
 *
 * @reamsid_L DBC-4990-030 pengxingyi
 */
@lombok.Getter
@lombok.Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class RiyoshaFutanwariaishoEntity extends DbTableEntityBase<RiyoshaFutanwariaishoEntity> implements IDbAccessable {

    private RString dbT3113RiyoshaFutanWariai_insertDantaiCd;
    private RDateTime dbT3113RiyoshaFutanWariai_insertTimestamp;
    private RString dbT3113RiyoshaFutanWariai_insertReamsLoginId;
    private UUID dbT3113RiyoshaFutanWariai_insertContextId;
    private boolean dbT3113RiyoshaFutanWariai_isDeleted = false;
    private int dbT3113RiyoshaFutanWariai_updateCount = 0;
    private RDateTime dbT3113RiyoshaFutanWariai_lastUpdateTimestamp;
    private RString dbT3113RiyoshaFutanWariai_lastUpdateReamsLoginId;
    private FlexibleYear dbT3113RiyoshaFutanWariai_nendo;
    private HihokenshaNo dbT3113RiyoshaFutanWariai_hihokenshaNo;
    private int dbT3113RiyoshaFutanWariai_rirekiNo;
    private boolean dbT3113RiyoshaFutanWariai_hakoFuyoFlag;
    private boolean dbT3113RiyoshaFutanWariai_shokenFlag;
    private FlexibleDate dbT3113RiyoshaFutanWariai_hanteiYMD;
    private RString dbT3113RiyoshaFutanWariai_hanteiKubun;
    private Code dbT3113RiyoshaFutanWariai_koseiJiyu;
    private RString dbT3113RiyoshaFutanWariai_hakoKubun;
    private FlexibleDate dbT3113RiyoshaFutanWariai_hakoYMD;
    private FlexibleDate dbT3113RiyoshaFutanWariai_kofuYMD;
    private boolean dbT3113RiyoshaFutanWariai_logicalDeletedFlag;

    private RString dbT1001HihokenshaDaicho_insertDantaiCd;
    private RDateTime dbT1001HihokenshaDaicho_insertTimestamp;
    private RString dbT1001HihokenshaDaicho_insertReamsLoginId;
    private UUID dbT1001HihokenshaDaicho_insertContextId;
    private boolean dbT1001HihokenshaDaicho_isDeleted = false;
    private int dbT1001HihokenshaDaicho_updateCount = 0;
    private RDateTime dbT1001HihokenshaDaicho_lastUpdateTimestamp;
    private RString dbT1001HihokenshaDaicho_lastUpdateReamsLoginId;
    private HihokenshaNo dbT1001HihokenshaDaicho_hihokenshaNo;
    private FlexibleDate dbT1001HihokenshaDaicho_idoYMD;
    private RString dbT1001HihokenshaDaicho_edaNo;
    private RString dbT1001HihokenshaDaicho_idoJiyuCode;
    private LasdecCode dbT1001HihokenshaDaicho_shichosonCode;
    private ShikibetsuCode dbT1001HihokenshaDaicho_shikibetsuCode;
    private RString dbT1001HihokenshaDaicho_shikakuShutokuJiyuCode;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuShutokuYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuShutokuTodokedeYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_ichigoShikakuShutokuYMD;
    private RString dbT1001HihokenshaDaicho_hihokennshaKubunCode;
    private RString dbT1001HihokenshaDaicho_shikakuSoshitsuJiyuCode;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuSoshitsuYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuSoshitsuTodokedeYMD;
    private RString dbT1001HihokenshaDaicho_shikakuHenkoJiyuCode;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuHenkoYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_shikakuHenkoTodokedeYMD;
    private RString dbT1001HihokenshaDaicho_jushochitokureiTekiyoJiyuCode;
    private FlexibleDate dbT1001HihokenshaDaicho_jushochitokureiTekiyoYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_jushochitokureiTekiyoTodokedeYMD;
    private RString dbT1001HihokenshaDaicho_jushochitokureiKaijoJiyuCode;
    private FlexibleDate dbT1001HihokenshaDaicho_jushochitokureiKaijoYMD;
    private FlexibleDate dbT1001HihokenshaDaicho_jushochitokureiKaijoTodokedeYMD;
    private RString dbT1001HihokenshaDaicho_jushochiTokureiFlag;
    private RString dbT1001HihokenshaDaicho_koikinaiJushochiTokureiFlag;
    private LasdecCode dbT1001HihokenshaDaicho_koikinaiTokureiSochimotoShichosonCode;
    private LasdecCode dbT1001HihokenshaDaicho_kyuShichosonCode;
    private boolean dbT1001HihokenshaDaicho_logicalDeletedFlag;

    private ShikibetsuCode shikibetsuTaisho_shikibetsuCode;
    private LasdecCode shikibetsuTaisho_genLasdecCode;
    private LasdecCode shikibetsuTaisho_kyuLasdecCode;
    private int shikibetsuTaisho_kyuLasdecCodeRenban;
    private GyomuCode shikibetsuTaisho_gyomuCode;
    private int shikibetsuTaisho_rirekiNo;
    private boolean shikibetsuTaisho_currentFlag;
    private RString shikibetsuTaisho_juminShubetsuCode;
    private KojinNo shikibetsuTaisho_kojinNo;
    private HojinNo shikibetsuTaisho_hojinNo;
    private FlexibleDate shikibetsuTaisho_shoriYMD;
    private RString shikibetsuTaisho_idoJiyuCode;
    private FlexibleDate shikibetsuTaisho_idoYMD;
    private RString shikibetsuTaisho_todokedeJiyuCode;
    private FlexibleDate shikibetsuTaisho_todokedeYMD;
    private Code shikibetsuTaisho_idoRiyuCode;
    private AtenaMeisho shikibetsuTaisho_meisho;
    private AtenaKanaMeisho shikibetsuTaisho_kanaMeisho;
    private RString shikibetsuTaisho_kannaiKangaiKubun;
    private YubinNo shikibetsuTaisho_yubinNo;
    private ChoikiCode shikibetsuTaisho_choikiCode;
    private ZenkokuJushoCode shikibetsuTaisho_zenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_jusho;
    private BanchiCode shikibetsuTaisho_banchiCode1;
    private BanchiCode shikibetsuTaisho_banchiCode2;
    private BanchiCode shikibetsuTaisho_banchiCode3;
    private BanchiCode shikibetsuTaisho_banchiCode4;
    private AtenaBanchi shikibetsuTaisho_banchi;
    private Katagaki shikibetsuTaisho_katagaki;
    private boolean shikibetsuTaisho_katagakiInjiFlag;
    private GyoseikuCode shikibetsuTaisho_gyoseikuCode;
    private RString shikibetsuTaisho_gyoseikuName;
    private ChikuCode shikibetsuTaisho_chikuCode1;
    private RString shikibetsuTaisho_chikuName1;
    private ChikuCode shikibetsuTaisho_chikuCode2;
    private RString shikibetsuTaisho_chikuName2;
    private ChikuCode shikibetsuTaisho_chikuCode3;
    private RString shikibetsuTaisho_chikuName3;
    private ShogakkokuCode shikibetsuTaisho_shogakkokuCode;
    private RString shikibetsuTaisho_shogakkokuName;
    private ChugakkokuCode shikibetsuTaisho_chugakkokuCode;
    private RString shikibetsuTaisho_chugakkokuName;
    private TohyokuCode shikibetsuTaisho_tohyokuCode;
    private RString shikibetsuTaisho_tohyokuName;
    private RString shikibetsuTaisho_juminJotaiCode;
    private SetaiCode shikibetsuTaisho_setaiCode;
    private FlexibleDate shikibetsuTaisho_seinengappiYMD;
    private RString shikibetsuTaisho_seinengappiFushoKubun;
    private RString shikibetsuTaisho_seibetsuCode;
    private TsuzukigaraCode shikibetsuTaisho_tsuzukigaraCode;
    private RString shikibetsuTaisho_tsuzukigara;
    private int shikibetsuTaisho_kazokuNo;
    private int shikibetsuTaisho_juminhyoHyojijun;
    private FlexibleDate shikibetsuTaisho_kikaYMD;
    private AtenaMeisho shikibetsuTaisho_kanjiShimei;
    private AtenaKanaMeisho shikibetsuTaisho_kanaShimei;
    private RString shikibetsuTaisho_juminhyoCode;
    private ZenkokuJushoCode shikibetsuTaisho_honsekiZenkokuJushoCode;
    private ChoikiCode shikibetsuTaisho_honsekiChoikiCode;
    private AtenaJusho shikibetsuTaisho_honsekiJusho;
    private AtenaBanchi shikibetsuTaisho_honsekiBanchi;
    private AtenaMeisho shikibetsuTaisho_hittosha;
    private AtenaMeisho shikibetsuTaisho_gaikokujinShimei;
    private AtenaMeisho shikibetsuTaisho_gaikokujinHeikimei;
    private AtenaKanaMeisho shikibetsuTaisho_gaikokujinKanaShimei;
    private AtenaMeisho shikibetsuTaisho_tsushomei;
    private RString shikibetsuTaisho_shimeiRiyoKubun;
    private AtenaKanaMeisho shikibetsuTaisho_kanaTsushomei;
    private AtenaKanaMeisho shikibetsuTaisho_katakanaHyoki;
    private Code shikibetsuTaisho_kokusekiChiikiCode;
    private Code shikibetsuTaisho_zairyuShikakuCode;
    private RString shikibetsuTaisho_zairyuKikanCode;
    private FlexibleDate shikibetsuTaisho_zairyuKikantoManryoYMD;
    private RString shikibetsuTaisho_zairyuCardtoNo;
    private FlexibleDate shikibetsuTaisho_zairyuCardtoYukoYMD;
    private RString shikibetsuTaisho_dai30Jono45niKiteisuruKubun;
    private ShikibetsuCode shikibetsuTaisho_setainushiShikibetsuCode;
    private AtenaMeisho shikibetsuTaisho_setainushiMei;
    private Code shikibetsuTaisho_hojinKeitaiCode;
    private RString shikibetsuTaisho_hojinKeitaiMeisho;
    private RString shikibetsuTaisho_hojinKeitaiRyakusho;
    private RString shikibetsuTaisho_hojinMeishoHenshuKubun;
    private RString shikibetsuTaisho_hojinKeitaiRyakushoKubun;
    private AtenaMeisho shikibetsuTaisho_hojinMeisho;
    private AtenaKanaMeisho shikibetsuTaisho_hojinKanaMeisho;
    private AtenaMeisho shikibetsuTaisho_hojinShitenMeisho;
    private AtenaKanaMeisho shikibetsuTaisho_hojinShitenKanaMeisho;
    private ShikibetsuCode shikibetsuTaisho_daihyoshaShikibetsuCode;
    private RString shikibetsuTaisho_daihyoshaJuminShubetsu;
    private AtenaMeisho shikibetsuTaisho_daihyoshaShimei;
    private AtenaKanaMeisho shikibetsuTaisho_daihyoshaKanaShimei;
    private AtenaMeisho shikibetsuTaisho_daihyoshaNihonjinShimei;
    private AtenaKanaMeisho shikibetsuTaisho_daihyoshaNihonjinKanaShimei;
    private AtenaMeisho shikibetsuTaisho_daihyoshaGaikokujinShimei;
    private AtenaMeisho shikibetsuTaisho_daihyoshaGaikokujinHeikimei;
    private AtenaKanaMeisho shikibetsuTaisho_daihyoshaGaikokujinKanaShimei;
    private AtenaMeisho shikibetsuTaisho_daihyoshaTsushomei;
    private RString shikibetsuTaisho_daihyoshaShimeiRiyoKubun;
    private AtenaKanaMeisho shikibetsuTaisho_daihyoshaKanaTsushomei;
    private RString shikibetsuTaisho_daihyoshaKannaiKangaiKubun;
    private YubinNo shikibetsuTaisho_daihyoshaYubinNo;
    private ChoikiCode shikibetsuTaisho_daihyoshaChoikiCode;
    private ZenkokuJushoCode shikibetsuTaisho_daihyoshaZenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_daihyoshaJusho;
    private BanchiCode shikibetsuTaisho_daihyoshaBanchiCode1;
    private BanchiCode shikibetsuTaisho_daihyoshaBanchiCode2;
    private BanchiCode shikibetsuTaisho_daihyoshaBanchiCode3;
    private BanchiCode shikibetsuTaisho_daihyoshaBanchiCode4;
    private AtenaBanchi shikibetsuTaisho_daihyoshaBanchi;
    private Katagaki shikibetsuTaisho_daihyoshaKatagaki;
    private Code shikibetsuTaisho_ninkachiendantaiTorokuShikakuKubun;
    private FlexibleDate shikibetsuTaisho_ninkachiendantaiNinkaYMD;
    private RString shikibetsuTaisho_kojinHojinKBN;
    private AtenaMeisho shikibetsuTaisho_kyoyushaMeisho;
    private AtenaKanaMeisho shikibetsuTaisho_kyoyushaKanaMeisho;
    private RString shikibetsuTaisho_torokuJiyuCode;
    private FlexibleDate shikibetsuTaisho_torokuIdoYMD;
    private FlexibleDate shikibetsuTaisho_torokuTodokedeYMD;
    private RString shikibetsuTaisho_juteiJiyuCode;
    private FlexibleDate shikibetsuTaisho_juteiIdoYMD;
    private FlexibleDate shikibetsuTaisho_juteiTodokedeYMD;
    private RString shikibetsuTaisho_shojoJiyuCode;
    private FlexibleDate shikibetsuTaisho_shojoIdoYMD;
    private FlexibleDate shikibetsuTaisho_shojoTodokedeYMD;
    private RString shikibetsuTaisho_aimaiShojobiMongon;
    private YubinNo shikibetsuTaisho_jutonaiYubinNo;
    private ChoikiCode shikibetsuTaisho_jutonaiChoikiCode;
    private RString shikibetsuTaisho_jutonaiJusho;
    private BanchiCode shikibetsuTaisho_jutonaiBanchiCode1;
    private BanchiCode shikibetsuTaisho_jutonaiBanchiCode2;
    private BanchiCode shikibetsuTaisho_jutonaiBanchiCode3;
    private BanchiCode shikibetsuTaisho_jutonaiBanchiCode4;
    private AtenaBanchi shikibetsuTaisho_jutonaiBanchi;
    private Katagaki shikibetsuTaisho_jutonaiKatagaki;
    private boolean shikibetsuTaisho_jutonaiKatagakiInjiFlag;
    private YubinNo shikibetsuTaisho_tennyumaeYubinNo;
    private ZenkokuJushoCode shikibetsuTaisho_tennyumaeZenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_tennyumaeJusho;
    private AtenaBanchi shikibetsuTaisho_tennyumaeBanchi;
    private Katagaki shikibetsuTaisho_tennyumaeKatagaki;
    private RString shikibetsuTaisho_tennyumaeSetainushimei;
    private AtenaMeisho shikibetsuTaisho_tennyumaeKyusei;
    private YubinNo shikibetsuTaisho_saishuJutochiYubinNo;
    private ZenkokuJushoCode shikibetsuTaisho_saishuJutochiZenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_saishuJutochiJusho;
    private AtenaBanchi shikibetsuTaisho_saishuJutochiBanchi;
    private Katagaki shikibetsuTaisho_saishuJutochiKatagaki;
    private RString shikibetsuTaisho_saishuJutochiSetainushimei;
    private FlexibleDate shikibetsuTaisho_tenshutsuYoteiIdoYMD;
    private YubinNo shikibetsuTaisho_tenshutsuYoteiYubinNo;
    private ZenkokuJushoCode shikibetsuTaisho_tenshutsuYoteiZenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_tenshutsuYoteiJusho;
    private AtenaBanchi shikibetsuTaisho_tenshutsuYoteiBanchi;
    private Katagaki shikibetsuTaisho_tenshutsuYoteiKatagaki;
    private RString shikibetsuTaisho_tenshutsuYoteiSetainushimei;
    private FlexibleDate shikibetsuTaisho_tenshutsuKakuteiIdoYMD;
    private FlexibleDate shikibetsuTaisho_tenshutsuKakuteiTsuchiYMD;
    private YubinNo shikibetsuTaisho_tenshutsuKakuteiYubinNo;
    private ZenkokuJushoCode shikibetsuTaisho_tenshutsuKakuteiZenkokuJushoCode;
    private AtenaJusho shikibetsuTaisho_tenshutsuKakuteiJusho;
    private AtenaBanchi shikibetsuTaisho_tenshutsuKakuteiBanchi;
    private Katagaki shikibetsuTaisho_tenshutsuKakuteiKatagaki;
    private RString shikibetsuTaisho_tenshutsuKakuteiSetainushimei;
    private RString shikibetsuTaisho_juminhyoUtsushiHakkoSeigyoKubun;
    private TelNo shikibetsuTaisho_renrakusaki1;
    private TelNo shikibetsuTaisho_kensakuRenrakusaki1;
    private Code shikibetsuTaisho_renrakusakiKubun1;
    private TelNo shikibetsuTaisho_renrakusaki2;
    private TelNo shikibetsuTaisho_kensakuRenrakusaki2;
    private Code shikibetsuTaisho_renrakusakiKubun2;
    private TelNo shikibetsuTaisho_renrakusaki3;
    private TelNo shikibetsuTaisho_kensakuRenrakusaki3;
    private Code shikibetsuTaisho_renrakusakiKubun3;
    private MailAddress shikibetsuTaisho_mailAddress;
    private RString shikibetsuTaisho_biko;
    private RString shikibetsuTaisho_kanaName;
    private RString shikibetsuTaisho_gaikokujinKanaName;
    private RString shikibetsuTaisho_kanaTsushoName;
    private RDateTime shikibetsuTaisho_lastUpdateTimestamp;
    private RString shikibetsuTaisho_lastUpdateReamsLoginId;
    private int shikibetsuTaisho_jutogaiKanriUpdateCount;
    private TorokuNo shikibetsuTaisho_jutogaiKanriTorokuNo;
    private int shikibetsuTaisho_jutogaiKojinKihonUpdateCount;
    private TorokuNo shikibetsuTaisho_jutogaiKojinKihonTorokuNo;
    private int shikibetsuTaisho_jutogaiNihonjinUpdateCount;
    private TorokuNo shikibetsuTaisho_jutogaiNihonjinTorokuNo;
    private int shikibetsuTaisho_jutogaiGaikokujinUpdateCount;
    private TorokuNo shikibetsuTaisho_jutogaiGaikokujinTorokuNo;
    private int shikibetsuTaisho_hojinUpdateCount;
    private TorokuNo shikibetsuTaisho_hojinTorokuNo;
    private int shikibetsuTaisho_kyoyushaUpdateCount;
    private TorokuNo shikibetsuTaisho_kyoyushaTorokuNo;
    private TorokuNo shikibetsuTaisho_shimeiSearchTorokuNo;
    private int shikibetsuTaisho_yusenShimeiUpdateCount;
    private RDateTime shikibetsuTaisho_yusenShimeiTimestamp;
    private TorokuNo shikibetsuTaisho_jukiTorokuNo;

    private ShikibetsuCode atesaki_shikibetsuCode;
    private RString atesaki_atesakiShubetsu;
    private RString atesaki_gyomubetsuPrimaryKey;
    private GyomuCode atesaki_gyomuCode;
    private SubGyomuCode atesaki_subGyomuCode;
    private RString atesaki_gyomuGroupCode;
    private RString atesaki_gyomuGroupName;
    private RString atesaki_subGyomuGroupCode;
    private RString atesaki_subGyomuGroupName;
    private KamokuCode atesaki_kamokuCode;
    private RString atesaki_gyomuKoyuKey;
    private RString atesaki_kannaiKangaiKubun;
    private ZenkokuJushoCode atesaki_zenkokuJushoCode;
    private ChoikiCode atesaki_choikiCode;
    private AtenaJusho atesaki_jusho;
    private YubinNo atesaki_yubinNo;
    private BanchiCode atesaki_banchiCode1;
    private BanchiCode atesaki_banchiCode2;
    private BanchiCode atesaki_banchiCode3;
    private BanchiCode atesaki_banchiCode4;
    private AtenaBanchi atesaki_banchi;
    private boolean atesaki_katagakiInjiFlag;
    private Katagaki atesaki_katagaki;
    private GyoseikuCode atesaki_gyoseikuCode;
    private RString atesaki_gyoseiku;
    private ChikuCode atesaki_chikuCode1;
    private RString atesaki_chiku1;
    private ChikuCode atesaki_chikuCode2;
    private RString atesaki_chiku2;
    private ChikuCode atesaki_chikuCode3;
    private RString atesaki_chiku3;
    private RString atesaki_juminShubetsuCode;
    private RString atesaki_juminJotaiCode;
    private AtenaMeisho atesaki_kanjiShimei;
    private AtenaKanaMeisho atesaki_kanaShimei;
    private AtenaMeisho atesaki_gaikokujinShimei;
    private AtenaMeisho atesaki_gaikokujinHeikimei;
    private AtenaKanaMeisho atesaki_gaikokujinKanaShimei;
    private AtenaMeisho atesaki_tsushomei;
    private AtenaKanaMeisho atesaki_kanaTsushomei;
    private RString atesaki_shimeiRiyoKubun;
    private AtenaMeisho atesaki_kyoyushaMeisho;
    private AtenaKanaMeisho atesaki_kyoyushaKanaMeisho;
    private Code atesaki_hojinKeitaiCode;
    private RString atesaki_hojinMeiHenshuKubun;
    private RString atesaki_hojinKeitaiRyakushoKubun;
    private AtenaMeisho atesaki_hojinMeisho;
    private AtenaKanaMeisho atesaki_hojinKanaMeisho;
    private AtenaMeisho atesaki_hojinShitenMeisho;
    private AtenaKanaMeisho atesaki_hojinShitenKanaMeisho;
    private AtenaMeisho atesaki_sofusakiMeisho;
    private AtenaKanaMeisho atesaki_sofusakiKanaMeisho;
    private TelNo atesaki_renrakusaki1;
    private Code atesaki_renrakusakiKubun1;
    private TelNo atesaki_renrakusaki2;
    private Code atesaki_renrakusakiKubun2;
    private TelNo atesaki_renrakusaki3;
    private Code atesaki_renrakusakiKubun3;
    private MailAddress atesaki_mailAddress;
    private Code atesaki_dainoKankeiCode;
    private RString atesaki_biko;
    private RString atesaki_honninJuminShubetsuCode;
    private RString atesaki_honninJuminJotaiCode;
    private AtenaMeisho atesaki_honninKanjiShimei;
    private AtenaKanaMeisho atesaki_honninKanaShimei;
    private AtenaMeisho atesaki_honninGaikokujinShimei;
    private AtenaMeisho atesaki_honninGaikokujinHeikimei;
    private AtenaKanaMeisho atesaki_honninGaikokujinKanaShimei;
    private AtenaMeisho atesaki_honninTsushomei;
    private AtenaKanaMeisho atesaki_honninKanaTsushomei;
    private RString atesaki_honninShimeiRiyoKubun;
    private AtenaMeisho atesaki_honninKyoyushaMeisho;
    private AtenaKanaMeisho atesaki_honninKyoyushaKanaMeisho;
    private Code atesaki_honninHojinKeitaiCode;
    private RString atesaki_honninHojinMeiHenshuKubun;
    private RString atesaki_honninHojinKeitaiRyakushoKubun;
    private AtenaMeisho atesaki_honninHojinMeisho;
    private AtenaKanaMeisho atesaki_honninHojinKanaMeisho;
    private AtenaMeisho atesaki_honninHojinShitenMeisho;
    private AtenaKanaMeisho atesaki_honninHojinShitenKanaMeisho;
    private ShikibetsuCode atesaki_honninDaihyoshaShikibetsuCode;
    private RString atesaki_honninDaihyoshaJuminShubetsuCode;
    private AtenaMeisho atesaki_honninDaihyoshaShimei;
    private AtenaKanaMeisho atesaki_honninDaihyoshaKanaShimei;
    private AtenaMeisho atesaki_honninDaihyoshaNihonjinShimei;
    private AtenaKanaMeisho atesaki_honninDaihyoshaNihonjinKanaShimei;
    private AtenaMeisho atesaki_honninDaihyoshaGaikokujinShimei;
    private AtenaMeisho atesaki_honninDaihyoshaGaikokujinHeikimei;
    private AtenaKanaMeisho atesaki_honninDaihyoshaGaikokujinKanaShimei;
    private AtenaMeisho atesaki_honninDaihyoshaTsushomei;
    private RString atesaki_honninDaihyoshaShimeiRiyoKubun;
    private AtenaKanaMeisho atesaki_honninDaihyoshaKanaTsushomei;
    private ShikibetsuCode atesaki_setainushiShikibetsuCode;
    private RString atesaki_setainushiKannaiKangaiKubun;
    private ZenkokuJushoCode atesaki_setainushiZenkokuJushoCode;
    private ChoikiCode atesaki_setainushiChoikiCode;
    private AtenaJusho atesaki_setainushiJusho;
    private YubinNo atesaki_setainushiYubinNo;
    private BanchiCode atesaki_setainushiBanchiCode1;
    private BanchiCode atesaki_setainushiBanchiCode2;
    private BanchiCode atesaki_setainushiBanchiCode3;
    private BanchiCode atesaki_setainushiBanchiCode4;
    private AtenaBanchi atesaki_setainushiBanchi;
    private boolean atesaki_setainushiKatagakiInjiFlag;
    private Katagaki atesaki_setainushiKatagaki;
    private GyoseikuCode atesaki_setainushiGyoseikuCode;
    private RString atesaki_setainushiGyoseikuName;
    private ChikuCode atesaki_setainushiChikuCode1;
    private RString atesaki_setainushiChiku1;
    private ChikuCode atesaki_setainushiChikuCode2;
    private RString atesaki_setainushiChiku2;
    private ChikuCode atesaki_setainushiChikuCode3;
    private RString atesaki_setainushiChiku3;
    private RString atesaki_setainushiJuminShubetsuCode;
    private RString atesaki_setainushiJuminJotaiCode;
    private AtenaMeisho atesaki_setainushiKanjiShimei;
    private AtenaKanaMeisho atesaki_setainushiKanaShimei;
    private AtenaMeisho atesaki_setainushiGaikokujinShimei;
    private AtenaMeisho atesaki_setainushiGaikokujinHeikimei;
    private AtenaKanaMeisho atesaki_setainushiGaikokujinKanaShimei;
    private AtenaMeisho atesaki_setainushiTsushomei;
    private AtenaKanaMeisho atesaki_setainushiKanaTsushomei;
    private RString atesaki_setainushiShimeiRiyoKubun;
    private TelNo atesaki_setainushiRenrakusaki1;
    private Code atesaki_setainushiRenrakusakiKubun1;
    private TelNo atesaki_setainushiRenrakusaki2;
    private Code atesaki_setainushiRenrakusakiKubun2;
    private TelNo atesaki_setainushiRenrakusaki3;
    private Code atesaki_setainushiRenrakusakiKubun3;
    private MailAddress atesaki_setainushiMailAddress;
    private ShikibetsuCode atesaki_dainoninShikibetsuCode;
    private SetaiCode atesaki_honninSetaiCode;
    private SetaiCode atesaki_dainoninSetaiCode;

    private RString kubun;

    private FlexibleYear futanWariKikanTemp_nendo;
    private HihokenshaNo futanWariKikanTemp_hihokenshaNo;
    private RString futanWariKikanTemp_futanWariaiKubun1;
    private FlexibleDate futanWariKikanTemp_yukoKaishiYMD1;
    private FlexibleDate futanWariKikanTemp_yukoShuryoYMD1;
    private RString futanWariKikanTemp_shikakuKubun1;
    private RString futanWariKikanTemp_futanWariaiKubun2;
    private FlexibleDate futanWariKikanTemp_yukoKaishiYMD2;
    private FlexibleDate futanWariKikanTemp_yukoShuryoYMD2;
    private RString futanWariKikanTemp_shikakuKubun2;

    private LasdecCode shokisaiHihokenshaNo;
}
