/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbu.entity.hihokenshashohakkoichiranhyo;

import jp.co.ndensan.reams.ur.urz.definition.core.shikibetsutaisho.JuminJotai;
import jp.co.ndensan.reams.uz.uza.biz.Code;
import jp.co.ndensan.reams.uz.uza.lang.RDate;
import jp.co.ndensan.reams.uz.uza.lang.RString;

/**
 * 被保険者証一覧表Entity
 *
 */
@lombok.Getter
@lombok.Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class HihokenshashoHakkoIchiranHyoEntity {

    private RString 被保険者番号;
    private RString 識別コード;
    private RString 市町村コード;
    private RString 更新日時;
    private RString 挿入日時;
    private RString 異動日;
    private RString 枝番;
    private RString 異動事由コード;
    private RString 資格取得事由コード;
    private RString 資格取得年月日;
    private RString 資格取得届出年月日;
    private RString 第1号資格取得年月日;
    private RString 被保険者区分コード;
    private RString 資格喪失事由コード;
    private RString 資格喪失年月日;
    private RString 資格喪失届出年月日;
    private RString 資格変更事由コード;
    private RString 資格変更年月日;
    private RString 資格変更届出年月日;
    private RString 住所地特例適用事由コード;
    private RString 適用年月日;
    private RString 適用届出年月日;
    private RString 住所地特例解除事由コード;
    private RString 解除年月日;
    private RString 解除届出年月日;
    private boolean 住所地特例フラグ;
    private boolean 広域内住所地特例フラグ;
    private RString 広住特措置元市町村コード;
    private RString 旧市町村コード;
    private boolean 論理削除フラグ;
    private RString 処理日時;
    private RString 台帳種別;
    private RString 入所施設種類;
    private RString 入所施設コード;
    private RString 入所処理年月日;
    private RString 入所年月日;
    private RString 退所処理年月日;
    private RString 退所年月日;
    private RString 部屋記号番号;
    private RString 履歴番号;
    private RString 申請書管理番号;
    private RString 申請状況区分;
    private RString 支所コード;
    private boolean 直近フラグ;
    private RString 受給申請事由;
    private RString 申請理由;
    private RString 届出者申請者関係コード;
    private RString 届出者本人との関係;
    private RString 受給申請年月日;
    private RString 二号特定疾病コード;
    private RString 審査会依頼年月日;
    private Code 要介護認定状態区分コード;
    private RDate 認定有効期間開始年月日;
    private RDate 認定有効期間終了年月日;
    private RString 認定年月日;
    private RString 指定サービス種類01;
    private RString 指定サービス種類02;
    private RString 指定サービス種類03;
    private RString 指定サービス種類04;
    private RString 指定サービス種類05;
    private RString 指定サービス種類06;
    private RString 指定サービス種類07;
    private RString 指定サービス種類08;
    private RString 指定サービス種類09;
    private RString 指定サービス種類10;
    private RString 指定サービス種類11;
    private RString 指定サービス種類12;
    private RString 指定サービス種類13;
    private RString 指定サービス種類14;
    private RString 指定サービス種類15;
    private RString 指定サービス種類16;
    private RString 指定サービス種類17;
    private RString 指定サービス種類18;
    private RString 指定サービス種類19;
    private RString 指定サービス種類20;
    private RString 指定サービス種類21;
    private RString 指定サービス種類22;
    private RString 指定サービス種類23;
    private RString 指定サービス種類24;
    private RString 指定サービス種類25;
    private RString 指定サービス種類26;
    private RString 指定サービス種類27;
    private RString 指定サービス種類28;
    private RString 指定サービス種類29;
    private RString 指定サービス種類30;
    private RString 喪失年月日;
    private RString 直近異動年月日;
    private RString 直近異動事由コード;
    private RString 有効無効区分;
    private RString データ区分;
    private RString 同一連番;
    private RString 異動理由;
    private RString 申請書区分;
    private RString 削除事由コード;
    private RString 要支援者認定申請区分;
    private RString 支給限度単位数;
    private RString 支給限度有効開始年月日;
    private RString 支給限度有効終了年月日;
    private RString 短期入所支給限度日数;
    private RString 短期入所支給限度開始年月日;
    private RString 短期入所支給限度終了年月日;
    private RString 当初認定有効開始年月日;
    private RString 当初認定有効終了年月日;
    private RString 受給資格証明書発行年月日１;
    private RString 受給資格証明書発行年月日２;
    private RString 診断命令書発行年月日;
    private RString 二号申請受理通知書発行年月日;
    private RString 認定結果通知書発行年月日;
    private RString 区分変更通知書発行年月日;
    private RString サービス変更通知書発行年月日;
    private RString 認定却下通知書発行年月日;
    private RString 認定取消通知書発行年月日;
    private boolean 資格取得前申請フラグ;
    private boolean 旧措置者フラグ;
    private RString 二次判定年月日;
    private RString 二次判定要介護状態区分コード;
    private RString 二次判定認定有効期間;
    private RString 二次判定認定有効開始年月日;
    private RString 二次判定認定有効終了年月日;
    private RString 介護認定審査会開催番号;
    private RString 介護認定審査会意見;
    private RString 一次判定結果変更理由;
    private RString 要介護状態像例コード;
    private RString 認定審査会意見種類;
    private RString 審査会メモ;
    private RString 二次判定結果入力方法;
    private RString 二次判定結果入力年月日;
    private RString 証記載保険者番号;
    private RString 管理区分;
    private RString 登録区分;
    private RString 適用開始年月日;
    private RString 適用終了年月日;
    private RString 終了区分;
    private RString 予告登録年月日;
    private RString 差止依頼書受理年月日;
    private RString 予告通知書発行年月日;
    private boolean 予告通知書再発行フラグ;
    private RString 弁明書提出期限;
    private RString 弁明書受付年月日;
    private RString 弁明理由コード;
    private RString 弁明審査決定年月日;
    private RString 弁明審査結果区分;
    private RString 償還払化決定年月日;
    private RString 償還払化通知書発行年月日;
    private boolean 償還払化通知書再発行フラグ;
    private RString 被保険者証提出期限;
    private boolean 差止対象フラグ;
    private RString 差止対象決定年月日;
    private RString 差止対象解除年月日;
    private RString 減額決定年月日;
    private RString 減額通知書発行年月日;
    private boolean 減額通知書再発行フラグ;
    private RString 給付率;
    private RString 終了申請書受付年月日;
    private RString 終了申請年月日;
    private RString 終了申請理由コード;
    private RString 終了申請審査決定年月日;
    private RString 終了申請審査結果区分;
    private RString 無効区分;
    private RString 対象年月;
    private RString 届出区分;
    private RString 届出年月日;
    private RString 届出者氏名;
    private RString 届出者氏名カナ;
    private RString 届出者郵便番号;
    private RString 届出者住所;
    private RString 届出者電話番号;
    private RString 届出者関係区分;
    private RString 暫定区分;
    private RString 計画事業者番号;
    private RString 委託先事業者番号;
    private RString 氏名;
    private RString 生年月日;
    private RString 住民種別コード;
    private JuminJotai 住民状態コード;
    private RString 行政区名;
    private RString 管内管外区分;
    private RString 住所;
    private RString 番地;
    private RString 方書;
    private boolean 申請中状態フラグ;
    private RString 受給区分;

}
