/// <reference path="../d.ts/jquery.d.ts" />
/// <reference path="../d.ts/UzViewControls.d.ts" />

module DBC {
    /**
     * 自動生成コードです。修正しないでください。
     * JukyushaIdoRenrakuhyoクラスのみで継承して使えます。
     */
    export class JukyushaIdoRenrakuhyo_Design extends Uz.CommonChildDiv {
    
        constructor($parentElement: JQuery, isDesignMode: bool, fieldName: string) {
            super($parentElement, isDesignMode, JukyushaIdoRenrakuhyo_Design.myLayout, fieldName);
        }
        
        /**
         * レイアウト情報のプロパティを登録します
         * @method registProperty
         */
        public registProperty() {
            super.registProperty();
        }
        
        /**
         * コントロール内で編集させたいプロパティをまとめたEditablePropertyInfoオブジェクトを返却します。
         * @method getEditableProperty
         * @return EditablePropertyInfoオブジェクト
         */
        public getEditablePropertyInfo(): any {
            var editablePropertyInfo = super.getEditablePropertyInfo();
            
            return editablePropertyInfo;
        }
        public static myLayout = {
 "fieldName": "defaultLayout",
 "items": [
  {
   "fieldName": "JukyushaIdoRenrakuhyo",
   "items": [
    {
     "fieldName": "JukyushaIdoRenrakuhyoKihonJoho",
     "items": [
      {
       "fieldName": "txtRenrakuhyoIdoDate",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "異動日",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "radRenrakuhyoIdoKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "220",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "異動区分",
       "labelLWidth": "75",
       "labelLAlign": 2,
       "selectedItem": "new",
       "dataSource": [
        {
         "key": "new",
         "value": "1:新規"
        },
        {
         "key": "change",
         "value": "2:変更"
        },
        {
         "key": "end",
         "value": "3:終了"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 3,
       "spaceSize": 0
      },
      {
       "fieldName": "ddlIdoJiyu",
       "items": [],
       "controlType": "DropDownList",
       "width": "270",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "text": "",
       "labelLText": "異動事由",
       "labelRText": "",
       "labelLWidth": "157",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "selectedItem": "koikinaiIdo",
       "dataSource": [
        {
         "key": "shutoku",
         "value": "01:受給資格取得"
        },
        {
         "key": "soshitsu",
         "value": "02:受給資格喪失"
        },
        {
         "key": "koikinaiIdo",
         "value": "03広域連合市町村間異動（政令市区間異動）"
        },
        {
         "key": "shinki",
         "value": "04:合併による新規"
        },
        {
         "key": "sonotaIdo",
         "value": "99:その他異動"
        }
       ]
      },
      {
       "fieldName": "txtRenrakuhyoHihoNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "被保番号",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "10"
      },
      {
       "fieldName": "txtRenrakuhyoHihoName",
       "items": [],
       "controlType": "TextBoxKana",
       "width": "270",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "カナ氏名",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "kanjiInField": "TextBox1",
       "kanaType": 0
      },
      {
       "fieldName": "txtHihoBirthday",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "生年月日",
       "labelRText": "",
       "labelLWidth": "105",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "radHihoSex",
       "items": [],
       "controlType": "RadioButton",
       "width": "85",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "性別",
       "labelLWidth": "90",
       "labelLAlign": 2,
       "selectedItem": "man",
       "dataSource": [
        {
         "key": "man",
         "value": "男"
        },
        {
         "key": "woman",
         "value": "女"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 2,
       "spaceSize": 0
      },
      {
       "fieldName": "txtShikakuShutokuDate",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "資格取得日",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "txtShikakuSoshitsuDate",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "資格喪失日",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "txtShokisaiHokenshaNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "50",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "証記載保険者番号",
       "labelRText": "",
       "labelLWidth": "120",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "6"
      },
      {
       "fieldName": "txtKoikiHokenshaNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "55",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "広域保険者番号",
       "labelRText": "",
       "labelLWidth": "105",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "6"
      },
      {
       "fieldName": "txtRenrakuhyoSendYM",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "55",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "送付年月",
       "labelRText": "",
       "labelLWidth": "110",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 1,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoKihonJoho"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoYokaigonintei",
     "items": [
      {
       "fieldName": "radShinseiType",
       "items": [],
       "controlType": "RadioButton",
       "width": "435",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "申請種別",
       "labelLWidth": "120",
       "labelLAlign": 2,
       "selectedItem": "new",
       "dataSource": [
        {
         "key": "new",
         "value": "1:新規　　　"
        },
        {
         "key": "update",
         "value": "2:更新　　　"
        },
        {
         "key": "change",
         "value": "3:変更　　　"
        },
        {
         "key": "shokken",
         "value": "4:職権　　　"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 4,
       "spaceSize": 0
      },
      {
       "fieldName": "txtShinseiDate",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "申請日 ",
       "labelRText": "",
       "labelLWidth": "45",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "radHenkoShinseichuKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "410",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "変更申請中区分",
       "labelLWidth": "120",
       "labelLAlign": 2,
       "selectedItem": "shinseiNashi",
       "dataSource": [
        {
         "key": "shinseiNashi",
         "value": "1:申請無し　"
        },
        {
         "key": "shinseiTyu",
         "value": "2:申請中　　"
        },
        {
         "key": "ketteiZumi",
         "value": "3:決定済　　"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 3,
       "spaceSize": 0
      },
      {
       "fieldName": "radMinashiYokaigoKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "600",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "みなし要介護区分",
       "labelLWidth": "120",
       "labelLAlign": 2,
       "selectedItem": "normal",
       "dataSource": [
        {
         "key": "normal",
         "value": "1:通常の認定"
        },
        {
         "key": "minashi",
         "value": "2:みなし認定"
        },
        {
         "key": "yamuwoenai",
         "value": "3:やむを得ない事由"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 3,
       "spaceSize": 0
      },
      {
       "fieldName": "ddlYokaigoJotaiKubun",
       "items": [],
       "controlType": "DropDownList",
       "width": "200",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "text": "",
       "labelLText": "要介護状態区分",
       "labelRText": "",
       "labelLWidth": "120",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "selectedItem": "yoshienKeikatekiYokaigo",
       "dataSource": [
        {
         "key": "higaito",
         "value": "01:非該当"
        },
        {
         "key": "yoshienKeikatekiYokaigo",
         "value": "11:要支援（経過的要介護）"
        },
        {
         "key": "yoshien1",
         "value": "12:要支援1"
        },
        {
         "key": "yoshien2",
         "value": "13:要支援2"
        },
        {
         "key": "yokaigo1",
         "value": "21:要介護1"
        },
        {
         "key": "yokaigo2",
         "value": "22:要介護2"
        },
        {
         "key": "yokaigo3",
         "value": "23:要介護3"
        },
        {
         "key": "yokaigo4",
         "value": "24:要介護4"
        },
        {
         "key": "yokaigo5",
         "value": "25:要介護5"
        }
       ]
      },
      {
       "fieldName": "txtNinteiDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "認定期間",
       "labelRText": "",
       "labelLWidth": "280",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "要介護認定",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoYokaigonintei"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoShikyugendoKijungaku",
     "items": [
      {
       "fieldName": "lblKyuHomonTsusho",
       "items": [],
       "controlType": "Label",
       "width": "90",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "isPrivateInfo": false,
       "text": "(旧訪問通所)",
       "align": 2
      },
      {
       "fieldName": "txtKyuHomonTsushoShikyuGendoKijungaku",
       "items": [],
       "controlType": "TextBoxNum",
       "width": "70",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "支給限度基準額",
       "labelRText": "",
       "labelLWidth": "105",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 2,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "+-,.",
       "maxValue": 1.7976931348623157e+308,
       "minValue": 0,
       "isCurrency": false,
       "isComma": true,
       "decimalPointLength": 0
      },
      {
       "fieldName": "txtKyuHomonTsushoKanriTekiyoDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "管理適用期間",
       "labelRText": "",
       "labelLWidth": "90",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      },
      {
       "fieldName": "lblKyuTankiNyusho",
       "items": [],
       "controlType": "Label",
       "width": "90",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "isPrivateInfo": false,
       "text": "(旧短期入所)",
       "align": 2
      },
      {
       "fieldName": "txtKyuTankiNyushoShikyuGendoKijungaku",
       "items": [],
       "controlType": "TextBoxNum",
       "width": "70",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "支給限度基準額",
       "labelRText": "",
       "labelLWidth": "105",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 2,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "+-,.",
       "maxValue": 1.7976931348623157e+308,
       "minValue": 0,
       "isCurrency": false,
       "isComma": true,
       "decimalPointLength": 0
      },
      {
       "fieldName": "txtKyuTankiNyushoKanriTekiyoDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "75",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "管理適用期間",
       "labelRText": "",
       "labelLWidth": "90",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "支給限度基準額",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoShikyugendoKijungaku"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoKyotakuServicePlan",
     "items": [
      {
       "fieldName": "radPlanSakuseiKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "515",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "計画作成区分",
       "labelLWidth": "90",
       "labelLAlign": 2,
       "selectedItem": "myself",
       "dataSource": [
        {
         "key": "kyotakuShienJigyosha",
         "value": "1:居宅介護支援事業所作成"
        },
        {
         "key": "myself",
         "value": "2:自己作成"
        },
        {
         "key": "kaigoyoboJigyosha",
         "value": "3:介護予防支援事業所作成"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 3,
       "spaceSize": 0
      },
      {
       "fieldName": "txtShienJigyoshaNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "85",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "支援事業者",
       "labelRText": "",
       "labelLWidth": "90",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "10"
      },
      {
       "fieldName": "txtShienJigyoshaName",
       "items": [],
       "controlType": "TextBoxKana",
       "width": "400",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "-0.2",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "",
       "labelRText": "",
       "labelLWidth": "S",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "kanjiInField": "TextBox1",
       "kanaType": 0
      },
      {
       "fieldName": "txtKyotakuServicePlanTekiyoDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "適用期間",
       "labelRText": "",
       "labelLWidth": "90",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      },
      {
       "fieldName": "radShokiboKyotakuServiceRiyoUmu",
       "items": [],
       "controlType": "RadioButton",
       "width": "120",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "小規模居宅サービス利用",
       "labelLWidth": "165",
       "labelLAlign": 2,
       "selectedItem": "nashi",
       "dataSource": [
        {
         "key": "nashi",
         "value": "なし"
        },
        {
         "key": "ari",
         "value": "あり"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 2,
       "spaceSize": 0
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "居宅サービス計画",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoKyotakuServicePlan"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoGemmenGengaku",
     "items": [
      {
       "fieldName": "radGemmenShinseichuKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "300",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "減免申請中区分",
       "labelLWidth": "105",
       "labelLAlign": 2,
       "selectedItem": "shinseiNashi",
       "dataSource": [
        {
         "key": "shinseiNashi",
         "value": "1:申請無し"
        },
        {
         "key": "shinseiTyu",
         "value": "2:申請中 "
        },
        {
         "key": "ketteiZumi",
         "value": "3:決定済み"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 3,
       "spaceSize": 0
      },
      {
       "fieldName": "JukyushaIdoRenrakuhyoGemmenGengakuSub",
       "items": [
        {
         "fieldName": "JukyushaIdoRenrakuhyoRiyoshaFutan",
         "items": [
          {
           "fieldName": "radRiyoshaFutanKubun",
           "items": [],
           "controlType": "RadioButton",
           "width": "250",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "required": false,
           "onChange": "",
           "labelLText": "区分",
           "labelLWidth": "60",
           "labelLAlign": 2,
           "selectedItem": "",
           "dataSource": [
            {
             "key": "standard",
             "value": "1:標準負担　"
            },
            {
             "key": "tokuteiStandard",
             "value": "2:特定標準負担"
            }
           ],
           "onClick": "",
           "newLineItemNumber": 2,
           "spaceSize": 0
          },
          {
           "fieldName": "txtRiyoshaFutanKyufuritsu",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "0",
           "marginRight": "XS",
           "required": false,
           "readOnly": false,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "labelLText": "給付率",
           "labelRText": "",
           "labelLWidth": "45",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "value": "",
           "maxLength": 1000000000000,
           "minLength": 0,
           "textAlign": 2,
           "isComboBox": false,
           "suggest": [],
           "permitCharactor": "+-,.",
           "maxValue": 1.7976931348623157e+308,
           "minValue": 0,
           "isCurrency": false,
           "isComma": false,
           "decimalPointLength": 0
          },
          {
           "fieldName": "txtRiyoshaFutanTekiyoDateRange",
           "items": [],
           "controlType": "TextBoxDateRange",
           "width": "80",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "readOnly": false,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "labelLText": "適用期間",
           "labelRText": "",
           "labelLWidth": "60",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "ymdKubun": 2,
           "displayFormat": 0,
           "permitCharactor": "",
           "fromPlaceHolder": "",
           "toPlaceHolder": "",
           "minDate": "",
           "maxDate": "",
           "fromText": "",
           "toText": "",
           "fromValue": "",
           "toValue": ""
          }
         ],
         "controlType": "Panel",
         "width": "475",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onLoad": "",
         "title": "利用者負担",
         "marginTop": "Default",
         "marginBottom": "Default",
         "isOpen": true,
         "canOpenAndClose": false,
         "postParameterPanelNames": [
          {
           "postParameterPanelNames": "JukyushaIdoRenrakuhyoRiyoshaFutan"
          }
         ],
         "requestSettings": [],
         "hiddenInput": [],
         "onOpen": "",
         "onClose": "",
         "session": {},
         "eraseBorderTop": false,
         "eraseBorderBottom": false,
         "eraseBorderRight": false,
         "eraseBorderLeft": false,
         "backgroundColor": 0,
         "widthAuto": false,
         "isGroupBox": true
        },
        {
         "fieldName": "JukyushaIdoRenrakuhyoFukushiHojinKeigen",
         "items": [
          {
           "fieldName": "txtKeigenritsu",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "30",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": true,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "required": false,
           "readOnly": false,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "labelLText": "軽減率",
           "labelRText": "",
           "labelLWidth": "50",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "value": "",
           "maxLength": 1000000000000,
           "minLength": 0,
           "textAlign": 2,
           "isComboBox": false,
           "suggest": [],
           "permitCharactor": "+-,.",
           "maxValue": 1.7976931348623157e+308,
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0
          },
          {
           "fieldName": "txtKeigenritsuTekiyoDateRange",
           "items": [],
           "controlType": "TextBoxDateRange",
           "width": "80",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "readOnly": false,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "labelLText": "軽減率適用期間",
           "labelRText": "",
           "labelLWidth": "105",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "ymdKubun": 2,
           "displayFormat": 0,
           "permitCharactor": "",
           "fromPlaceHolder": "",
           "toPlaceHolder": "",
           "minDate": "",
           "maxDate": "",
           "fromText": "",
           "toText": "",
           "fromValue": "",
           "toValue": ""
          }
         ],
         "controlType": "Panel",
         "width": "475",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onLoad": "",
         "title": "社会福祉法人軽減情報",
         "marginTop": "Default",
         "marginBottom": "Default",
         "isOpen": true,
         "canOpenAndClose": false,
         "postParameterPanelNames": [
          {
           "postParameterPanelNames": "JukyushaIdoRenrakuhyoFukushiHojinKeigen"
          }
         ],
         "requestSettings": [],
         "hiddenInput": [],
         "onOpen": "",
         "onClose": "",
         "session": {},
         "eraseBorderTop": false,
         "eraseBorderBottom": false,
         "eraseBorderRight": false,
         "eraseBorderLeft": false,
         "backgroundColor": 0,
         "widthAuto": false,
         "isGroupBox": true
        },
        {
         "fieldName": "JukyushaIdoRenrakuhyoHyojunFutan",
         "items": [
          {
           "fieldName": "lblHyojunFutanKubun",
           "items": [],
           "controlType": "Label",
           "width": "50",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": true,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "L",
           "marginRight": "XS",
           "required": false,
           "isPrivateInfo": false,
           "text": "区分",
           "align": 2
          },
          {
           "fieldName": "radHyojunFutanKubun",
           "items": [],
           "controlType": "RadioButton",
           "width": "320",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "0",
           "marginRight": "XS",
           "required": false,
           "onChange": "",
           "labelLText": "",
           "labelLWidth": "S",
           "labelLAlign": 2,
           "selectedItem": "",
           "dataSource": [
            {
             "key": "riyosha",
             "value": "1:利用者負担"
            },
            {
             "key": "kyushochiNyushosha",
             "value": "2:旧措置入所者利用者負担"
            }
           ],
           "onClick": "",
           "newLineItemNumber": 2,
           "spaceSize": 0
          },
          {
           "fieldName": "txtHyojunFutangaku",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "70",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "0",
           "marginRight": "XS",
           "required": false,
           "readOnly": false,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "labelLText": "負担額",
           "labelRText": "",
           "labelLWidth": "45",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "value": "",
           "maxLength": 1000000000000,
           "minLength": 0,
           "textAlign": 2,
           "isComboBox": false,
           "suggest": [],
           "permitCharactor": "+-,.",
           "maxValue": 1.7976931348623157e+308,
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0
          },
          {
           "fieldName": "txtHyojunFutanTekiyoDateRange",
           "items": [],
           "controlType": "TextBoxDateRange",
           "width": "80",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "0",
           "marginRight": "XS",
           "readOnly": false,
           "isPrivateInfo": false,
           "isPassword": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "labelLText": "適用期間",
           "labelRText": "",
           "labelLWidth": "60",
           "labelRWidth": "S",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "ymdKubun": 2,
           "displayFormat": 0,
           "permitCharactor": "",
           "fromPlaceHolder": "",
           "toPlaceHolder": "",
           "minDate": "",
           "maxDate": "",
           "fromText": "",
           "toText": "",
           "fromValue": "",
           "toValue": ""
          }
         ],
         "controlType": "Panel",
         "width": "475",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onLoad": "",
         "title": "標準負担",
         "marginTop": "Default",
         "marginBottom": "Default",
         "isOpen": true,
         "canOpenAndClose": false,
         "postParameterPanelNames": [
          {
           "postParameterPanelNames": "JukyushaIdoRenrakuhyoHyojunFutan"
          }
         ],
         "requestSettings": [],
         "hiddenInput": [],
         "onOpen": "",
         "onClose": "",
         "session": {},
         "eraseBorderTop": false,
         "eraseBorderBottom": false,
         "eraseBorderRight": false,
         "eraseBorderLeft": false,
         "backgroundColor": 0,
         "widthAuto": false,
         "isGroupBox": true
        }
       ],
       "controlType": "Panel",
       "width": "485",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "onLoad": "",
       "title": "",
       "marginTop": "Default",
       "marginBottom": "Default",
       "isOpen": true,
       "canOpenAndClose": true,
       "postParameterPanelNames": [
        {
         "postParameterPanelNames": "JukyushaIdoRenrakuhyoGemmenGengakuSub"
        }
       ],
       "requestSettings": [],
       "hiddenInput": [],
       "onOpen": "",
       "onClose": "",
       "session": {},
       "eraseBorderTop": true,
       "eraseBorderBottom": true,
       "eraseBorderRight": true,
       "eraseBorderLeft": true,
       "backgroundColor": 0,
       "widthAuto": false,
       "isGroupBox": false
      },
      {
       "fieldName": "JukyushaIdoRenrakuhyoTokuteiNyushoshaServiceHi",
       "items": [
        {
         "fieldName": "lblNinteiShinseichuKubun",
         "items": [],
         "controlType": "Label",
         "width": "135",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "認定申請中区分",
         "align": 2
        },
        {
         "fieldName": "radNinteiShinseichuKubun",
         "items": [],
         "controlType": "RadioButton",
         "width": "300",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "onChange": "",
         "labelLText": "",
         "labelLWidth": "S",
         "labelLAlign": 2,
         "selectedItem": "shinseiNashi",
         "dataSource": [
          {
           "key": "shinseiNashi",
           "value": "1:申請無し"
          },
          {
           "key": "shinseiTyu",
           "value": "2:申請中 "
          },
          {
           "key": "ketteiZumi",
           "value": "3:決定済み"
          }
         ],
         "onClick": "",
         "newLineItemNumber": 3,
         "spaceSize": 0
        },
        {
         "fieldName": "lblServiceKubun",
         "items": [],
         "controlType": "Label",
         "width": "135",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "サービス区分",
         "align": 2
        },
        {
         "fieldName": "radServiceKubun",
         "items": [],
         "controlType": "RadioButton",
         "width": "285",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "onChange": "",
         "labelLText": "",
         "labelLWidth": "S",
         "labelLAlign": 2,
         "selectedItem": "",
         "dataSource": [
          {
           "key": "standard",
           "value": "1:通常の受給者"
          },
          {
           "key": "kyusochiNyushosha",
           "value": "2:旧措置入所者"
          }
         ],
         "onClick": "",
         "newLineItemNumber": 3,
         "spaceSize": 0
        },
        {
         "fieldName": "lblTokureiKeigenSochiTaisho",
         "items": [],
         "controlType": "Label",
         "width": "135",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "特例減額措置対象",
         "align": 2
        },
        {
         "fieldName": "radTokureiKeigenSochiTaisho",
         "items": [],
         "controlType": "RadioButton",
         "width": "205",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "onChange": "",
         "labelLText": "",
         "labelLWidth": "S",
         "labelLAlign": 2,
         "selectedItem": "nashi",
         "dataSource": [
          {
           "key": "nashi",
           "value": "1:該当無し"
          },
          {
           "key": "ari",
           "value": "2:該当有り"
          }
         ],
         "onClick": "",
         "newLineItemNumber": 2,
         "spaceSize": 0
        },
        {
         "fieldName": "txtShokuhiFutanGendogaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "食費負担限度額 ",
         "labelRText": "",
         "labelLWidth": "135",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        },
        {
         "fieldName": "txtFutanGendogakuTekiyoDateRange",
         "items": [],
         "controlType": "TextBoxDateRange",
         "width": "80",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "readOnly": false,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "labelLText": "負担限度額適用期間",
         "labelRText": "",
         "labelLWidth": "135",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "ymdKubun": 2,
         "displayFormat": 0,
         "permitCharactor": "",
         "fromPlaceHolder": "",
         "toPlaceHolder": "",
         "minDate": "",
         "maxDate": "",
         "fromText": "",
         "toText": "",
         "fromValue": "",
         "toValue": ""
        },
        {
         "fieldName": "lblKyojuhiFutanGendogaku",
         "items": [],
         "controlType": "Label",
         "width": "125",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "居住費負担限度額",
         "align": 2
        },
        {
         "fieldName": "txtUnitKoshitsuGendogaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "ユニット型個室",
         "labelRText": "",
         "labelLWidth": "125",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        },
        {
         "fieldName": "txtUnitJunKoshitsuFutanGendogaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "ユニット型準個室",
         "labelRText": "",
         "labelLWidth": "165",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        },
        {
         "fieldName": "txtJuraigataKoshitsuTokuyoFutanGendogaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "従来型個室特養等",
         "labelRText": "",
         "labelLWidth": "130",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        },
        {
         "fieldName": "txtJuraigataKoshitsuRokenRyoyoFutanGendogaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "従来型個室老健、療養等",
         "labelRText": "",
         "labelLWidth": "170",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        },
        {
         "fieldName": "txtTashoshitsu",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "45",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "多床室",
         "labelRText": "",
         "labelLWidth": "130",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": true,
         "decimalPointLength": 0
        }
       ],
       "controlType": "Panel",
       "width": "480",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "onLoad": "",
       "title": "特定入所者サービス費",
       "marginTop": "Default",
       "marginBottom": "Default",
       "isOpen": true,
       "canOpenAndClose": false,
       "postParameterPanelNames": [
        {
         "postParameterPanelNames": "JukyushaIdoRenrakuhyoTokuteiNyushoshaServiceHi"
        }
       ],
       "requestSettings": [],
       "hiddenInput": [],
       "onOpen": "",
       "onClose": "",
       "session": {},
       "eraseBorderTop": false,
       "eraseBorderBottom": false,
       "eraseBorderRight": false,
       "eraseBorderLeft": false,
       "backgroundColor": 0,
       "widthAuto": false,
       "isGroupBox": true
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "減免・減額",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoGemmenGengaku"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoKokiKoreiKokuho",
     "items": [
      {
       "fieldName": "JukyushaIdoRenrakuhyoKokiKorei",
       "items": [
        {
         "fieldName": "txtKokiKoreiHokenshaNo",
         "items": [],
         "controlType": "TextBoxCode",
         "width": "60",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "保険者番号",
         "labelRText": "",
         "labelLWidth": "80",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "",
         "formatLength": "8"
        },
        {
         "fieldName": "txtKokiKoreiHihokenshaNo",
         "items": [],
         "controlType": "TextBoxCode",
         "width": "60",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "被保険者番号",
         "labelRText": "",
         "labelLWidth": "105",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "",
         "formatLength": "8"
        }
       ],
       "controlType": "Panel",
       "width": "480",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "onLoad": "",
       "title": "後期高齢",
       "marginTop": "Default",
       "marginBottom": "Default",
       "isOpen": true,
       "canOpenAndClose": false,
       "postParameterPanelNames": [
        {
         "postParameterPanelNames": "JukyushaIdoRenrakuhyoKokiKorei"
        }
       ],
       "requestSettings": [],
       "hiddenInput": [],
       "onOpen": "",
       "onClose": "",
       "session": {},
       "eraseBorderTop": false,
       "eraseBorderBottom": false,
       "eraseBorderRight": false,
       "eraseBorderLeft": false,
       "backgroundColor": 0,
       "widthAuto": false,
       "isGroupBox": true
      },
      {
       "fieldName": "JukyushaIdoRenrakuhyoKokuho",
       "items": [
        {
         "fieldName": "txtKokuhoHokenshaNo",
         "items": [],
         "controlType": "TextBoxCode",
         "width": "60",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "0",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "保険者番号",
         "labelRText": "",
         "labelLWidth": "80",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "",
         "formatLength": "8"
        },
        {
         "fieldName": "txtKokuhoHihokenshashoNo",
         "items": [],
         "controlType": "TextBoxCode",
         "width": "150",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "被保険者証番号",
         "labelRText": "",
         "labelLWidth": "120",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "",
         "formatLength": "20"
        },
        {
         "fieldName": "txtKokuhoKojinNo",
         "items": [],
         "controlType": "TextBoxCode",
         "width": "75",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "readOnly": false,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "labelLText": "個人番号",
         "labelRText": "",
         "labelLWidth": "75",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "",
         "formatLength": "10"
        }
       ],
       "controlType": "Panel",
       "width": "480",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "onLoad": "",
       "title": "国保",
       "marginTop": "Default",
       "marginBottom": "Default",
       "isOpen": true,
       "canOpenAndClose": false,
       "postParameterPanelNames": [
        {
         "postParameterPanelNames": "JukyushaIdoRenrakuhyoKokuho"
        }
       ],
       "requestSettings": [],
       "hiddenInput": [],
       "onOpen": "",
       "onClose": "",
       "session": {},
       "eraseBorderTop": false,
       "eraseBorderBottom": false,
       "eraseBorderRight": false,
       "eraseBorderLeft": false,
       "backgroundColor": 0,
       "widthAuto": false,
       "isGroupBox": true
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "後期高齢・国保",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoKokiKoreiKokuho"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoKyufuSeigen",
     "items": [
      {
       "fieldName": "lblKohiFutanJogengakuGengakuUmu",
       "items": [],
       "controlType": "Label",
       "width": "135",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "required": false,
       "isPrivateInfo": false,
       "text": "公費負担上限額減額(生活保護等)",
       "align": 2
      },
      {
       "fieldName": "radKohiFutanJogengakuGengakuUmu",
       "items": [],
       "controlType": "RadioButton",
       "width": "105",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "",
       "labelLWidth": "S",
       "labelLAlign": 2,
       "selectedItem": "nashi",
       "dataSource": [
        {
         "key": "nashi",
         "value": "なし"
        },
        {
         "key": "ari",
         "value": "あり"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 2,
       "spaceSize": 0
      },
      {
       "fieldName": "txtKyufuritsuHikisageDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "償還払化期間",
       "labelRText": "",
       "labelLWidth": "132",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      },
      {
       "fieldName": "txtShokanBaraikaDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "給付率引下げ期間",
       "labelRText": "",
       "labelLWidth": "120",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "給付制限",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoKyufuSeigen"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoNijiyoboJigyo",
     "items": [
      {
       "fieldName": "radNijiyoboJigyoKubun",
       "items": [],
       "controlType": "RadioButton",
       "width": "170",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "onChange": "",
       "labelLText": "事業区分",
       "labelLWidth": "60",
       "labelLAlign": 2,
       "selectedItem": "higaito",
       "dataSource": [
        {
         "key": "higaito",
         "value": "1:非該当"
        },
        {
         "key": "gaito",
         "value": "2:該当"
        }
       ],
       "onClick": "",
       "newLineItemNumber": 2,
       "spaceSize": 0
      },
      {
       "fieldName": "txtNijiyoboJigyoYukoDateRange",
       "items": [],
       "controlType": "TextBoxDateRange",
       "width": "80",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "readOnly": false,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "labelLText": "事業有効期間",
       "labelRText": "",
       "labelLWidth": "90",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "",
       "fromPlaceHolder": "",
       "toPlaceHolder": "",
       "minDate": "",
       "maxDate": "",
       "fromText": "",
       "toText": "",
       "fromValue": "",
       "toValue": ""
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "二次予防事業",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoNijiyoboJigyo"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    },
    {
     "fieldName": "JukyushaIdoRenrakuhyoRojinHoken",
     "items": [
      {
       "fieldName": "RokenShichosonNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "70",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "市町村番号",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "8"
      },
      {
       "fieldName": "RokenJukyushaNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "70",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "受給者番号",
       "labelRText": "",
       "labelLWidth": "75",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "8"
      },
      {
       "fieldName": "RokenKohiFutanshaNo",
       "items": [],
       "controlType": "TextBoxCode",
       "width": "70",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "0",
       "marginRight": "XS",
       "required": false,
       "readOnly": false,
       "placeHolder": "",
       "textKind": 2,
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "labelLText": "公費負担者番号",
       "labelRText": "",
       "labelLWidth": "105",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "value": "",
       "maxLength": 1000000000000,
       "minLength": 0,
       "textAlign": 0,
       "isComboBox": false,
       "suggest": [],
       "permitCharactor": "",
       "formatLength": "8"
      }
     ],
     "controlType": "Panel",
     "width": "985",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onLoad": "",
     "title": "老人保健",
     "marginTop": "XS",
     "marginBottom": "XS",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "JukyushaIdoRenrakuhyoRojinHoken"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorderTop": false,
     "eraseBorderBottom": false,
     "eraseBorderRight": false,
     "eraseBorderLeft": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "isGroupBox": false
    }
   ],
   "controlType": "Panel",
   "width": "1000",
   "visible": true,
   "displayNone": false,
   "disabled": false,
   "accessKey": "",
   "nextFocusFieldName": "",
   "wrap": false,
   "dependencies": [],
   "float": 0,
   "toolTip": "",
   "authorityMode": 0,
   "marginLeft": "XS",
   "marginRight": "XS",
   "onLoad": "",
   "title": "受給者異動連絡票",
   "marginTop": "Default",
   "marginBottom": "Default",
   "isOpen": true,
   "canOpenAndClose": true,
   "postParameterPanelNames": [
    {
     "postParameterPanelNames": "JukyushaIdoRenrakuhyo"
    }
   ],
   "requestSettings": [],
   "hiddenInput": [],
   "onOpen": "",
   "onClose": "",
   "session": {},
   "eraseBorderTop": false,
   "eraseBorderBottom": false,
   "eraseBorderRight": false,
   "eraseBorderLeft": false,
   "backgroundColor": 0,
   "widthAuto": false,
   "isGroupBox": false
  }
 ],
 "controlType": "CommonChildDiv",
 "width": "XS",
 "visible": true,
 "displayNone": false,
 "disabled": false,
 "accessKey": "",
 "nextFocusFieldName": "",
 "wrap": false,
 "dependencies": [],
 "float": 0,
 "toolTip": "",
 "authorityMode": 0,
 "marginLeft": 0,
 "marginRight": 0,
 "relation": [],
 "businessId": "DBC",
 "controlName": "JukyushaIdoRenrakuhyo",
 "marginTop": 0,
 "marginBottom": 0,
 "originalProperty": [],
 "dataPassingForDialog": [],
 "dialogOkEventNameForDialog": "",
 "dialogCancelEventNameForDialog": ""
}        
    }
}

