/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbc.entity.db.relate.kogakukaigokyufuhitaishoshatoroku;

import jp.co.ndensan.reams.db.dbx.definition.core.valueobject.domain.HihokenshaNo;
import jp.co.ndensan.reams.ur.urz.definition.core.shikibetsutaisho.TorokuNo;
import jp.co.ndensan.reams.uz.uza.biz.AtenaBanchi;
import jp.co.ndensan.reams.uz.uza.biz.AtenaJusho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaKanaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.BanchiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChikuCode;
import jp.co.ndensan.reams.uz.uza.biz.ChoikiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChugakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.Code;
import jp.co.ndensan.reams.uz.uza.biz.GyomuCode;
import jp.co.ndensan.reams.uz.uza.biz.GyoseikuCode;
import jp.co.ndensan.reams.uz.uza.biz.HojinNo;
import jp.co.ndensan.reams.uz.uza.biz.Katagaki;
import jp.co.ndensan.reams.uz.uza.biz.KojinNo;
import jp.co.ndensan.reams.uz.uza.biz.LasdecCode;
import jp.co.ndensan.reams.uz.uza.biz.MailAddress;
import jp.co.ndensan.reams.uz.uza.biz.SetaiCode;
import jp.co.ndensan.reams.uz.uza.biz.ShikibetsuCode;
import jp.co.ndensan.reams.uz.uza.biz.ShogakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.TelNo;
import jp.co.ndensan.reams.uz.uza.biz.TohyokuCode;
import jp.co.ndensan.reams.uz.uza.biz.TsuzukigaraCode;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.biz.ZenkokuJushoCode;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.RDateTime;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import jp.co.ndensan.reams.uz.uza.util.db.DbTableEntityBase;
import jp.co.ndensan.reams.uz.uza.util.db.IDbAccessable;

/**
 * 給付被保宛名情報高額一時テーブルのエンティティクラスです。
 *
 * @reamsid_L DBC-2010-040 huzongcheng
 */
@lombok.Setter
@lombok.Getter
@SuppressWarnings("PMD.UnusedPrivateField")
public class TempKyufuHihokenAtenaEntity
        extends DbTableEntityBase<TempKyufuHihokenAtenaEntity> implements IDbAccessable {

    private HihokenshaNo hihokenshaNo;
    private FlexibleDate idoYMD;
    private RString edaNo;
    private RString idoJiyuCode;
    private LasdecCode shichosonCode;
    private ShikibetsuCode shikibetsuCode;
    private RString shikakuShutokuJiyuCode;
    private FlexibleDate shikakuShutokuYMD;
    private FlexibleDate shikakuShutokuTodokedeYMD;
    private FlexibleDate ichigoShikakuShutokuYMD;
    private RString hihokennshaKubunCode;
    private RString shikakuSoshitsuJiyuCode;
    private FlexibleDate shikakuSoshitsuYMD;
    private FlexibleDate shikakuSoshitsuTodokedeYMD;
    private RString shikakuHenkoJiyuCode;
    private FlexibleDate shikakuHenkoYMD;
    private FlexibleDate shikakuHenkoTodokedeYMD;
    private RString jushochitokureiTekiyoJiyuCode;
    private FlexibleDate jushochitokureiTekiyoYMD;
    private FlexibleDate jushochitokureiTekiyoTodokedeYMD;
    private RString jushochitokureiKaijoJiyuCode;
    private FlexibleDate jushochitokureiKaijoYMD;
    private FlexibleDate jushochitokureiKaijoTodokedeYMD;
    private RString jushochiTokureiFlag;
    private RString koikinaiJushochiTokureiFlag;
    private LasdecCode koikinaiTokureiSochimotoShichosonCode;
    private LasdecCode kyuShichosonCode;
    private boolean logicalDeletedFlag;

    private ShikibetsuCode atena_shikibetsuCode;
    private LasdecCode atena_genLasdecCode;
    private LasdecCode atena_kyuLasdecCode;
    private int atena_kyuLasdecCodeRenban;
    private GyomuCode atena_gyomuCode;
    private int atena_rirekiNo;
    private boolean atena_currentFlag;
    private RString atena_juminShubetsuCode;
    private KojinNo atena_kojinNo;
    private HojinNo atena_hojinNo;
    private FlexibleDate atena_shoriYMD;
    private RString atena_idoJiyuCode;
    private FlexibleDate atena_idoYMD;
    private RString atena_todokedeJiyuCode;
    private FlexibleDate atena_todokedeYMD;
    private Code atena_idoRiyuCode;
    private AtenaMeisho atena_meisho;
    private AtenaKanaMeisho atena_kanaMeisho;
    private RString atena_kannaiKangaiKubun;
    private YubinNo atena_yubinNo;
    private ChoikiCode atena_choikiCode;
    private ZenkokuJushoCode atena_zenkokuJushoCode;
    private AtenaJusho atena_jusho;
    private BanchiCode atena_banchiCode1;
    private BanchiCode atena_banchiCode2;
    private BanchiCode atena_banchiCode3;
    private BanchiCode atena_banchiCode4;
    private AtenaBanchi atena_banchi;
    private Katagaki atena_katagaki;
    private boolean atena_katagakiInjiFlag;
    private GyoseikuCode atena_gyoseikuCode;
    private RString atena_gyoseikuName;
    private ChikuCode atena_chikuCode1;
    private RString atena_chikuName1;
    private ChikuCode atena_chikuCode2;
    private RString atena_chikuName2;
    private ChikuCode atena_chikuCode3;
    private RString atena_chikuName3;
    private ShogakkokuCode atena_shogakkokuCode;
    private RString atena_shogakkokuName;
    private ChugakkokuCode atena_chugakkokuCode;
    private RString atena_chugakkokuName;
    private TohyokuCode atena_tohyokuCode;
    private RString atena_tohyokuName;
    private RString atena_juminJotaiCode;
    private SetaiCode atena_setaiCode;
    private FlexibleDate atena_seinengappiYMD;
    private RString atena_seinengappiFushoKubun;
    private RString atena_seibetsuCode;
    private TsuzukigaraCode atena_tsuzukigaraCode;
    private RString atena_tsuzukigara;
    private int atena_kazokuNo;
    private int atena_juminhyoHyojijun;
    private FlexibleDate atena_kikaYMD;
    private AtenaMeisho atena_kanjiShimei;
    private AtenaKanaMeisho atena_kanaShimei;
    private ZenkokuJushoCode atena_honsekiZenkokuJushoCode;
    private ChoikiCode atena_honsekiChoikiCode;
    private AtenaJusho atena_honsekiJusho;
    private AtenaBanchi atena_honsekiBanchi;
    private AtenaMeisho atena_hittosha;
    private AtenaMeisho atena_gaikokujinShimei;
    private AtenaMeisho atena_gaikokujinHeikimei;
    private AtenaKanaMeisho atena_gaikokujinKanaShimei;
    private AtenaMeisho atena_tsushomei;
    private RString atena_shimeiRiyoKubun;
    private AtenaKanaMeisho atena_kanaTsushomei;
    private AtenaKanaMeisho atena_katakanaHyoki;
    private Code atena_kokusekiChiikiCode;
    private Code atena_zairyuShikakuCode;
    private RString atena_zairyuKikanCode;
    private FlexibleDate atena_zairyuKikantoManryoYMD;
    private RString atena_zairyuCardtoNo;
    private FlexibleDate atena_zairyuCardtoYukoYMD;
    private RString atena_dai30Jono45niKiteisuruKubun;
    private ShikibetsuCode atena_setainushiShikibetsuCode;
    private AtenaMeisho atena_setainushiMei;
    private Code atena_hojinKeitaiCode;
    private RString atena_hojinKeitaiMeisho;
    private RString atena_hojinKeitaiRyakusho;
    private RString atena_hojinMeishoHenshuKubun;
    private RString atena_hojinKeitaiRyakushoKubun;
    private AtenaMeisho atena_hojinMeisho;
    private AtenaKanaMeisho atena_hojinKanaMeisho;
    private AtenaMeisho atena_hojinShitenMeisho;
    private AtenaKanaMeisho atena_hojinShitenKanaMeisho;
    private ShikibetsuCode atena_daihyoshaShikibetsuCode;
    private RString atena_daihyoshaJuminShubetsu;
    private AtenaMeisho atena_daihyoshaShimei;
    private AtenaKanaMeisho atena_daihyoshaKanaShimei;
    private AtenaMeisho atena_daihyoshaNihonjinShimei;
    private AtenaKanaMeisho atena_daihyoshaNihonjinKanaShimei;
    private AtenaMeisho atena_daihyoshaGaikokujinShimei;
    private AtenaMeisho atena_daihyoshaGaikokujinHeikimei;
    private AtenaKanaMeisho atena_daihyoshaGaikokujinKanaShimei;
    private AtenaMeisho atena_daihyoshaTsushomei;
    private RString atena_daihyoshaShimeiRiyoKubun;
    private AtenaKanaMeisho atena_daihyoshaKanaTsushomei;
    private RString atena_daihyoshaKannaiKangaiKubun;
    private YubinNo atena_daihyoshaYubinNo;
    private ChoikiCode atena_daihyoshaChoikiCode;
    private ZenkokuJushoCode atena_daihyoshaZenkokuJushoCode;
    private AtenaJusho atena_daihyoshaJusho;
    private BanchiCode atena_daihyoshaBanchiCode1;
    private BanchiCode atena_daihyoshaBanchiCode2;
    private BanchiCode atena_daihyoshaBanchiCode3;
    private BanchiCode atena_daihyoshaBanchiCode4;
    private AtenaBanchi atena_daihyoshaBanchi;
    private Katagaki atena_daihyoshaKatagaki;
    private Code atena_ninkachiendantaiTorokuShikakuKubun;
    private FlexibleDate atena_ninkachiendantaiNinkaYMD;
    private RString atena_kojinHojinKBN;
    private AtenaMeisho atena_kyoyushaMeisho;
    private AtenaKanaMeisho atena_kyoyushaKanaMeisho;
    private RString atena_torokuJiyuCode;
    private FlexibleDate atena_torokuIdoYMD;
    private FlexibleDate atena_torokuTodokedeYMD;
    private RString atena_juteiJiyuCode;
    private FlexibleDate atena_juteiIdoYMD;
    private FlexibleDate atena_juteiTodokedeYMD;
    private RString atena_shojoJiyuCode;
    private FlexibleDate atena_shojoIdoYMD;
    private FlexibleDate atena_shojoTodokedeYMD;
    private YubinNo atena_jutonaiYubinNo;
    private ChoikiCode atena_jutonaiChoikiCode;
    private RString atena_jutonaiJusho;
    private BanchiCode atena_jutonaiBanchiCode1;
    private BanchiCode atena_jutonaiBanchiCode2;
    private BanchiCode atena_jutonaiBanchiCode3;
    private BanchiCode atena_jutonaiBanchiCode4;
    private AtenaBanchi atena_jutonaiBanchi;
    private Katagaki atena_jutonaiKatagaki;
    private boolean atena_jutonaiKatagakiInjiFlag;
    private YubinNo atena_tennyumaeYubinNo;
    private ZenkokuJushoCode atena_tennyumaeZenkokuJushoCode;
    private AtenaJusho atena_tennyumaeJusho;
    private AtenaBanchi atena_tennyumaeBanchi;
    private Katagaki atena_tennyumaeKatagaki;
    private RString atena_tennyumaeSetainushimei;
    private AtenaMeisho atena_tennyumaeKyusei;
    private YubinNo atena_saishuJutochiYubinNo;
    private ZenkokuJushoCode atena_saishuJutochiZenkokuJushoCode;
    private AtenaJusho atena_saishuJutochiJusho;
    private AtenaBanchi atena_saishuJutochiBanchi;
    private Katagaki atena_saishuJutochiKatagaki;
    private RString atena_saishuJutochiSetainushimei;
    private FlexibleDate atena_tenshutsuYoteiIdoYMD;
    private YubinNo atena_tenshutsuYoteiYubinNo;
    private ZenkokuJushoCode atena_tenshutsuYoteiZenkokuJushoCode;
    private AtenaJusho atena_tenshutsuYoteiJusho;
    private AtenaBanchi atena_tenshutsuYoteiBanchi;
    private Katagaki atena_tenshutsuYoteiKatagaki;
    private RString atena_tenshutsuYoteiSetainushimei;
    private FlexibleDate atena_tenshutsuKakuteiIdoYMD;
    private FlexibleDate atena_tenshutsuKakuteiTsuchiYMD;
    private YubinNo atena_tenshutsuKakuteiYubinNo;
    private ZenkokuJushoCode atena_tenshutsuKakuteiZenkokuJushoCode;
    private AtenaJusho atena_tenshutsuKakuteiJusho;
    private AtenaBanchi atena_tenshutsuKakuteiBanchi;
    private Katagaki atena_tenshutsuKakuteiKatagaki;
    private RString atena_tenshutsuKakuteiSetainushimei;
    private RString atena_juminhyoUtsushiHakkoSeigyoKubun;
    private TelNo atena_renrakusaki1;
    private TelNo atena_kensakuRenrakusaki1;
    private Code atena_renrakusakiKubun1;
    private TelNo atena_renrakusaki2;
    private TelNo atena_kensakuRenrakusaki2;
    private Code atena_renrakusakiKubun2;
    private TelNo atena_renrakusaki3;
    private TelNo atena_kensakuRenrakusaki3;
    private Code atena_renrakusakiKubun3;
    private MailAddress atena_mailAddress;
    private RString atena_biko;
    private RString atena_kanaName;
    private RString atena_gaikokujinKanaName;
    private RString atena_kanaTsushoName;
    private RDateTime atena_lastUpdateTimestamp;
    private RString atena_lastUpdateReamsLoginId;
    private int atena_jutogaiKanriUpdateCount;
    private TorokuNo atena_jutogaiKanriTorokuNo;
    private int atena_jutogaiKojinKihonUpdateCount;
    private TorokuNo atena_jutogaiKojinKihonTorokuNo;
    private int atena_jutogaiNihonjinUpdateCount;
    private TorokuNo atena_jutogaiNihonjinTorokuNo;
    private int atena_jutogaiGaikokujinUpdateCount;
    private TorokuNo atena_jutogaiGaikokujinTorokuNo;
    private int atena_hojinUpdateCount;
    private TorokuNo atena_hojinTorokuNo;
    private int atena_kyoyushaUpdateCount;
    private TorokuNo atena_kyoyushaTorokuNo;
    private TorokuNo atena_shimeiSearchTorokuNo;
    private int atena_yusenShimeiUpdateCount;
    private RDateTime atena_yusenShimeiTimestamp;
}
