/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jp.co.ndensan.reams.db.dba.business.report.hihokenshashob4;

import jp.co.ndensan.reams.uz.uza.lang.RString;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * 介護保険被保険者証（B4版）BodyEntityリストです。
 */
@Getter
@Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class HihokenshashoB4BodyItem {
    private RString yukokigen;
    private RString hihokenshanno;
    private RString yubinno;
    private RString gyoseiku;
    private RString gyoseikuS;
    private RString hihojusho;
    private RString hihokana;
    private RString hihoname;
    private RString umareMeiji;
    private RString umareTaisho;
    private RString umareShowa;
    private RString umareYy;
    private RString seibetsuMan;
    private RString seibetsuWoman;
    private RString kofuymdGengo;
    private RString saikofu1;
    private RString hokenshano1;
    private RString hokenshano2;
    private RString hokenshano3;
    private RString hokenshano4;
    private RString hokenshano5;
    private RString hokenshano6;
    private RString kaigokbn;
    private RString ninteiymd;
    private RString yukokikanst;
    private RString yukokikaned;
    private RString homonkikanst;
    private RString homonkikaned;
    private RString servicetani;
    private RString service1;
    private RString ten0;
    private RString shurui1;
    private RString shurui2;
    private RString shurui3;
    private RString shurui4;
    private RString shurui5;
    private RString shurui6;
    private RString shuruigendo1;
    private RString shuruigendo2;
    private RString shuruigendo3;
    private RString shuruigendo4;
    private RString shuruigendo5;
    private RString shuruigendo6;
    private RString ten1;
    private RString ten2;
    private RString ten3;
    private RString ten4;
    private RString ten5;
    private RString ten6;
    private RString ryui;
    private RString saikofu2;
    private RString seigen1;
    private RString seigenLong1;
    private RString seigen2;
    private RString seigenLong2;
    private RString seigen3;
    private RString seigenLong3;
    private RString seigen4;
    private RString seigenLong4;
    private RString seigen5;
    private RString seigenLong5;
    private RString seigen6;
    private RString seigenLong6;
    private RString seigenSt1;
    private RString seigenEd1;
    private RString seigenSt2;
    private RString seigenEd2;
    private RString seigenSt3;
    private RString seigenEd3;
    private RString gyosha;
    private RString todokeYmd1;
    private RString gyosha2;
    private RString todokeYmd2;
    private RString gyosha3;
    private RString todokeYmd3;
    private RString shisetsuSyu1;
    private RString shisetsuname1;
    private RString nyushochk1;
    private RString nyuinchk1;
    private RString taishochk1;
    private RString taiinchk1;
    private RString nyushoymd1;
    private RString taiinymd1;
    private RString shisetsuSyu2;
    private RString shisetsuname2;
    private RString nyushochk2;
    private RString nyuinchk2;
    private RString taishochk2;
    private RString taiinchk2;
    private RString nyushoymd2;
    private RString taiinymd2;
    private RString renban;
    private RString seiShogai1;
    private RString seiShogai2;
    private RString kosekiSeibetsu1;
    private RString kosekiSeibetsu2;
    private RString itakuGyosha1;
    private RString itakuGyosha2;
    private RString itakuGyosha3;
    
    private RString yukokigen2;
    private RString hihokenshanno2;
    private RString yubinno2;
    private RString gyoseiku2;
    private RString gyoseikuS2;
    private RString hihojusho2;
    private RString hihokana2;
    private RString hihoname2;
    private RString umareMeiji2;
    private RString umareTaisho2;
    private RString umareShowa2;
    private RString umareYy2;
    private RString seibetsuMan2;
    private RString seibetsuWoman2;
    private RString kofuymdGengo2;
    private RString saikofu12;
    private RString hokenshano12;
    private RString hokenshano22;
    private RString hokenshano32;
    private RString hokenshano42;
    private RString hokenshano52;
    private RString hokenshano62;
    private RString kaigokbn2;
    private RString ninteiymd2;
    private RString yukokikanst2;
    private RString yukokikaned2;
    private RString homonkikanst2;
    private RString homonkikaned2;
    private RString servicetani2;
    private RString service12;
    private RString ten02;
    private RString shurui12;
    private RString shurui22;
    private RString shurui32;
    private RString shurui42;
    private RString shurui52;
    private RString shurui62;
    private RString shuruigendo12;
    private RString shuruigendo22;
    private RString shuruigendo32;
    private RString shuruigendo42;
    private RString shuruigendo52;
    private RString shuruigendo62;
    private RString ten12;
    private RString ten22;
    private RString ten32;
    private RString ten42;
    private RString ten52;
    private RString ten62;
    private RString ryui2;
    private RString saikofu22;
    private RString seigen12;
    private RString seigenLong12;
    private RString seigen22;
    private RString seigenLong22;
    private RString seigen32;
    private RString seigenLong32;
    private RString seigen42;
    private RString seigenLong42;
    private RString seigen52;
    private RString seigenLong52;
    private RString seigen62;
    private RString seigenLong62;
    private RString seigenSt12;
    private RString seigenEd12;
    private RString seigenSt22;
    private RString seigenEd22;
    private RString seigenSt32;
    private RString seigenEd32;
    private RString gyosha02;
    private RString todokeYmd12;
    private RString gyosha22;
    private RString todokeYmd22;
    private RString gyosha32;
    private RString todokeYmd32;
    private RString shisetsuSyu12;
    private RString shisetsuname12;
    private RString nyushochk12;
    private RString nyuinchk12;
    private RString taishochk12;
    private RString taiinchk12;
    private RString nyushoymd12;
    private RString taiinymd12;
    private RString shisetsuSyu22;
    private RString shisetsuname22;
    private RString nyushochk22;
    private RString nyuinchk22;
    private RString taishochk22;
    private RString taiinchk22;
    private RString nyushoymd22;
    private RString taiinymd22;
    private RString renban2;
    private RString seiShogai12;
    private RString seiShogai22;
    private RString kosekiSeibetsu12;
    private RString kosekiSeibetsu22;
    private RString itakuGyosha12;
    private RString itakuGyosha22;
    private RString itakuGyosha32;

}
