/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbc.entity.db.relate.kogakukaigotaishoshachushutsusokyubun;

import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.HojinKeitai;
import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.JutogaiIdoRiyu;
import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.KokusekiChiikiCode;
import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.NinkaChienDantaiTorokuShikakuKubun;
import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.RenrakusakiKubun;
import jp.co.ndensan.reams.ua.uax.definition.core.valueobject.code.ZairyuShikakuCode;
import jp.co.ndensan.reams.uz.uza.biz.AtenaBanchi;
import jp.co.ndensan.reams.uz.uza.biz.AtenaJusho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaKanaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.AtenaMeisho;
import jp.co.ndensan.reams.uz.uza.biz.BanchiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChikuCode;
import jp.co.ndensan.reams.uz.uza.biz.ChoikiCode;
import jp.co.ndensan.reams.uz.uza.biz.ChugakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.GyomuCode;
import jp.co.ndensan.reams.uz.uza.biz.GyoseikuCode;
import jp.co.ndensan.reams.uz.uza.biz.HojinNo;
import jp.co.ndensan.reams.uz.uza.biz.Katagaki;
import jp.co.ndensan.reams.uz.uza.biz.KojinNo;
import jp.co.ndensan.reams.uz.uza.biz.LasdecCode;
import jp.co.ndensan.reams.uz.uza.biz.MailAddress;
import jp.co.ndensan.reams.uz.uza.biz.SetaiCode;
import jp.co.ndensan.reams.uz.uza.biz.ShikibetsuCode;
import jp.co.ndensan.reams.uz.uza.biz.ShogakkokuCode;
import jp.co.ndensan.reams.uz.uza.biz.TelNo;
import jp.co.ndensan.reams.uz.uza.biz.TohyokuCode;
import jp.co.ndensan.reams.uz.uza.biz.TsuzukigaraCode;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.biz.ZenkokuJushoCode;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.RDateTime;
import jp.co.ndensan.reams.uz.uza.lang.RString;

/**
 * 高額介護対象者抽出（遡及分）
 *
 * @reamsid_L DBC-5750-050 houtianpeng
 */
@lombok.Getter
@lombok.Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class UaFt001FindEntity {

    private ShikibetsuCode shikibetsuCode;
    private int torokuNo;
    private RDateTime idoShoriTimestamp;
    private RString idoZengoKubun;
    private RDateTime lastUpdateTimestamp;
    private RString lastUpdateReamsLoginId;
    private LasdecCode genLasdecCode;
    private LasdecCode kyuLasdecCode;
    private int kyuLasdecCodeRenban;
    private GyomuCode gyomuCode;
    private int rirekiNo;
    private boolean currentFlag;
    private RString juminShubetsuCode;
    private KojinNo kojinNo;
    private HojinNo hojinNo;
    private FlexibleDate shoriYMD;
    private RString shoriJiyuCode;
    private RString idoJiyuCode;
    private FlexibleDate idoYMD;
    private RString todokedeJiyuCode;
    private FlexibleDate todokedeYMD;
    private JutogaiIdoRiyu idoRiyuCode;
    private RString kannaiKangaiKubun;
    private YubinNo yubinNo;
    private ChoikiCode choikiCode;
    private ZenkokuJushoCode zenkokuJushoCode;
    private AtenaJusho jusho;
    private BanchiCode banchiCode1;
    private BanchiCode banchiCode2;
    private BanchiCode banchiCode3;
    private BanchiCode banchiCode4;
    private AtenaBanchi banchi;
    private Katagaki katagaki;
    private boolean katagakiInjiFlag;
    private GyoseikuCode gyoseikuCode;
    private RString gyoseiku;
    private ChikuCode chikuCode1;
    private RString chiku1;
    private ChikuCode chikuCode2;
    private RString chiku2;
    private ChikuCode chikuCode3;
    private RString chiku3;
    private ShogakkokuCode shogakkokuCode;
    private RString shogakkokuName;
    private ChugakkokuCode chugakkokuCode;
    private RString chugakkokuName;
    private TohyokuCode tohyokuCode;
    private RString tohyokuName;
    private TelNo renrakusaki1;
    private TelNo kensakuRenrakusaki1;
    private RenrakusakiKubun renrakusakiKubun1;
    private TelNo renrakusaki2;
    private TelNo kensakuRenrakusaki2;
    private RenrakusakiKubun renrakusakiKubun2;
    private TelNo renrakusaki3;
    private TelNo kensakuRenrakusaki3;
    private RenrakusakiKubun renrakusakiKubun3;
    private MailAddress mailAddress;
    private RString juminJotaiCode;
    private SetaiCode setaiCode;
    private FlexibleDate seinengappiYMD;
    private RString seinengappiFushoKubun;
    private RString seibetsuCode;
    private TsuzukigaraCode tsuzukigaraCode;
    private RString tsuzukigara;
    private int kazokuNo;
    private RString juminhyoCode;
    private int juminhyoHyojijun;
    private FlexibleDate kikaYMD;
    private AtenaMeisho kanjiShimei;
    private AtenaKanaMeisho kanaShimei;
    private ZenkokuJushoCode honsekiZenkokuJushoCode;
    private AtenaJusho honsekiJusho;
    private BanchiCode honsekiBanchiCode1;
    private BanchiCode honsekiBanchiCode2;
    private BanchiCode honsekiBanchiCode3;
    private BanchiCode honsekiBanchiCode4;
    private AtenaBanchi honsekiBanchi;
    private AtenaMeisho hittosha;
    private AtenaMeisho gaikokujinShimei;
    private AtenaMeisho gaikokujinHeikimei;
    private AtenaKanaMeisho gaikokujinKanaShimei;
    private AtenaMeisho tsushomei;
    private RString shimeiRiyoKubun;
    private AtenaKanaMeisho kanaTsushomei;
    private FlexibleDate tsushoIdoYMD;
    private AtenaKanaMeisho katakanaHyoki;
    private KokusekiChiikiCode kokusekiChiikiCode;
    private ZairyuShikakuCode zairyuShikakuCode;
    private RString zairyuKikanCode;
    private FlexibleDate zairyuKikantoManryoYMD;
    private RString zairyuCardtoNo;
    private FlexibleDate zairyuCardtoYukoYMD;
    private RString dai30Jono45niKiteisuruKubun;
    private RString jukyochiTodokedeKubun;
    private ShikibetsuCode setainushiShikibetsuCode;
    private AtenaMeisho setainushimei;
    private AtenaMeisho setainushiHeikimei;
    private AtenaMeisho setainushiTsushomei;
    private AtenaMeisho setainushiYusenShimei;
    private HojinKeitai hojinKeitaiCode;
    private RString hojinMeiHenshuKubun;
    private RString hojinKeitaiRyakushoKubun;
    private AtenaMeisho hojinMeisho;
    private AtenaKanaMeisho hojinKanaMeisho;
    private AtenaMeisho hojinShitenMeisho;
    private AtenaKanaMeisho hojinShitenKanaMeisho;
    private ShikibetsuCode daihyoshaShikibetsuCode;
    private AtenaMeisho daihyoshaShimei;
    private AtenaKanaMeisho daihyoshaKanaShimei;
    private NinkaChienDantaiTorokuShikakuKubun ninkachiendantaiTorokuShikakuKubun;
    private FlexibleDate ninkachiendantaiNinkaYMD;
    private RString kojinHojinKBN;
    private AtenaMeisho kyoyushaMeisho;
    private AtenaKanaMeisho kyoyushaKanaMeisho;
    private RString torokuJiyuCode;
    private FlexibleDate torokuIdoYMD;
    private FlexibleDate torokuTodokedeYMD;
    private boolean torokuTsuchiFlag;
    private RString juteiJiyuCode;
    private FlexibleDate juteiIdoYMD;
    private FlexibleDate juteiTodokedeYMD;
    private RString juminhyoJuteiJiyu;
    private boolean juteiTsuchiFlag;
    private RString shojoJiyuCode;
    private FlexibleDate shojoIdoYMD;
    private RString aimaiShojobiMongon;
    private FlexibleDate shojoTodokedeYMD;
    private boolean shojoTsuchiFlag;
    private YubinNo tennyumaeYubinNo;
    private ZenkokuJushoCode tennyumaeZenkokuJushoCode;
    private AtenaJusho tennyumaeJusho;
    private AtenaBanchi tennyumaeBanchi;
    private Katagaki tennyumaeKatagaki;
    private RString tennyumaeSetainushimei;
    private boolean tennyumaeJushoMitodokeFlag;
    private RString tennyumaeKyusei;
    private RString tennyumaeTenshutsunyuRiyuCode;
    private YubinNo saishuJutochiYubinNo;
    private ZenkokuJushoCode saishuJutochiZenkokuJushoCode;
    private AtenaJusho saishuJutochiJusho;
    private AtenaBanchi saishuJutochiBanchi;
    private Katagaki saishuJutochiKatagaki;
    private RString saishuJutochiSetainushimei;
    private FlexibleDate tenshutsuYoteiIdoYMD;
    private YubinNo tenshutsuYoteiYubinNo;
    private ZenkokuJushoCode tenshutsuYoteiZenkokuJushoCode;
    private AtenaJusho tenshutsuYoteiJusho;
    private AtenaBanchi tenshutsuYoteiBanchi;
    private Katagaki tenshutsuYoteiKatagaki;
    private RString tenshutsuYoteiSetainushimei;
    private RString tenshutsuYoteiTenshutsunyuRiyuCode;
    private FlexibleDate tenshutsuKakuteiIdoYMD;
    private FlexibleDate tenshutsuKakuteiTsuchiYMD;
    private YubinNo tenshutsuKakuteiYubinNo;
    private ZenkokuJushoCode tenshutsuKakuteiZenkokuJushoCode;
    private AtenaJusho tenshutsuKakuteiJusho;
    private AtenaBanchi tenshutsuKakuteiBanchi;
    private Katagaki tenshutsuKakuteiKatagaki;
    private RString tenshutsuKakuteiSetainushimei;
    private RString tenshutsuKakuteiTenshutsunyuRiyuCode;
    private RString juminhyoUtsushiHakkoSeigyoKubun;
    private RString biko;
    private RString kanaName;
    private RString gaikokujinKanaName;
    private RString kanaTsushoName;
    private int idoId;
}
