/// <reference path="../d.ts/jquery.d.ts" />
/// <reference path="../d.ts/UzViewControls.d.ts" />

module DBZ {
    /**
     * 自動生成コードです。修正しないでください。
     * HihokenshaShikakuHakkoクラスのみで継承して使えます。
     */
    export class HihokenshaShikakuHakko_Design extends Uz.CommonChildDiv {
    
        public get txtYukoKigen_displayNone() {
            return Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"])["displayNone"];
        }
        
        public set txtYukoKigen_displayNone(value) {
            if ( $("#" + this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"]).length > 0 && 
                 Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"]) != undefined ) {
                Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"])["displayNone"] = value;
            } else {
                this.layout.items[0].items[3]["displayNone"] = value;
                this.raisePropertyChanged(this.layout);
            }
        }
        
        constructor($parentElement: JQuery, isDesignMode: bool, fieldName: string) {
            super($parentElement, isDesignMode, HihokenshaShikakuHakko_Design.myLayout, fieldName);
        }
        
        /**
         * レイアウト情報のプロパティを登録します
         * @method registProperty
         */
        public registProperty() {
            super.registProperty();
            Uz.JSControlUtil.registProperty("txtYukoKigen_displayNone");
        }
        
        /**
         * コントロール内で編集させたいプロパティをまとめたEditablePropertyInfoオブジェクトを返却します。
         * @method getEditableProperty
         * @return EditablePropertyInfoオブジェクト
         */
        public getEditablePropertyInfo(): any {
            var editablePropertyInfo = super.getEditablePropertyInfo();
            editablePropertyInfo["txtYukoKigen_displayNone"] = Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"]).getEditablePropertyInfo()["displayNone"];
            
            return editablePropertyInfo;
        }
        public static myLayout = {
 "fieldName": "defaultLayout",
 "items": [
  {
   "fieldName": "HihokenshaShikakuHakko",
   "items": [
    {
     "fieldName": "radInjiIchi",
     "items": [],
     "controlType": "RadioButton",
     "width": "120",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "selectedItem": "upside",
     "dataSource": [
      {
       "key": "upside",
       "value": "上段"
      },
      {
       "key": "downside",
       "value": "下段"
      }
     ],
     "required": false,
     "onClick": "",
     "newLineItemNumber": 2,
     "spaceSize": 1,
     "labelLText": "印字位置:",
     "labelLWidth": "６０",
     "labelLAlign": 2
    },
    {
     "fieldName": "txtKofuDate",
     "items": [],
     "controlType": "TextBoxFlexibleDate",
     "width": "80",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "required": false,
     "labelLText": "交付日",
     "labelLWidth": "60",
     "labelLAlign": 2,
     "readOnly": false,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "onFocus": "",
     "onBlur": "",
     "onKeyPress": "",
     "text": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0,
     "ymdKubun": 2,
     "displayFormat": 0,
     "value": "",
     "permitCharactor": "./_-"
    },
    {
     "fieldName": "ddlKofuJiyu",
     "items": [],
     "controlType": "DropDownList",
     "width": "132",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "selectedItem": "",
     "dataSource": [
      {
       "key": "shikakuShutoku",
       "value": "資格取得"
      },
      {
       "key": "yokaigoNintei",
       "value": "要介護認定"
      },
      {
       "key": "kyojuKeikaku",
       "value": "居住計画"
      },
      {
       "key": "kyufuSeigen",
       "value": "給付制限"
      },
      {
       "key": "jutokuTekiyo",
       "value": "住所地特例適用"
      },
      {
       "key": "jutokuKaijo",
       "value": "住所地特例解除"
      },
      {
       "key": "koikiTenkyo",
       "value": "広域転居"
      },
      {
       "key": "kigenGire",
       "value": "期限切れ"
      },
      {
       "key": "yoshikiHenko",
       "value": "様式変更"
      },
      {
       "key": "kisaiHenko",
       "value": "記載変更"
      },
      {
       "key": "saikofu",
       "value": "再交付"
      }
     ],
     "required": false,
     "labelLText": "交付事由",
     "labelLWidth": "60",
     "labelLAlign": 2,
     "onFocus": "",
     "onBlur": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0
    },
    {
     "fieldName": "txtYukoKigen",
     "items": [],
     "controlType": "TextBoxFlexibleDate",
     "width": "80",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "required": false,
     "labelLText": "有効期限",
     "labelLWidth": "85",
     "labelLAlign": 2,
     "readOnly": false,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "onFocus": "",
     "onBlur": "",
     "onKeyPress": "",
     "text": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0,
     "ymdKubun": 2,
     "displayFormat": 0,
     "value": "",
     "permitCharactor": "./_-"
    },
    {
     "fieldName": "txtHokensha",
     "items": [],
     "controlType": "TextBox",
     "width": "200",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "required": false,
     "labelLText": "保険者",
     "labelLWidth": "60",
     "labelLAlign": 2,
     "readOnly": true,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "onFocus": "",
     "onBlur": "",
     "onKeyPress": "",
     "text": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0,
     "value": "",
     "maxLength": 1000000000000,
     "minLength": 0,
     "textAlign": 0,
     "isComboBox": false,
     "suggest": [],
     "permitCharactor": ""
    },
    {
     "fieldName": "txtYokaigodo",
     "items": [],
     "controlType": "TextBox",
     "width": "50",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "required": false,
     "labelLText": "要介護度",
     "labelLWidth": "60",
     "labelLAlign": 2,
     "readOnly": true,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "onFocus": "",
     "onBlur": "",
     "onKeyPress": "",
     "text": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0,
     "value": "",
     "maxLength": 1000000000000,
     "minLength": 0,
     "textAlign": 0,
     "isComboBox": false,
     "suggest": [],
     "permitCharactor": ""
    },
    {
     "fieldName": "txtShinseiDate",
     "items": [],
     "controlType": "TextBoxFlexibleDate",
     "width": "80",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "required": false,
     "labelLText": "申請日",
     "labelLWidth": "45",
     "labelLAlign": 2,
     "readOnly": true,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "onFocus": "",
     "onBlur": "",
     "onKeyPress": "",
     "text": "",
     "labelRText": "",
     "labelRWidth": "S",
     "labelRAlign": 0,
     "ymdKubun": 2,
     "displayFormat": 0,
     "value": "",
     "permitCharactor": "./_-"
    },
    {
     "fieldName": "tabHihokenshaShikakuShosai",
     "items": [
      {
       "fieldName": "tplGendoGaku",
       "items": [
        {
         "fieldName": "txtServiceShurui",
         "items": [],
         "controlType": "TextBox",
         "width": "220",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onChange": "",
         "required": false,
         "labelLText": "サービス種類",
         "labelLWidth": "90",
         "labelLAlign": 2,
         "readOnly": true,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onKeyPress": "",
         "text": "",
         "labelRText": "",
         "labelRWidth": "S",
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": ""
        },
        {
         "fieldName": "txtYukoKikan",
         "items": [],
         "controlType": "TextBoxDateRange",
         "width": "80",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onChange": "",
         "labelLText": "有効期間",
         "labelLWidth": "60",
         "labelLAlign": 2,
         "readOnly": true,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onKeyPress": "",
         "labelRText": "",
         "labelRWidth": "S",
         "labelRAlign": 0,
         "ymdKubun": 2,
         "displayFormat": 0,
         "permitCharactor": "",
         "fromPlaceHolder": "",
         "toPlaceHolder": "",
         "minDate": "",
         "maxDate": "",
         "fromText": "",
         "toText": "",
         "fromValue": "",
         "toValue": ""
        },
        {
         "fieldName": "txtKubunShikyuGendoKijunGaku",
         "items": [],
         "controlType": "TextBoxNum",
         "width": "50",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onChange": "",
         "required": false,
         "labelLText": "区分支給限度基準額",
         "labelLWidth": "135",
         "labelLAlign": 2,
         "readOnly": true,
         "placeHolder": "",
         "textKind": 2,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onKeyPress": "",
         "text": "",
         "labelRText": "",
         "labelRWidth": "S",
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 2,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": "+-,.\\",
         "maxValue": 1.7976931348623157e+308,
         "minValue": 0,
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": 0
        },
        {
         "fieldName": "lblShuruiShikyuGendoKijunGaku",
         "items": [],
         "controlType": "Label",
         "width": "１８０",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "うち種類支給限度基準額",
         "align": 2
        },
        {
         "fieldName": "dgShuruiShikyuGendoKijunGaku",
         "items": [],
         "controlType": "DataGrid",
         "width": "390",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "M",
         "marginRight": "XS",
         "dataSource": [],
         "gridSetting": {
          "rowHeight": 25,
          "isMultiSelectable": false,
          "isShowFooter": true,
          "isShowFilter": false,
          "isShowFilterButton": false,
          "isShowRowState": false,
          "header": {
           "combineColumns": [],
           "frozenColumn": "",
           "headerHeight": 0
          },
          "columns": [
           {
            "columnName": "サービス種類",
            "dataName": "serviceShurui",
            "toolTip": "",
            "bgColor": 0,
            "width": 270,
            "visible": true,
            "cellType": 0,
            "cellDetails": {
             "cellType": 0
            },
            "align": 0,
            "resize": true,
            "isPrivateInfo": false,
            "sortKey": ""
           },
           {
            "columnName": "限度額",
            "dataName": "gendoGaku",
            "toolTip": "",
            "bgColor": 0,
            "width": 100,
            "visible": true,
            "cellType": 0,
            "cellDetails": {
             "cellType": 0
            },
            "align": 2,
            "resize": true,
            "isPrivateInfo": false,
            "sortKey": ""
           }
          ]
         },
         "height": "125",
         "onSort": "",
         "onSelect": "",
         "onSelectByDblClick": "",
         "onOnlyRow": "",
         "onNoRow": "",
         "onMultiRows": "",
         "sortOrder": "serviceShurui",
         "isAscending": true,
         "filterList": [],
         "activeRowId": -1
        }
       ],
       "controlType": "TabPanel",
       "width": "XS",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "title": "限度額",
       "onActive": ""
      },
      {
       "fieldName": "tplShinsakaiIken",
       "items": [
        {
         "fieldName": "lblShinsakaiIken",
         "items": [],
         "controlType": "Label",
         "width": "105",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "required": false,
         "isPrivateInfo": false,
         "text": "認定審査会意見",
         "align": 2
        },
        {
         "fieldName": "txtShinsakaiIken",
         "items": [],
         "controlType": "TextBoxMultiLine",
         "width": "400",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "M",
         "marginRight": "XS",
         "onChange": "",
         "required": false,
         "labelLText": "",
         "labelLWidth": "XS",
         "labelLAlign": 2,
         "readOnly": true,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "onFocus": "",
         "onBlur": "",
         "onKeyPress": "",
         "text": "",
         "labelRText": "",
         "labelRWidth": "S",
         "labelRAlign": 0,
         "value": "",
         "maxLength": 100000000,
         "minLength": 0,
         "height": "100",
         "limitLength": "198",
         "countDisp": true
        }
       ],
       "controlType": "TabPanel",
       "width": "XS",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "title": "審査会意見",
       "onActive": ""
      },
      {
       "fieldName": "tplKyufuSeigen",
       "items": [
        {
         "fieldName": "tblKyuhuSeigen",
         "items": [
          {
           "fieldName": "celKyufuSeigenNaiyoTitle",
           "items": [
            {
             "fieldName": "lblKyufuSeigenNaiyo",
             "items": [],
             "controlType": "Label",
             "width": "60",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "制限内容",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C1"
          },
          {
           "fieldName": "celKyufuSeigenKikanTitle",
           "items": [
            {
             "fieldName": "lblKyufuSeigenKikan",
             "items": [],
             "controlType": "Label",
             "width": "60",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "制限期間",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C2"
          },
          {
           "fieldName": "celKyufuSeigenNaiyo1",
           "items": [
            {
             "fieldName": "txtKyufuSeigenNaiyo1",
             "items": [],
             "controlType": "TextBox",
             "width": "200",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C1"
          },
          {
           "fieldName": "celKyufuSeigenKikan1",
           "items": [
            {
             "fieldName": "txtKyufuSeigenKikan1",
             "items": [],
             "controlType": "TextBoxDateRange",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "permitCharactor": "",
             "fromPlaceHolder": "",
             "toPlaceHolder": "",
             "minDate": "",
             "maxDate": "",
             "fromText": "",
             "toText": "",
             "fromValue": "",
             "toValue": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C2"
          },
          {
           "fieldName": "celKyufuSeigenNaiyo2",
           "items": [
            {
             "fieldName": "txtKyufuSeigenNaiyo2",
             "items": [],
             "controlType": "TextBox",
             "width": "200",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C1"
          },
          {
           "fieldName": "celKyufuSeigenKikan2",
           "items": [
            {
             "fieldName": "txtKyufuSeigenKikan2",
             "items": [],
             "controlType": "TextBoxDateRange",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "permitCharactor": "",
             "fromPlaceHolder": "",
             "toPlaceHolder": "",
             "minDate": "",
             "maxDate": "",
             "fromText": "",
             "toText": "",
             "fromValue": "",
             "toValue": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C2"
          },
          {
           "fieldName": "celKyufuSeigenNaiyo3",
           "items": [
            {
             "fieldName": "txtKyufuSeigenNaiyo3",
             "items": [],
             "controlType": "TextBox",
             "width": "200",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C1"
          },
          {
           "fieldName": "celKyufuSeigenKikan3",
           "items": [
            {
             "fieldName": "txtKyufuSeigenKikan3",
             "items": [],
             "controlType": "TextBoxDateRange",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "permitCharactor": "",
             "fromPlaceHolder": "",
             "toPlaceHolder": "",
             "minDate": "",
             "maxDate": "",
             "fromText": "",
             "toText": "",
             "fromValue": "",
             "toValue": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C2"
          }
         ],
         "controlType": "TablePanel",
         "width": "XS",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "html": "<table>\n  <tbody>\n    <tr><td id='R1C1'></td><td id='R1C2'></td></tr>\n    <tr><td id='R2C1'></td><td id='R2C2'></td></tr>\n    <tr><td id='R3C1'></td><td id='R3C2'></td></tr>\n    <tr><td id='R4C1'></td><td id='R4C2'></td></tr>\n  </tbody>\n</table>\n"
        }
       ],
       "controlType": "TabPanel",
       "width": "XS",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "title": "給付制限",
       "onActive": ""
      },
      {
       "fieldName": "tplShienJigyosha",
       "items": [
        {
         "fieldName": "txtJigyoshaShurui",
         "items": [],
         "controlType": "TextBox",
         "width": "200",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "onChange": "",
         "required": false,
         "labelLText": "事業者種類",
         "labelLWidth": "75",
         "labelLAlign": 2,
         "readOnly": true,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onKeyPress": "",
         "text": "",
         "labelRText": "",
         "labelRWidth": "S",
         "labelRAlign": 0,
         "value": "",
         "maxLength": 1000000000000,
         "minLength": 0,
         "textAlign": 0,
         "isComboBox": false,
         "suggest": [],
         "permitCharactor": ""
        },
        {
         "fieldName": "tblJigyosha",
         "items": [
          {
           "fieldName": "celJigyoshaTitle",
           "items": [
            {
             "fieldName": "lblJigyosha",
             "items": [],
             "controlType": "Label",
             "width": "45",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "事業者",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C1"
          },
          {
           "fieldName": "celTodokedeDateTitle",
           "items": [
            {
             "fieldName": "lblTodokedeDate",
             "items": [],
             "controlType": "Label",
             "width": "45",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "届出日",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C2"
          },
          {
           "fieldName": "celJigyosha1",
           "items": [
            {
             "fieldName": "txtJigyosha1",
             "items": [],
             "controlType": "TextBox",
             "width": "500",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C1"
          },
          {
           "fieldName": "celTodokedeDate1",
           "items": [
            {
             "fieldName": "txtTodokedeDate1",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C2"
          },
          {
           "fieldName": "celJigyosha2",
           "items": [
            {
             "fieldName": "txtJigyosha2",
             "items": [],
             "controlType": "TextBox",
             "width": "500",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C1"
          },
          {
           "fieldName": "celTodokedeDate2",
           "items": [
            {
             "fieldName": "txtTodokedeDate2",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C2"
          },
          {
           "fieldName": "celJigyosha3",
           "items": [
            {
             "fieldName": "txtJigyosha3",
             "items": [],
             "controlType": "TextBox",
             "width": "500",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C1"
          },
          {
           "fieldName": "celTodokedeDate3",
           "items": [
            {
             "fieldName": "txtTodokedeDate3",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C2"
          }
         ],
         "controlType": "TablePanel",
         "width": "XS",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "html": "<table>\n  <tbody>\n    <tr><td id='R1C1'></td><td id='R1C2'></td></tr>\n    <tr><td id='R2C1'></td><td id='R2C2'></td></tr>\n    <tr><td id='R3C1'></td><td id='R3C2'></td></tr>\n    <tr><td id='R4C1'></td><td id='R4C2'></td></tr>\n  </tbody>\n</table>\n"
        }
       ],
       "controlType": "TabPanel",
       "width": "XS",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "title": "支援事業者",
       "onActive": ""
      },
      {
       "fieldName": "tplShisetsuNyutaisho",
       "items": [
        {
         "fieldName": "tblShisetsuNyutaisho",
         "items": [
          {
           "fieldName": "celShisetsuNyushoDateTitle",
           "items": [
            {
             "fieldName": "lblShisetsuNyushoDate",
             "items": [],
             "controlType": "Label",
             "width": "45",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "入所日",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C1"
          },
          {
           "fieldName": "celShisetsuTaishoDateTitle",
           "items": [
            {
             "fieldName": "lblShisetsuTaishoDate",
             "items": [],
             "controlType": "Label",
             "width": "45",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "退所日",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C2"
          },
          {
           "fieldName": "celNyushoShisetsuTitle",
           "items": [
            {
             "fieldName": "lblNyushoShisetsu",
             "items": [],
             "controlType": "Label",
             "width": "60",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "入所施設",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C3"
          },
          {
           "fieldName": "celShisetsuNyushoDate1",
           "items": [
            {
             "fieldName": "txtShisetsuNyushoDate1",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C1"
          },
          {
           "fieldName": "celShisetsuTaishoDate1",
           "items": [
            {
             "fieldName": "txtShisetsuTaishoDate1",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C2"
          },
          {
           "fieldName": "celNyushoShisetsu1",
           "items": [
            {
             "fieldName": "txtNyushoShisetsu1",
             "items": [],
             "controlType": "TextBox",
             "width": "350",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C3"
          },
          {
           "fieldName": "celShisetsuNyushoDate2",
           "items": [
            {
             "fieldName": "txtShisetsuNyushoDate2",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C1"
          },
          {
           "fieldName": "celShisetsuTaishoDate2",
           "items": [
            {
             "fieldName": "txtShisetsuTaishoDate2",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C2"
          },
          {
           "fieldName": "celNyushoShisetsu2",
           "items": [
            {
             "fieldName": "txtNyushoShisetsu2",
             "items": [],
             "controlType": "TextBox",
             "width": "350",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C3"
          },
          {
           "fieldName": "celTaishoJohoTitle",
           "items": [
            {
             "fieldName": "lblTaishoJoho",
             "items": [],
             "controlType": "Label",
             "width": "60",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "対象情報",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C4"
          },
          {
           "fieldName": "celShisetsuShuruiTitle",
           "items": [
            {
             "fieldName": "lblShisetsuShurui",
             "items": [],
             "controlType": "Label",
             "width": "60",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "required": false,
             "isPrivateInfo": false,
             "text": "施設種類",
             "align": 2
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R1C5"
          },
          {
           "fieldName": "celTaishoJoho1",
           "items": [
            {
             "fieldName": "txtTaishoJoho1",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C4"
          },
          {
           "fieldName": "celShisetsuShurui1",
           "items": [
            {
             "fieldName": "txtShisetsuShurui1",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R2C5"
          },
          {
           "fieldName": "celTaishoJoho2",
           "items": [
            {
             "fieldName": "txtTaishoJoho2",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C4"
          },
          {
           "fieldName": "celShisetsuShurui2",
           "items": [
            {
             "fieldName": "txtShisetsuShurui2",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R3C5"
          },
          {
           "fieldName": "celShisetsuNyushoDate3",
           "items": [
            {
             "fieldName": "txtShisetsuNyushoDate3",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C1"
          },
          {
           "fieldName": "celShisetsuTaishoDate3",
           "items": [
            {
             "fieldName": "txtShisetsuTaishoDate3",
             "items": [],
             "controlType": "TextBoxFlexibleDate",
             "width": "80",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": true,
             "dependencies": [],
             "float": 1,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "ymdKubun": 2,
             "displayFormat": 0,
             "value": "",
             "permitCharactor": "./_-"
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C2"
          },
          {
           "fieldName": "celNyushoShisetsu3",
           "items": [
            {
             "fieldName": "txtNyushoShisetsu3",
             "items": [],
             "controlType": "TextBox",
             "width": "350",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C3"
          },
          {
           "fieldName": "celTaishoJoho3",
           "items": [
            {
             "fieldName": "txtTaishoJoho3",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C4"
          },
          {
           "fieldName": "celShisetsuShurui3",
           "items": [
            {
             "fieldName": "txtShisetsuShurui3",
             "items": [],
             "controlType": "TextBox",
             "width": "150",
             "visible": true,
             "displayNone": false,
             "disabled": false,
             "accessKey": "",
             "nextFocusFieldName": "",
             "wrap": false,
             "dependencies": [],
             "float": 0,
             "toolTip": "",
             "authorityMode": 0,
             "marginLeft": "XS",
             "marginRight": "XS",
             "onChange": "",
             "required": false,
             "labelLText": "",
             "labelLWidth": "S",
             "labelLAlign": 2,
             "readOnly": true,
             "placeHolder": "",
             "textKind": 0,
             "isPrivateInfo": false,
             "isPassword": false,
             "onFocus": "",
             "onBlur": "",
             "onKeyPress": "",
             "text": "",
             "labelRText": "",
             "labelRWidth": "S",
             "labelRAlign": 0,
             "value": "",
             "maxLength": 1000000000000,
             "minLength": 0,
             "textAlign": 0,
             "isComboBox": false,
             "suggest": [],
             "permitCharactor": ""
            }
           ],
           "controlType": "TableCell",
           "width": "XS",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": 0,
           "marginRight": 0,
           "connectTd": "R4C5"
          }
         ],
         "controlType": "TablePanel",
         "width": "XS",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "html": "<table>\n  <tbody>\n    <tr><td id='R1C1'></td><td id='R1C2'></td><td id='R1C3'></td><td id='R1C4'></td><td id='R1C5'></td></tr>\n    <tr><td id='R2C1'></td><td id='R2C2'></td><td id='R2C3'></td><td id='R2C4'></td><td id='R2C5'></td></tr>\n    <tr><td id='R3C1'></td><td id='R3C2'></td><td id='R3C3'></td><td id='R3C4'></td><td id='R3C5'></td></tr>\n    <tr><td id='R4C1'></td><td id='R4C2'></td><td id='R4C3'></td><td id='R4C4'></td><td id='R4C5'></td></tr>\n  </tbody>\n</table>\n"
        }
       ],
       "controlType": "TabPanel",
       "width": "XS",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "title": "施設入退所",
       "onActive": ""
      }
     ],
     "controlType": "TabContainer",
     "width": "980",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "onChange": "",
     "selectedItem": null,
     "tabpanelPosition": [
      "tplGendoGaku",
      "tplShinsakaiIken",
      "tplKyufuSeigen",
      "tplShienJigyosha",
      "tplShisetsuNyutaisho"
     ],
     "isDraggable": false,
     "selectedItemFieldName": "tplGendoGaku"
    }
   ],
   "controlType": "Panel",
   "width": "1000",
   "visible": true,
   "displayNone": false,
   "disabled": false,
   "accessKey": "",
   "nextFocusFieldName": "",
   "wrap": false,
   "dependencies": [],
   "float": 0,
   "toolTip": "",
   "authorityMode": 0,
   "marginLeft": "XS",
   "marginRight": "XS",
   "onLoad": "",
   "title": "",
   "marginTop": "Default",
   "marginBottom": "Default",
   "isOpen": true,
   "canOpenAndClose": true,
   "postParameterPanelNames": [
    {
     "postParameterPanelNames": "HihokenshaShikakuHakko"
    }
   ],
   "requestSettings": [],
   "hiddenInput": [],
   "onOpen": "",
   "onClose": "",
   "session": {},
   "eraseBorderTop": true,
   "eraseBorderBottom": true,
   "eraseBorderRight": true,
   "eraseBorderLeft": true,
   "backgroundColor": 0,
   "widthAuto": false,
   "isGroupBox": false
  }
 ],
 "controlType": "CommonChildDiv",
 "width": "XS",
 "visible": true,
 "displayNone": false,
 "disabled": false,
 "accessKey": "",
 "nextFocusFieldName": "",
 "wrap": false,
 "dependencies": [],
 "float": 0,
 "toolTip": "",
 "authorityMode": 0,
 "marginLeft": 0,
 "marginRight": 0,
 "relation": [],
 "businessId": "DBZ",
 "controlName": "HihokenshaShikakuHakko",
 "marginTop": 0,
 "marginBottom": 0,
 "originalProperty": [
  {
   "publicChildFieldName": "txtYukoKigen",
   "publicChildProperty": "displayNone",
   "newPropertyName": "txtYukoKigen_displayNone"
  }
 ],
 "dataPassingForDialog": [],
 "dialogOkEventNameForDialog": "",
 "dialogCancelEventNameForDialog": ""
}        
    }
}

