var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var DBZ;
(function (DBZ) {
    var HihokenshaFinder_Design = (function (_super) {
        __extends(HihokenshaFinder_Design, _super);
        function HihokenshaFinder_Design($parentElement, isDesignMode, fieldName) {
            _super.call(this, $parentElement, isDesignMode, HihokenshaFinder_Design.myLayout, fieldName);
        }
        Object.defineProperty(HihokenshaFinder_Design.prototype, "onClick_BtnToSearch", {
            get: function () {
                return Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"] + "_" + this.layout.items[0].items[3].items[1]["fieldName"])["onClick"];
            },
            set: function (value) {
                if ($("#" + this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"] + "_" + this.layout.items[0].items[3].items[1]["fieldName"]).length > 0 && Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"] + "_" + this.layout.items[0].items[3].items[1]["fieldName"]) != undefined) {
                    Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"] + "_" + this.layout.items[0].items[3].items[1]["fieldName"])["onClick"] = value;
                } else {
                    this.layout.items[0].items[3].items[1]["onClick"] = value;
                    this.raisePropertyChanged(this.layout);
                }
            },
            enumerable: true,
            configurable: true
        });


        HihokenshaFinder_Design.prototype.registProperty = function () {
            _super.prototype.registProperty.call(this);
            Uz.JSControlUtil.registProperty("onClick_BtnToSearch");
        };

        HihokenshaFinder_Design.prototype.getEditablePropertyInfo = function () {
            var editablePropertyInfo = _super.prototype.getEditablePropertyInfo.call(this);
            editablePropertyInfo["onClick_BtnToSearch"] = Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[3]["fieldName"] + "_" + this.layout.items[0].items[3].items[1]["fieldName"]).getEditablePropertyInfo()["onClick"];

            return editablePropertyInfo;
        };
        HihokenshaFinder_Design.myLayout = {
            "fieldName": "defaultLayout",
            "items": [
                {
                    "fieldName": "HihokenshaFinder",
                    "items": [
                        {
                            "fieldName": "SearchCriteriaOfHokensha",
                            "items": [
                                {
                                    "fieldName": "ddlHokensha",
                                    "items": [],
                                    "controlType": "DropDownList",
                                    "width": "M",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "ddlHokensha_core",
                                    "onChange": "",
                                    "selectedItem": "key0",
                                    "dataSource": [
                                        {
                                            "key": "key0",
                                            "value": "指定なし"
                                        }
                                    ],
                                    "required": false,
                                    "labelLText": "保険者",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "text": ""
                                }
                            ],
                            "controlType": "Panel",
                            "width": "G2",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "SearchCriteriaOfHokensha",
                            "onLoad": "",
                            "title": "",
                            "marginTop": "XS",
                            "marginBottom": "XS",
                            "isOpen": true,
                            "canOpenAndClose": true,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "SearchCriteriaOfHokensha"
                                }
                            ],
                            "requestSettings": [],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorderTop": true,
                            "eraseBorderBottom": true,
                            "eraseBorderRight": true,
                            "eraseBorderLeft": true,
                            "backgroundColor": 0,
                            "widthAuto": true,
                            "panelDisplay": 0,
                            "isGroupBox": false,
                            "readOnly": false
                        },
                        {
                            "fieldName": "SearchCriteriaOfHihokensha",
                            "items": [
                                {
                                    "fieldName": "txtHihokenshaNo",
                                    "items": [],
                                    "controlType": "TextBoxCode",
                                    "width": "75",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtHihokenshaNo_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "被保番号",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": "10",
                                    "minLength": "10",
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 2,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": "",
                                    "formatLength": "10"
                                },
                                {
                                    "fieldName": "chkHihokenshaKubun",
                                    "items": [],
                                    "controlType": "CheckBoxList",
                                    "width": "L",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "chkHihokenshaKubun_core",
                                    "onChange": "",
                                    "selectedItem": null,
                                    "dataSource": [
                                        {
                                            "key": "no1",
                                            "value": "第1号被保険者"
                                        },
                                        {
                                            "key": "no2",
                                            "value": "第2号被保険者"
                                        },
                                        {
                                            "key": "other",
                                            "value": "その他"
                                        }
                                    ],
                                    "required": false,
                                    "labelLText": "被保険者区分",
                                    "labelLWidth": "S",
                                    "labelLAlign": 2,
                                    "onClick": "",
                                    "selectedItems": [],
                                    "newLineItemNumber": 3,
                                    "minCheckedItem": 0,
                                    "maxCheckedItem": "3",
                                    "spaceSize": "M",
                                    "isAllSelectable": false,
                                    "icon": []
                                }
                            ],
                            "controlType": "Panel",
                            "width": "1075",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "SearchCriteriaOfHihokensha",
                            "onLoad": "",
                            "title": "被保険者",
                            "marginTop": "XS",
                            "marginBottom": "XS",
                            "isOpen": true,
                            "canOpenAndClose": false,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "SearchCriteriaOfHihokensha"
                                }
                            ],
                            "requestSettings": [
                                {
                                    "eventName": "onLoad",
                                    "requestUrl": ""
                                }
                            ],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorderTop": false,
                            "eraseBorderBottom": false,
                            "eraseBorderRight": false,
                            "eraseBorderLeft": false,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "panelDisplay": 1,
                            "isGroupBox": false,
                            "readOnly": false
                        },
                        {
                            "fieldName": "SearchCriteriaOfKojin",
                            "items": [
                                {
                                    "fieldName": "txtShikibetsuCode",
                                    "items": [],
                                    "controlType": "TextBoxCode",
                                    "width": "121",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtShikibetsuCode_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "識別コード",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": "15",
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 2,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": "",
                                    "formatLength": ""
                                },
                                {
                                    "fieldName": "txtSetaiCode",
                                    "items": [],
                                    "controlType": "TextBoxCode",
                                    "width": "110",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtSetaiCode_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "世帯コード",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": "15",
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 2,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": "",
                                    "formatLength": 1
                                },
                                {
                                    "fieldName": "txtKojinNo",
                                    "items": [],
                                    "controlType": "TextBoxCode",
                                    "width": "110",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtKojinNo_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "個人番号",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": "12",
                                    "minLength": "12",
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 2,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": "",
                                    "formatLength": "12"
                                },
                                {
                                    "fieldName": "lblJuminShubetsu",
                                    "items": [],
                                    "controlType": "Label",
                                    "width": "120",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "lblJuminShubetsu",
                                    "required": false,
                                    "isPrivateInfo": false,
                                    "text": "住民種別",
                                    "align": 2
                                },
                                {
                                    "fieldName": "ddlJuminShubetsu",
                                    "items": [],
                                    "controlType": "DropDownList",
                                    "width": "110",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "ddlJuminShubetsu_core",
                                    "onChange": "",
                                    "selectedItem": "key0",
                                    "dataSource": [
                                        {
                                            "key": "key0",
                                            "value": "指定なし"
                                        },
                                        {
                                            "key": "key1",
                                            "value": "日本人"
                                        },
                                        {
                                            "key": "key2",
                                            "value": "外国人"
                                        }
                                    ],
                                    "required": false,
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "text": ""
                                },
                                {
                                    "fieldName": "txtShimei",
                                    "items": [],
                                    "controlType": "TextBox",
                                    "width": "L",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtShimei_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "氏名",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": 100000000,
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 0,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": ""
                                },
                                {
                                    "fieldName": "chkGender",
                                    "items": [],
                                    "controlType": "CheckBoxList",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "chkGender_core",
                                    "onChange": "",
                                    "selectedItem": null,
                                    "dataSource": [
                                        {
                                            "key": "man",
                                            "value": "男"
                                        },
                                        {
                                            "key": "woman",
                                            "value": "女"
                                        }
                                    ],
                                    "required": false,
                                    "labelLText": "　　　　　　性別",
                                    "labelLWidth": "150",
                                    "labelLAlign": 1,
                                    "onClick": "",
                                    "selectedItems": [],
                                    "newLineItemNumber": 2,
                                    "minCheckedItem": 0,
                                    "maxCheckedItem": 2,
                                    "spaceSize": "M",
                                    "isAllSelectable": false,
                                    "icon": []
                                },
                                {
                                    "fieldName": "radSearchPatternOfShimei",
                                    "items": [],
                                    "controlType": "RadioButton",
                                    "width": "400",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "0",
                                    "selectControlID": "radSearchPatternOfShimei_core",
                                    "onChange": "",
                                    "selectedItem": null,
                                    "dataSource": [
                                        {
                                            "key": "key0",
                                            "value": "前方一致"
                                        },
                                        {
                                            "key": "key1",
                                            "value": "後方一致"
                                        },
                                        {
                                            "key": "key2",
                                            "value": "完全一致"
                                        },
                                        {
                                            "key": "key3",
                                            "value": "部分一致"
                                        }
                                    ],
                                    "required": false,
                                    "labelLText": "　",
                                    "labelLWidth": "S",
                                    "labelLAlign": 2,
                                    "onClick": "",
                                    "newLineItemNumber": 4,
                                    "spaceSize": "M",
                                    "icon": []
                                },
                                {
                                    "fieldName": "lblSearching",
                                    "items": [],
                                    "controlType": "Label",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "0",
                                    "marginRight": "XS",
                                    "selectControlID": "lblSearching",
                                    "required": false,
                                    "isPrivateInfo": false,
                                    "text": "で検索する。",
                                    "align": 2
                                },
                                {
                                    "fieldName": "txtBirthDay",
                                    "items": [],
                                    "controlType": "TextBoxFlexibleDate",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtBirthDay_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "生年月日",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "placeHolder": "",
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "value": "",
                                    "permitCharactor": "./_-",
                                    "ymdKubun": 2,
                                    "displayFormat": 0
                                },
                                {
                                    "fieldName": "txtYubinNo",
                                    "items": [],
                                    "controlType": "TextBoxYubinNo",
                                    "width": "68",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtYubinNo_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "〒",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": 100000000,
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 2,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": ""
                                },
                                {
                                    "fieldName": "txtJusho",
                                    "items": [],
                                    "controlType": "TextBox",
                                    "width": "XL",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtJusho_core",
                                    "readOnly": false,
                                    "onChange": "",
                                    "required": false,
                                    "labelLText": "住所",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "maxLength": 100000000,
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "placeHolder": "",
                                    "textKind": 0,
                                    "isPrivateInfo": false,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onKeyPress": "",
                                    "text": "",
                                    "suggest": [],
                                    "value": "",
                                    "permitCharactor": ""
                                }
                            ],
                            "controlType": "Panel",
                            "width": "1075",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "SearchCriteriaOfKojin",
                            "onLoad": "",
                            "title": "個人",
                            "marginTop": "XS",
                            "marginBottom": "XS",
                            "isOpen": true,
                            "canOpenAndClose": false,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "SearchCriteriaOfKojin"
                                }
                            ],
                            "requestSettings": [
                                {
                                    "eventName": "onLoad",
                                    "requestUrl": ""
                                }
                            ],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorderTop": false,
                            "eraseBorderBottom": false,
                            "eraseBorderRight": false,
                            "eraseBorderLeft": false,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "panelDisplay": 1,
                            "isGroupBox": false,
                            "readOnly": false
                        },
                        {
                            "fieldName": "ButtonsForHihokenshaFinder",
                            "items": [
                                {
                                    "fieldName": "btnToClear",
                                    "items": [],
                                    "controlType": "Button",
                                    "width": "M",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "btnToClear",
                                    "text": "条件をクリアする",
                                    "onClick": "",
                                    "icon": 0,
                                    "appearance": 0,
                                    "imageFileUrl": "",
                                    "imageWidth": "",
                                    "imageHeight": ""
                                },
                                {
                                    "fieldName": "btnToSearch",
                                    "items": [],
                                    "controlType": "Button",
                                    "width": "M",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 2,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "btnToSearch",
                                    "text": "検索する",
                                    "onClick": "",
                                    "icon": 0,
                                    "appearance": 0,
                                    "imageFileUrl": "",
                                    "imageWidth": "",
                                    "imageHeight": ""
                                }
                            ],
                            "controlType": "Panel",
                            "width": "1075",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "ButtonsForHihokenshaFinder",
                            "onLoad": "",
                            "title": "",
                            "marginTop": "Default",
                            "marginBottom": "Default",
                            "isOpen": true,
                            "canOpenAndClose": true,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "ButtonsForHihokenshaFinder"
                                }
                            ],
                            "requestSettings": [],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorderTop": true,
                            "eraseBorderBottom": true,
                            "eraseBorderRight": true,
                            "eraseBorderLeft": true,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "panelDisplay": 0,
                            "isGroupBox": false,
                            "readOnly": false
                        }
                    ],
                    "controlType": "Panel",
                    "width": "1090",
                    "visible": true,
                    "displayNone": false,
                    "disabled": false,
                    "accessKey": "",
                    "nextFocusFieldName": "",
                    "wrap": true,
                    "dependencies": [],
                    "float": 0,
                    "toolTip": "",
                    "authorityMode": 0,
                    "marginLeft": "XS",
                    "marginRight": "XS",
                    "selectControlID": "HihokenshaFinder",
                    "onLoad": "",
                    "title": "検索条件",
                    "marginTop": "XS",
                    "marginBottom": "XS",
                    "isOpen": true,
                    "canOpenAndClose": true,
                    "postParameterPanelNames": [
                        {
                            "postParameterPanelNames": "HihokenshaFinder"
                        }
                    ],
                    "requestSettings": [
                        {
                            "eventName": "onLoad",
                            "requestUrl": "dbz/db/dbz/HihokenshaFinder/onLoad"
                        },
                        {
                            "eventName": "onClick_btnToClear",
                            "requestUrl": "dbz/db/dbz/HihokenshaFinder/onClick_btnToClear"
                        }
                    ],
                    "hiddenInput": [],
                    "onOpen": "",
                    "onClose": "",
                    "session": {},
                    "eraseBorderTop": false,
                    "eraseBorderBottom": false,
                    "eraseBorderRight": false,
                    "eraseBorderLeft": false,
                    "backgroundColor": 0,
                    "widthAuto": false,
                    "panelDisplay": 0,
                    "isGroupBox": false,
                    "readOnly": false
                }
            ],
            "controlType": "CommonChildDiv",
            "width": "XS",
            "visible": true,
            "displayNone": false,
            "disabled": false,
            "accessKey": "",
            "nextFocusFieldName": "",
            "wrap": false,
            "dependencies": [],
            "float": 0,
            "toolTip": "",
            "authorityMode": 0,
            "marginLeft": 0,
            "marginRight": 0,
            "selectControlID": "defaultLayout",
            "relation": [],
            "businessId": "DBZ",
            "controlName": "HihokenshaFinder",
            "marginTop": 0,
            "marginBottom": 0,
            "originalProperty": [
                {
                    "publicChildFieldName": "btnToSearch",
                    "publicChildProperty": "onClick",
                    "newPropertyName": "onClick_BtnToSearch"
                }
            ],
            "dataPassingForDialog": [],
            "dialogOkEventNameForDialog": "",
            "dialogCancelEventNameForDialog": ""
        };
        return HihokenshaFinder_Design;
    })(Uz.CommonChildDiv);
    DBZ.HihokenshaFinder_Design = HihokenshaFinder_Design;
})(DBZ || (DBZ = {}));
