/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbe.entity.db.relate.hokokushiryosakusei;

import jp.co.ndensan.reams.uz.uza.lang.RString;
import lombok.Getter;
import lombok.Setter;

/**
 * 帳票設計_DBE701001_介護認定審査会判定状況表クラスです。
 *
 * @reamsid_L DBE-1450-030 wanghui
 */
@Getter
@Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class ShinsaHanteiJokyoEntity {

    private RString タイトル;
    private RString 合議体名称;
    private RString 開催開始年月日;
    private RString 開催終了年月日;
    private RString 開催回数;
    private RString 保険者番号;
    private RString 保険者名;
    private RString 発行日時;
    private RString 二次判定非該当タイトル;
    private RString 二次判定要支援1タイトル;
    private RString 二次判定要支援2タイトル;
    private RString 二次判定要介護1タイトル;
    private RString 二次判定要介護2タイトル;
    private RString 二次判定要介護3タイトル;
    private RString 二次判定要介護4タイトル;
    private RString 二次判定要介護5タイトル;
    private RString 一次判定計タイトル;
    private RString 一次判定非該当タイトル;
    private RString 一次判定非該当二次判定非該当;
    private RString 一次判定非該当二次判定要支援1;
    private RString 一次判定非該当二次判定要支援2;
    private RString 一次判定非該当二次判定要介護1;
    private RString 一次判定非該当二次判定要介護2;
    private RString 一次判定非該当二次判定要介護3;
    private RString 一次判定非該当二次判定要介護4;
    private RString 一次判定非該当二次判定要介護5;
    private RString 一次判定非該当計;
    private RString 一次判定非該当再調査二次保留分;
    private RString 一次判定非該当判定変更者数;
    private RString 一次判定非該当軽度変更者数;
    private RString 一次判定非該当重度変更者数;
    private RString 一次判定非該当判定変更割合;
    private RString 一次判定要支援1タイトル;
    private RString 一次判定要支援1二次判定非該当;
    private RString 一次判定要支援1二次判定要支援1;
    private RString 一次判定要支援1二次判定要支援2;
    private RString 一次判定要支援1二次判定要介護1;
    private RString 一次判定要支援1二次判定要介護2;
    private RString 一次判定要支援1二次判定要介護3;
    private RString 一次判定要支援1二次判定要介護4;
    private RString 一次判定要支援1二次判定要介護5;
    private RString 一次判定要支援1計;
    private RString 一次判定要支援1再調査二次保留分;
    private RString 一次判定要支援1判定変更者数;
    private RString 一次判定要支援1軽度変更者数;
    private RString 一次判定要支援1重度変更者数;
    private RString 一次判定要支援1判定変更割合;
    private RString 一次判定要支援2タイトル;
    private RString 一次判定要支援2二次判定非該当;
    private RString 一次判定要支援2二次判定要支援1;
    private RString 一次判定要支援2二次判定要支援2;
    private RString 一次判定要支援2二次判定要介護1;
    private RString 一次判定要支援2二次判定要介護2;
    private RString 一次判定要支援2二次判定要介護3;
    private RString 一次判定要支援2二次判定要介護4;
    private RString 一次判定要支援2二次判定要介護5;
    private RString 一次判定要支援2計;
    private RString 一次判定要支援2再調査二次保留分;
    private RString 一次判定要支援2判定変更者数;
    private RString 一次判定要支援2軽度変更者数;
    private RString 一次判定要支援2重度変更者数;
    private RString 一次判定要支援2判定変更割合;
    private RString 一次判定要介護1タイトル;
    private RString 一次判定要介護1二次判定非該当;
    private RString 一次判定要介護1二次判定要支援1;
    private RString 一次判定要介護1二次判定要支援2;
    private RString 一次判定要介護1二次判定要介護1;
    private RString 一次判定要介護1二次判定要介護2;
    private RString 一次判定要介護1二次判定要介護3;
    private RString 一次判定要介護1二次判定要介護4;
    private RString 一次判定要介護1二次判定要介護5;
    private RString 一次判定要介護1計;
    private RString 一次判定要介護1再調査二次保留分;
    private RString 一次判定要介護1判定変更者数;
    private RString 一次判定要介護1軽度変更者数;
    private RString 一次判定要介護1重度変更者数;
    private RString 一次判定要介護1判定変更割合;
    private RString 一次判定要介護2タイトル;
    private RString 一次判定要介護2二次判定非該当;
    private RString 一次判定要介護2二次判定要支援1;
    private RString 一次判定要介護2二次判定要支援2;
    private RString 一次判定要介護2二次判定要介護1;
    private RString 一次判定要介護2二次判定要介護2;
    private RString 一次判定要介護2二次判定要介護3;
    private RString 一次判定要介護2二次判定要介護4;
    private RString 一次判定要介護2二次判定要介護5;
    private RString 一次判定要介護2計;
    private RString 一次判定要介護2再調査二次保留分;
    private RString 一次判定要介護2判定変更者数;
    private RString 一次判定要介護2軽度変更者数;
    private RString 一次判定要介護2重度変更者数;
    private RString 一次判定要介護2判定変更割合;
    private RString 一次判定要介護3タイトル;
    private RString 一次判定要介護3二次判定非該当;
    private RString 一次判定要介護3二次判定要支援1;
    private RString 一次判定要介護3二次判定要支援2;
    private RString 一次判定要介護3二次判定要介護1;
    private RString 一次判定要介護3二次判定要介護2;
    private RString 一次判定要介護3二次判定要介護3;
    private RString 一次判定要介護3二次判定要介護4;
    private RString 一次判定要介護3二次判定要介護5;
    private RString 一次判定要介護3計;
    private RString 一次判定要介護3再調査二次保留分;
    private RString 一次判定要介護3判定変更者数;
    private RString 一次判定要介護3軽度変更者数;
    private RString 一次判定要介護3重度変更者数;
    private RString 一次判定要介護3判定変更割合;
    private RString 一次判定要介護4タイトル;
    private RString 一次判定要介護4二次判定非該当;
    private RString 一次判定要介護4二次判定要支援1;
    private RString 一次判定要介護4二次判定要支援2;
    private RString 一次判定要介護4二次判定要介護1;
    private RString 一次判定要介護4二次判定要介護2;
    private RString 一次判定要介護4二次判定要介護3;
    private RString 一次判定要介護4二次判定要介護4;
    private RString 一次判定要介護4二次判定要介護5;
    private RString 一次判定要介護4計;
    private RString 一次判定要介護4再調査二次保留分;
    private RString 一次判定要介護4判定変更者数;
    private RString 一次判定要介護4軽度変更者数;
    private RString 一次判定要介護4重度変更者数;
    private RString 一次判定要介護4判定変更割合;
    private RString 一次判定要介護5タイトル;
    private RString 一次判定要介護5二次判定非該当;
    private RString 一次判定要介護5二次判定要支援1;
    private RString 一次判定要介護5二次判定要支援2;
    private RString 一次判定要介護5二次判定要介護1;
    private RString 一次判定要介護5二次判定要介護2;
    private RString 一次判定要介護5二次判定要介護3;
    private RString 一次判定要介護5二次判定要介護4;
    private RString 一次判定要介護5二次判定要介護5;
    private RString 一次判定要介護5計;
    private RString 一次判定要介護5再調査二次保留分;
    private RString 一次判定要介護5判定変更者数;
    private RString 一次判定要介護5軽度変更者数;
    private RString 一次判定要介護5重度変更者数;
    private RString 一次判定要介護5判定変更割合;
    private RString 計タイトル;
    private RString 計二次判定非該当;
    private RString 計二次判定要支援1;
    private RString 計二次判定要支援2;
    private RString 計二次判定要介護1;
    private RString 計二次判定要介護2;
    private RString 計二次判定要介護3;
    private RString 計二次判定要介護4;
    private RString 計二次判定要介護5;
    private RString 計計;
    private RString 計再調査二次保留分;
    private RString 計判定変更者数;
    private RString 計軽度変更者数;
    private RString 計重度変更者数;
    private RString 計判定変更割合;
    private RString 変更者タイトル;
    private RString 変更者二次判定非該当;
    private RString 変更者二次判定要支援1;
    private RString 変更者二次判定要支援2;
    private RString 変更者二次判定要介護1;
    private RString 変更者二次判定要介護2;
    private RString 変更者二次判定要介護3;
    private RString 変更者二次判定要介護4;
    private RString 変更者二次判定要介護5;
    private RString 変更者計;
    private RString 変更者再調査二次保留分;
    private RString 変更者判定変更者数;
    private RString 変更者軽度変更者数;
    private RString 変更者重度変更者数;
    private RString 変更者判定変更割合;
    private RString 割合タイトル;
    private RString 割合二次判定非該当;
    private RString 割合二次判定要支援1;
    private RString 割合二次判定要支援2;
    private RString 割合二次判定要介護1;
    private RString 割合二次判定要介護2;
    private RString 割合二次判定要介護3;
    private RString 割合二次判定要介護4;
    private RString 割合二次判定要介護5;
    private RString 割合計;
    private RString 割合再調査二次保留分;
    private RString 割合判定変更者数;
    private RString 割合軽度変更者数;
    private RString 割合重度変更者数;
    private RString 割合判定変更割合;
    private RString 変更者;
    private RString 軽度;
    private RString 重度;
}
