/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbu.batchcontroller.step.DBU030070;

import java.util.HashMap;
import java.util.Map;
import jp.co.ndensan.reams.db.dbu.business.report.jigyohokokucompyoshiki202.JigyohokokuCompYoshiki202Report;
import jp.co.ndensan.reams.db.dbu.definition.core.jigyohokoku.ShukeiNoyoshiki2;
import jp.co.ndensan.reams.db.dbu.definition.processprm.jigyohokokunenpohokenkyufugenbutsu.JigyoHokokuNenpoHokenkyufuGenbutsuProcessParamter;
import jp.co.ndensan.reams.db.dbu.definition.reportid.ReportIdDBU;
import jp.co.ndensan.reams.db.dbu.entity.db.relate.jigyohokokucompyoshiki202.JigyohokokuCompYoshiki202Data;
import jp.co.ndensan.reams.db.dbu.entity.db.relate.jigyohokokunenpoippangenbutsu.GassanJigyouHoukokuTokeiEntity;
import jp.co.ndensan.reams.db.dbu.entity.report.jigyohokokucompyoshiki202.JigyohokokuCompYoshiki202ReportSource;
import jp.co.ndensan.reams.ur.urz.business.core.association.Association;
import jp.co.ndensan.reams.ur.urz.service.core.association.AssociationFinderFactory;
import jp.co.ndensan.reams.uz.uza.batch.process.BatchDbReader;
import jp.co.ndensan.reams.uz.uza.batch.process.BatchProcessBase;
import jp.co.ndensan.reams.uz.uza.batch.process.BatchReportFactory;
import jp.co.ndensan.reams.uz.uza.batch.process.BatchReportWriter;
import jp.co.ndensan.reams.uz.uza.batch.process.BatchWriter;
import jp.co.ndensan.reams.uz.uza.batch.process.IBatchReader;
import jp.co.ndensan.reams.uz.uza.biz.ReportId;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYear;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleYearMonth;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import jp.co.ndensan.reams.uz.uza.math.Decimal;
import jp.co.ndensan.reams.uz.uza.report.ReportSourceWriter;

/**
 * 介護事業状況報告年報（様式2-4）帳票出力のバッチ処理クラスです。
 *
 * @reamsid_L DBU-5600-050 lishengli
 */
public class JigyoHokokuNenpoReportDBU300116Process extends BatchProcessBase<GassanJigyouHoukokuTokeiEntity> {

    private static final RString MYBATIS_SELECT_ID = new RString(
            "jp.co.ndensan.reams.db.dbu.persistence.db.mapper.relate.jigyohokokunenpohokenkyufugenbutsu."
            + "IJigyoHokokuNenpoHokenkyufuGenbutsuMapper.getJigyouHokokuTokeiReportJyoho");
    private JigyoHokokuNenpoHokenkyufuGenbutsuProcessParamter processParameter;

    private static final ReportId REPORT_DBU300116 = ReportIdDBU.DBU300116.getReportId();
    private static final RString 過去集計分旧市町村区分 = new RString("1");
    private static final RString 固定文字列_旧 = new RString("（旧）");
    private static final RString 年報月報区分CODE = new RString("2");
    private static final RString 現物分 = new RString("1");
    private static final RString 償還審査分 = new RString("2");
    private static final RString 償還決定分 = new RString("3");
    private static final int 数値_100 = 100;
    private static final Decimal 数値_101 = new Decimal(101);
    private static final Decimal 数値_102 = new Decimal(102);
    private static final Decimal 数値_103 = new Decimal(103);
    private static final Decimal 数値_106 = new Decimal(106);
    private static final Decimal 数値_107 = new Decimal(107);
    private static final Decimal 数値_108 = new Decimal(108);
    private static final Decimal 数値_109 = new Decimal(109);
    private static final Decimal 数値_114 = new Decimal(114);
    private static final Decimal 数値_115 = new Decimal(115);
    private static final Decimal 数値_116 = new Decimal(116);
    private static final Decimal 数値_117 = new Decimal(117);
    private static final Decimal 数値_118 = new Decimal(118);
    private static final Decimal 数値_119 = new Decimal(119);
    private static final Decimal 数値_120 = new Decimal(120);
    private static final Decimal 数値_121 = new Decimal(121);
    private static final Decimal 数値_122 = new Decimal(122);
    private static final Decimal 数値_123 = new Decimal(123);
    private static final Decimal 数値_124 = new Decimal(124);
    private static final Decimal 数値_125 = new Decimal(125);
    private static final Decimal 数値_126 = new Decimal(126);
    private static final Decimal 数値_127 = new Decimal(127);
    private static final Decimal 数値_128 = new Decimal(128);
    private static final Decimal 数値_129 = new Decimal(129);
    private static final Decimal 数値_130 = new Decimal(130);
    private static final Decimal 数値_131 = new Decimal(131);
    private static final Decimal 数値_132 = new Decimal(132);
    private static final Decimal 数値_133 = new Decimal(133);
    private static final Decimal 数値_134 = new Decimal(134);
    private static final Decimal 数値_135 = new Decimal(135);
    private static final Decimal 数値_136 = new Decimal(136);
    private static final Decimal 数値_137 = new Decimal(137);
    private static final Decimal 数値_138 = new Decimal(138);
    private static final Decimal 数値_139 = new Decimal(139);
    private static final Decimal 数値_201 = new Decimal(201);
    private static final Decimal 数値_202 = new Decimal(202);
    private static final Decimal 数値_203 = new Decimal(203);
    private static final Decimal 数値_206 = new Decimal(206);
    private static final Decimal 数値_207 = new Decimal(207);
    private static final Decimal 数値_208 = new Decimal(208);
    private static final Decimal 数値_209 = new Decimal(209);
    private static final Decimal 数値_214 = new Decimal(214);
    private static final Decimal 数値_215 = new Decimal(215);
    private static final Decimal 数値_216 = new Decimal(216);
    private static final Decimal 数値_217 = new Decimal(217);
    private static final Decimal 数値_218 = new Decimal(218);
    private static final Decimal 数値_219 = new Decimal(219);
    private static final Decimal 数値_220 = new Decimal(220);
    private static final Decimal 数値_221 = new Decimal(221);
    private static final Decimal 数値_222 = new Decimal(222);
    private static final Decimal 数値_223 = new Decimal(223);
    private static final Decimal 数値_224 = new Decimal(224);
    private static final Decimal 数値_225 = new Decimal(225);
    private static final Decimal 数値_226 = new Decimal(226);
    private static final Decimal 数値_227 = new Decimal(227);
    private static final Decimal 数値_228 = new Decimal(228);
    private static final Decimal 数値_229 = new Decimal(229);
    private static final Decimal 数値_230 = new Decimal(230);
    private static final Decimal 数値_231 = new Decimal(231);
    private static final Decimal 数値_232 = new Decimal(232);
    private static final Decimal 数値_233 = new Decimal(233);
    private static final Decimal 数値_234 = new Decimal(234);
    private static final Decimal 数値_235 = new Decimal(235);
    private static final Decimal 数値_236 = new Decimal(236);
    private static final Decimal 数値_237 = new Decimal(237);
    private static final Decimal 数値_238 = new Decimal(238);
    private static final Decimal 数値_239 = new Decimal(239);
    private static final Decimal 数値_301 = new Decimal(301);
    private static final Decimal 数値_302 = new Decimal(302);
    private static final Decimal 数値_303 = new Decimal(303);
    private static final Decimal 数値_306 = new Decimal(306);
    private static final Decimal 数値_307 = new Decimal(307);
    private static final Decimal 数値_308 = new Decimal(308);
    private static final Decimal 数値_309 = new Decimal(309);
    private static final Decimal 数値_314 = new Decimal(314);
    private static final Decimal 数値_315 = new Decimal(315);
    private static final Decimal 数値_316 = new Decimal(316);
    private static final Decimal 数値_317 = new Decimal(317);
    private static final Decimal 数値_318 = new Decimal(318);
    private static final Decimal 数値_319 = new Decimal(319);
    private static final Decimal 数値_320 = new Decimal(320);
    private static final Decimal 数値_321 = new Decimal(321);
    private static final Decimal 数値_322 = new Decimal(322);
    private static final Decimal 数値_323 = new Decimal(323);
    private static final Decimal 数値_324 = new Decimal(324);
    private static final Decimal 数値_325 = new Decimal(325);
    private static final Decimal 数値_326 = new Decimal(326);
    private static final Decimal 数値_327 = new Decimal(327);
    private static final Decimal 数値_328 = new Decimal(328);
    private static final Decimal 数値_329 = new Decimal(329);
    private static final Decimal 数値_330 = new Decimal(330);
    private static final Decimal 数値_331 = new Decimal(331);
    private static final Decimal 数値_332 = new Decimal(332);
    private static final Decimal 数値_333 = new Decimal(333);
    private static final Decimal 数値_334 = new Decimal(334);
    private static final Decimal 数値_335 = new Decimal(335);
    private static final Decimal 数値_336 = new Decimal(336);
    private static final Decimal 数値_337 = new Decimal(337);
    private static final Decimal 数値_338 = new Decimal(338);
    private static final Decimal 数値_339 = new Decimal(339);
    private static final Decimal 数値_401 = new Decimal(401);
    private static final Decimal 数値_402 = new Decimal(402);
    private static final Decimal 数値_403 = new Decimal(403);
    private static final Decimal 数値_406 = new Decimal(406);
    private static final Decimal 数値_407 = new Decimal(407);
    private static final Decimal 数値_408 = new Decimal(408);
    private static final Decimal 数値_409 = new Decimal(409);
    private static final Decimal 数値_414 = new Decimal(414);
    private static final Decimal 数値_415 = new Decimal(415);
    private static final Decimal 数値_416 = new Decimal(416);
    private static final Decimal 数値_417 = new Decimal(417);
    private static final Decimal 数値_418 = new Decimal(418);
    private static final Decimal 数値_419 = new Decimal(419);
    private static final Decimal 数値_420 = new Decimal(420);
    private static final Decimal 数値_421 = new Decimal(421);
    private static final Decimal 数値_422 = new Decimal(422);
    private static final Decimal 数値_423 = new Decimal(423);
    private static final Decimal 数値_424 = new Decimal(424);
    private static final Decimal 数値_425 = new Decimal(425);
    private static final Decimal 数値_426 = new Decimal(426);
    private static final Decimal 数値_427 = new Decimal(427);
    private static final Decimal 数値_428 = new Decimal(428);
    private static final Decimal 数値_429 = new Decimal(429);
    private static final Decimal 数値_430 = new Decimal(430);
    private static final Decimal 数値_431 = new Decimal(431);
    private static final Decimal 数値_432 = new Decimal(432);
    private static final Decimal 数値_433 = new Decimal(433);
    private static final Decimal 数値_434 = new Decimal(434);
    private static final Decimal 数値_435 = new Decimal(435);
    private static final Decimal 数値_436 = new Decimal(436);
    private static final Decimal 数値_437 = new Decimal(437);
    private static final Decimal 数値_438 = new Decimal(438);
    private static final Decimal 数値_439 = new Decimal(439);
    private static final Decimal 数値_501 = new Decimal(501);
    private static final Decimal 数値_502 = new Decimal(502);
    private static final Decimal 数値_503 = new Decimal(503);
    private static final Decimal 数値_506 = new Decimal(506);
    private static final Decimal 数値_507 = new Decimal(507);
    private static final Decimal 数値_508 = new Decimal(508);
    private static final Decimal 数値_509 = new Decimal(509);
    private static final Decimal 数値_514 = new Decimal(514);
    private static final Decimal 数値_515 = new Decimal(515);
    private static final Decimal 数値_516 = new Decimal(516);
    private static final Decimal 数値_517 = new Decimal(517);
    private static final Decimal 数値_518 = new Decimal(518);
    private static final Decimal 数値_519 = new Decimal(519);
    private static final Decimal 数値_520 = new Decimal(520);
    private static final Decimal 数値_521 = new Decimal(521);
    private static final Decimal 数値_522 = new Decimal(522);
    private static final Decimal 数値_523 = new Decimal(523);
    private static final Decimal 数値_524 = new Decimal(524);
    private static final Decimal 数値_525 = new Decimal(525);
    private static final Decimal 数値_526 = new Decimal(526);
    private static final Decimal 数値_527 = new Decimal(527);
    private static final Decimal 数値_528 = new Decimal(528);
    private static final Decimal 数値_529 = new Decimal(529);
    private static final Decimal 数値_530 = new Decimal(530);
    private static final Decimal 数値_531 = new Decimal(531);
    private static final Decimal 数値_532 = new Decimal(532);
    private static final Decimal 数値_533 = new Decimal(533);
    private static final Decimal 数値_534 = new Decimal(534);
    private static final Decimal 数値_535 = new Decimal(535);
    private static final Decimal 数値_536 = new Decimal(536);
    private static final Decimal 数値_537 = new Decimal(537);
    private static final Decimal 数値_538 = new Decimal(538);
    private static final Decimal 数値_539 = new Decimal(539);
    private static final Decimal 数値_601 = new Decimal(601);
    private static final Decimal 数値_602 = new Decimal(602);
    private static final Decimal 数値_603 = new Decimal(603);
    private static final Decimal 数値_606 = new Decimal(606);
    private static final Decimal 数値_607 = new Decimal(607);
    private static final Decimal 数値_608 = new Decimal(608);
    private static final Decimal 数値_609 = new Decimal(609);
    private static final Decimal 数値_614 = new Decimal(614);
    private static final Decimal 数値_615 = new Decimal(615);
    private static final Decimal 数値_616 = new Decimal(616);
    private static final Decimal 数値_617 = new Decimal(617);
    private static final Decimal 数値_618 = new Decimal(618);
    private static final Decimal 数値_619 = new Decimal(619);
    private static final Decimal 数値_620 = new Decimal(620);
    private static final Decimal 数値_621 = new Decimal(621);
    private static final Decimal 数値_622 = new Decimal(622);
    private static final Decimal 数値_623 = new Decimal(623);
    private static final Decimal 数値_624 = new Decimal(624);
    private static final Decimal 数値_625 = new Decimal(625);
    private static final Decimal 数値_626 = new Decimal(626);
    private static final Decimal 数値_627 = new Decimal(627);
    private static final Decimal 数値_628 = new Decimal(628);
    private static final Decimal 数値_629 = new Decimal(629);
    private static final Decimal 数値_630 = new Decimal(630);
    private static final Decimal 数値_631 = new Decimal(631);
    private static final Decimal 数値_632 = new Decimal(632);
    private static final Decimal 数値_633 = new Decimal(633);
    private static final Decimal 数値_634 = new Decimal(634);
    private static final Decimal 数値_635 = new Decimal(635);
    private static final Decimal 数値_636 = new Decimal(636);
    private static final Decimal 数値_637 = new Decimal(637);
    private static final Decimal 数値_638 = new Decimal(638);
    private static final Decimal 数値_639 = new Decimal(639);
    private static final Decimal 数値_701 = new Decimal(701);
    private static final Decimal 数値_702 = new Decimal(702);
    private static final Decimal 数値_703 = new Decimal(703);
    private static final Decimal 数値_706 = new Decimal(706);
    private static final Decimal 数値_707 = new Decimal(707);
    private static final Decimal 数値_708 = new Decimal(708);
    private static final Decimal 数値_709 = new Decimal(709);
    private static final Decimal 数値_714 = new Decimal(714);
    private static final Decimal 数値_715 = new Decimal(715);
    private static final Decimal 数値_716 = new Decimal(716);
    private static final Decimal 数値_717 = new Decimal(717);
    private static final Decimal 数値_718 = new Decimal(718);
    private static final Decimal 数値_719 = new Decimal(719);
    private static final Decimal 数値_720 = new Decimal(720);
    private static final Decimal 数値_721 = new Decimal(721);
    private static final Decimal 数値_722 = new Decimal(722);
    private static final Decimal 数値_723 = new Decimal(723);
    private static final Decimal 数値_724 = new Decimal(724);
    private static final Decimal 数値_725 = new Decimal(725);
    private static final Decimal 数値_726 = new Decimal(726);
    private static final Decimal 数値_727 = new Decimal(727);
    private static final Decimal 数値_728 = new Decimal(728);
    private static final Decimal 数値_729 = new Decimal(729);
    private static final Decimal 数値_730 = new Decimal(730);
    private static final Decimal 数値_731 = new Decimal(731);
    private static final Decimal 数値_732 = new Decimal(732);
    private static final Decimal 数値_733 = new Decimal(733);
    private static final Decimal 数値_734 = new Decimal(734);
    private static final Decimal 数値_735 = new Decimal(735);
    private static final Decimal 数値_736 = new Decimal(736);
    private static final Decimal 数値_737 = new Decimal(737);
    private static final Decimal 数値_738 = new Decimal(738);
    private static final Decimal 数値_739 = new Decimal(739);
    private static final Decimal 数値_801 = new Decimal(801);
    private static final Decimal 数値_802 = new Decimal(802);
    private static final Decimal 数値_803 = new Decimal(803);
    private static final Decimal 数値_806 = new Decimal(806);
    private static final Decimal 数値_807 = new Decimal(807);
    private static final Decimal 数値_808 = new Decimal(808);
    private static final Decimal 数値_809 = new Decimal(809);
    private static final Decimal 数値_814 = new Decimal(814);
    private static final Decimal 数値_815 = new Decimal(815);
    private static final Decimal 数値_816 = new Decimal(816);
    private static final Decimal 数値_817 = new Decimal(817);
    private static final Decimal 数値_818 = new Decimal(818);
    private static final Decimal 数値_819 = new Decimal(819);
    private static final Decimal 数値_820 = new Decimal(820);
    private static final Decimal 数値_821 = new Decimal(821);
    private static final Decimal 数値_822 = new Decimal(822);
    private static final Decimal 数値_823 = new Decimal(823);
    private static final Decimal 数値_824 = new Decimal(824);
    private static final Decimal 数値_825 = new Decimal(825);
    private static final Decimal 数値_826 = new Decimal(826);
    private static final Decimal 数値_827 = new Decimal(827);
    private static final Decimal 数値_828 = new Decimal(828);
    private static final Decimal 数値_829 = new Decimal(829);
    private static final Decimal 数値_830 = new Decimal(830);
    private static final Decimal 数値_831 = new Decimal(831);
    private static final Decimal 数値_832 = new Decimal(832);
    private static final Decimal 数値_833 = new Decimal(833);
    private static final Decimal 数値_834 = new Decimal(834);
    private static final Decimal 数値_835 = new Decimal(835);
    private static final Decimal 数値_836 = new Decimal(836);
    private static final Decimal 数値_837 = new Decimal(837);
    private static final Decimal 数値_838 = new Decimal(838);
    private static final Decimal 数値_839 = new Decimal(839);
    private static final Decimal 数値_901 = new Decimal(901);
    private static final Decimal 数値_902 = new Decimal(902);
    private static final Decimal 数値_903 = new Decimal(903);
    private static final Decimal 数値_906 = new Decimal(906);
    private static final Decimal 数値_907 = new Decimal(907);
    private static final Decimal 数値_908 = new Decimal(908);
    private static final Decimal 数値_909 = new Decimal(909);
    private static final Decimal 数値_914 = new Decimal(914);
    private static final Decimal 数値_915 = new Decimal(915);
    private static final Decimal 数値_916 = new Decimal(916);
    private static final Decimal 数値_917 = new Decimal(917);
    private static final Decimal 数値_918 = new Decimal(918);
    private static final Decimal 数値_919 = new Decimal(919);
    private static final Decimal 数値_920 = new Decimal(920);
    private static final Decimal 数値_921 = new Decimal(921);
    private static final Decimal 数値_922 = new Decimal(922);
    private static final Decimal 数値_923 = new Decimal(923);
    private static final Decimal 数値_924 = new Decimal(924);
    private static final Decimal 数値_925 = new Decimal(925);
    private static final Decimal 数値_926 = new Decimal(926);
    private static final Decimal 数値_927 = new Decimal(927);
    private static final Decimal 数値_928 = new Decimal(928);
    private static final Decimal 数値_929 = new Decimal(929);
    private static final Decimal 数値_930 = new Decimal(930);
    private static final Decimal 数値_931 = new Decimal(931);
    private static final Decimal 数値_932 = new Decimal(932);
    private static final Decimal 数値_933 = new Decimal(933);
    private static final Decimal 数値_934 = new Decimal(934);
    private static final Decimal 数値_935 = new Decimal(935);
    private static final Decimal 数値_936 = new Decimal(936);
    private static final Decimal 数値_937 = new Decimal(937);
    private static final Decimal 数値_938 = new Decimal(938);
    private static final Decimal 数値_939 = new Decimal(939);
    private static final Decimal 数値_1001 = new Decimal(1001);
    private static final Decimal 数値_1002 = new Decimal(1002);
    private static final Decimal 数値_1003 = new Decimal(1003);
    private static final Decimal 数値_1006 = new Decimal(1006);
    private static final Decimal 数値_1007 = new Decimal(1007);
    private static final Decimal 数値_1008 = new Decimal(1008);
    private static final Decimal 数値_1009 = new Decimal(1009);
    private static final Decimal 数値_1014 = new Decimal(1014);
    private static final Decimal 数値_1015 = new Decimal(1015);
    private static final Decimal 数値_1016 = new Decimal(1016);
    private static final Decimal 数値_1017 = new Decimal(1017);
    private static final Decimal 数値_1018 = new Decimal(1018);
    private static final Decimal 数値_1019 = new Decimal(1019);
    private static final Decimal 数値_1020 = new Decimal(1020);
    private static final Decimal 数値_1021 = new Decimal(1021);
    private static final Decimal 数値_1022 = new Decimal(1022);
    private static final Decimal 数値_1023 = new Decimal(1023);
    private static final Decimal 数値_1024 = new Decimal(1024);
    private static final Decimal 数値_1025 = new Decimal(1025);
    private static final Decimal 数値_1026 = new Decimal(1026);
    private static final Decimal 数値_1027 = new Decimal(1027);
    private static final Decimal 数値_1028 = new Decimal(1028);
    private static final Decimal 数値_1029 = new Decimal(1029);
    private static final Decimal 数値_1030 = new Decimal(1030);
    private static final Decimal 数値_1031 = new Decimal(1031);
    private static final Decimal 数値_1032 = new Decimal(1032);
    private static final Decimal 数値_1033 = new Decimal(1033);
    private static final Decimal 数値_1034 = new Decimal(1034);
    private static final Decimal 数値_1035 = new Decimal(1035);
    private static final Decimal 数値_1036 = new Decimal(1036);
    private static final Decimal 数値_1037 = new Decimal(1037);
    private static final Decimal 数値_1038 = new Decimal(1038);
    private static final Decimal 数値_1039 = new Decimal(1039);
    private static final Decimal 数値_1101 = new Decimal(1101);
    private static final Decimal 数値_1102 = new Decimal(1102);
    private static final Decimal 数値_1103 = new Decimal(1103);
    private static final Decimal 数値_1106 = new Decimal(1106);
    private static final Decimal 数値_1107 = new Decimal(1107);
    private static final Decimal 数値_1108 = new Decimal(1108);
    private static final Decimal 数値_1109 = new Decimal(1109);
    private static final Decimal 数値_1114 = new Decimal(1114);
    private static final Decimal 数値_1115 = new Decimal(1115);
    private static final Decimal 数値_1116 = new Decimal(1116);
    private static final Decimal 数値_1117 = new Decimal(1117);
    private static final Decimal 数値_1118 = new Decimal(1118);
    private static final Decimal 数値_1119 = new Decimal(1119);
    private static final Decimal 数値_1120 = new Decimal(1120);
    private static final Decimal 数値_1121 = new Decimal(1121);
    private static final Decimal 数値_1122 = new Decimal(1122);
    private static final Decimal 数値_1123 = new Decimal(1123);
    private static final Decimal 数値_1124 = new Decimal(1124);
    private static final Decimal 数値_1125 = new Decimal(1125);
    private static final Decimal 数値_1126 = new Decimal(1126);
    private static final Decimal 数値_1127 = new Decimal(1127);
    private static final Decimal 数値_1128 = new Decimal(1128);
    private static final Decimal 数値_1129 = new Decimal(1129);
    private static final Decimal 数値_1130 = new Decimal(1130);
    private static final Decimal 数値_1131 = new Decimal(1131);
    private static final Decimal 数値_1132 = new Decimal(1132);
    private static final Decimal 数値_1133 = new Decimal(1133);
    private static final Decimal 数値_1134 = new Decimal(1134);
    private static final Decimal 数値_1135 = new Decimal(1135);
    private static final Decimal 数値_1136 = new Decimal(1136);
    private static final Decimal 数値_1137 = new Decimal(1137);
    private static final Decimal 数値_1138 = new Decimal(1138);
    private static final Decimal 数値_1139 = new Decimal(1139);
    private static final Decimal 数値_1201 = new Decimal(1201);
    private static final Decimal 数値_1202 = new Decimal(1202);
    private static final Decimal 数値_1203 = new Decimal(1203);
    private static final Decimal 数値_1206 = new Decimal(1206);
    private static final Decimal 数値_1207 = new Decimal(1207);
    private static final Decimal 数値_1208 = new Decimal(1208);
    private static final Decimal 数値_1209 = new Decimal(1209);
    private static final Decimal 数値_1214 = new Decimal(1214);
    private static final Decimal 数値_1215 = new Decimal(1215);
    private static final Decimal 数値_1216 = new Decimal(1216);
    private static final Decimal 数値_1217 = new Decimal(1217);
    private static final Decimal 数値_1218 = new Decimal(1218);
    private static final Decimal 数値_1219 = new Decimal(1219);
    private static final Decimal 数値_1220 = new Decimal(1220);
    private static final Decimal 数値_1221 = new Decimal(1221);
    private static final Decimal 数値_1222 = new Decimal(1222);
    private static final Decimal 数値_1223 = new Decimal(1223);
    private static final Decimal 数値_1224 = new Decimal(1224);
    private static final Decimal 数値_1225 = new Decimal(1225);
    private static final Decimal 数値_1226 = new Decimal(1226);
    private static final Decimal 数値_1227 = new Decimal(1227);
    private static final Decimal 数値_1228 = new Decimal(1228);
    private static final Decimal 数値_1229 = new Decimal(1229);
    private static final Decimal 数値_1230 = new Decimal(1230);
    private static final Decimal 数値_1231 = new Decimal(1231);
    private static final Decimal 数値_1232 = new Decimal(1232);
    private static final Decimal 数値_1233 = new Decimal(1233);
    private static final Decimal 数値_1234 = new Decimal(1234);
    private static final Decimal 数値_1235 = new Decimal(1235);
    private static final Decimal 数値_1236 = new Decimal(1236);
    private static final Decimal 数値_1237 = new Decimal(1237);
    private static final Decimal 数値_1238 = new Decimal(1238);
    private static final Decimal 数値_1239 = new Decimal(1239);

    private RString 保険者番号;
    private RString 保険者名;
    private Map<Decimal, Decimal> syukeiNo0402;

    @BatchWriter
    private BatchReportWriter<JigyohokokuCompYoshiki202ReportSource> batchWrite;
    private ReportSourceWriter<JigyohokokuCompYoshiki202ReportSource> reportSourceWriter;

    @Override
    protected void beforeExecute() {
        super.beforeExecute();
        syukeiNo0402 = new HashMap<>();
        Association 地方公共団体 = AssociationFinderFactory.createInstance().getAssociation();
        保険者番号 = 地方公共団体.get地方公共団体コード().value();
        if (過去集計分旧市町村区分.equals(processParameter.get過去集計分旧市町村区分())) {
            保険者名 = 固定文字列_旧.concat(地方公共団体.get市町村名());
        } else {
            保険者名 = 地方公共団体.get市町村名();
        }
    }

    @Override
    protected IBatchReader createReader() {
        return new BatchDbReader(MYBATIS_SELECT_ID, processParameter.toSelectReportDataMybitisParamter());
    }

    @Override
    protected void createWriter() {
        batchWrite = BatchReportFactory.createBatchReportWriter(REPORT_DBU300116.value()).create();
        reportSourceWriter = new ReportSourceWriter(batchWrite);
    }

    @Override
    protected void process(GassanJigyouHoukokuTokeiEntity entity) {
        if (ShukeiNoyoshiki2._1_介護給付_予防給付4第２号被保険者分_再掲_特例分_単位数.getコード().equals(entity.getSyukeiNo().value())) {
            syukeiNo0402.put(entity.getYokoNo().multiply(数値_100).add(entity.getTateNo()), entity.getSukeiKekkaAtai());
        }
    }

    @Override
    protected void afterExecute() {
        JigyohokokuCompYoshiki202Data reportData = new JigyohokokuCompYoshiki202Data();
        reportData.set様式(new RString("様式２の４"));
        reportData.set処理日時(processParameter.get処理日時());
        reportData.set保険者名(保険者名);
        reportData.set保険者番号(保険者番号);
        reportData.set年報月報区分(年報月報区分CODE);
        reportData.set集計年度(new FlexibleYear(processParameter.get集計年度()));
        reportData.set集計期間FROM(new FlexibleYearMonth(processParameter.get集計開始年月()));
        reportData.set集計期間TO(new FlexibleYearMonth(processParameter.get集計終了年月()));
        reportData.setタイトル1(getタイトル1(processParameter.get給付集計区分()));
        reportData.setタイトル2(new RString("⑤第２号被保険者分（再掲：介護給付・予防給付の特例分）"));
        reportData.set給付集計区分(processParameter.get給付集計区分());
        if (syukeiNo0402 != null && !syukeiNo0402.isEmpty()) {
            JigyohokokuCompYoshiki202Report report = new JigyohokokuCompYoshiki202Report(set集計結果(reportData, syukeiNo0402));
            report.writeBy(reportSourceWriter);
        }
    }

    private RString getValue(Map<Decimal, Decimal> map, Decimal key) {
        if (map != null && map.get(key) != null) {
            return new RString(map.get(key).longValue());
        }
        return RString.EMPTY;
    }

    private RString getタイトル1(RString 給付集計区分) {
        RString タイトル1 = RString.EMPTY;
        if (現物分.equals(給付集計区分)) {
            タイトル1 = new RString("（１）介護給付・予防給付（現物分）");
        } else if (償還審査分.equals(給付集計区分)) {
            タイトル1 = new RString("（１）介護給付・予防給付（償還分）");
        } else if (償還決定分.equals(給付集計区分)) {
            タイトル1 = new RString("（１）介護給付・予防給付（償還分）");
        }
        return タイトル1;
    }

    private JigyohokokuCompYoshiki202Data set集計結果(JigyohokokuCompYoshiki202Data reportData, Map<Decimal, Decimal> map) {
        reportData.set居宅_介護予防_サービス_要支援１(getValue(map, 数値_915));
        reportData.set居宅_介護予防_サービス_要支援２(getValue(map, 数値_1015));
        reportData.set居宅_介護予防_サービス_予防計(getValue(map, 数値_1115));
        reportData.set居宅_介護予防_サービス_非該当(getValue(map, 数値_115));
        reportData.set居宅_介護予防_サービス_経過的要介護(getValue(map, 数値_215));
        reportData.set居宅_介護予防_サービス_要介護１(getValue(map, 数値_315));
        reportData.set居宅_介護予防_サービス_要介護２(getValue(map, 数値_415));
        reportData.set居宅_介護予防_サービス_要介護３(getValue(map, 数値_515));
        reportData.set居宅_介護予防_サービス_要介護４(getValue(map, 数値_615));
        reportData.set居宅_介護予防_サービス_要介護５(getValue(map, 数値_715));
        reportData.set居宅_介護予防_サービス_介護計(getValue(map, 数値_815));
        reportData.set居宅_介護予防_サービス_合計(getValue(map, 数値_1215));
        reportData.set訪問サービス_要支援１(getValue(map, 数値_901));
        reportData.set訪問サービス_要支援２(getValue(map, 数値_1001));
        reportData.set訪問サービス_予防計(getValue(map, 数値_1101));
        reportData.set訪問サービス_非該当(getValue(map, 数値_101));
        reportData.set訪問サービス_経過的要介護(getValue(map, 数値_201));
        reportData.set訪問サービス_要介護１(getValue(map, 数値_301));
        reportData.set訪問サービス_要介護２(getValue(map, 数値_401));
        reportData.set訪問サービス_要介護３(getValue(map, 数値_501));
        reportData.set訪問サービス_要介護４(getValue(map, 数値_601));
        reportData.set訪問サービス_要介護５(getValue(map, 数値_701));
        reportData.set訪問サービス_介護計(getValue(map, 数値_801));
        reportData.set訪問サービス_合計(getValue(map, 数値_1201));
        reportData.set訪問介護_要支援１(getValue(map, 数値_916));
        reportData.set訪問介護_要支援２(getValue(map, 数値_1016));
        reportData.set訪問介護_予防計(getValue(map, 数値_1116));
        reportData.set訪問介護_非該当(getValue(map, 数値_116));
        reportData.set訪問介護_経過的要介護(getValue(map, 数値_216));
        reportData.set訪問介護_要介護１(getValue(map, 数値_316));
        reportData.set訪問介護_要介護２(getValue(map, 数値_416));
        reportData.set訪問介護_要介護３(getValue(map, 数値_516));
        reportData.set訪問介護_要介護４(getValue(map, 数値_616));
        reportData.set訪問介護_要介護５(getValue(map, 数値_716));
        reportData.set訪問介護_介護計(getValue(map, 数値_816));
        reportData.set訪問介護_合計(getValue(map, 数値_1216));
        reportData.set訪問入浴介護_要支援１(getValue(map, 数値_917));
        reportData.set訪問入浴介護_要支援２(getValue(map, 数値_1017));
        reportData.set訪問入浴介護_予防計(getValue(map, 数値_1117));
        reportData.set訪問入浴介護_非該当(getValue(map, 数値_117));
        reportData.set訪問入浴介護_経過的要介護(getValue(map, 数値_217));
        reportData.set訪問入浴介護_要介護１(getValue(map, 数値_317));
        reportData.set訪問入浴介護_要介護２(getValue(map, 数値_417));
        reportData.set訪問入浴介護_要介護３(getValue(map, 数値_517));
        reportData.set訪問入浴介護_要介護４(getValue(map, 数値_617));
        reportData.set訪問入浴介護_要介護５(getValue(map, 数値_717));
        reportData.set訪問入浴介護_介護計(getValue(map, 数値_817));
        reportData.set訪問入浴介護_合計(getValue(map, 数値_1217));
        reportData.set訪問看護_要支援１(getValue(map, 数値_918));
        reportData.set訪問看護_要支援２(getValue(map, 数値_1018));
        reportData.set訪問看護_予防計(getValue(map, 数値_1118));
        reportData.set訪問看護_非該当(getValue(map, 数値_118));
        reportData.set訪問看護_経過的要介護(getValue(map, 数値_218));
        reportData.set訪問看護_要介護１(getValue(map, 数値_318));
        reportData.set訪問看護_要介護２(getValue(map, 数値_418));
        reportData.set訪問看護_要介護３(getValue(map, 数値_518));
        reportData.set訪問看護_要介護４(getValue(map, 数値_618));
        reportData.set訪問看護_要介護５(getValue(map, 数値_718));
        reportData.set訪問看護_介護計(getValue(map, 数値_818));
        reportData.set訪問看護_合計(getValue(map, 数値_1218));
        reportData.set訪問リハビリテーション_要支援１(getValue(map, 数値_919));
        reportData.set訪問リハビリテーション_要支援２(getValue(map, 数値_1019));
        reportData.set訪問リハビリテーション_予防計(getValue(map, 数値_1119));
        reportData.set訪問リハビリテーション_非該当(getValue(map, 数値_119));
        reportData.set訪問リハビリテーション_経過的要介護(getValue(map, 数値_219));
        reportData.set訪問リハビリテーション_要介護１(getValue(map, 数値_319));
        reportData.set訪問リハビリテーション_要介護２(getValue(map, 数値_419));
        reportData.set訪問リハビリテーション_要介護３(getValue(map, 数値_519));
        reportData.set訪問リハビリテーション_要介護４(getValue(map, 数値_619));
        reportData.set訪問リハビリテーション_要介護５(getValue(map, 数値_719));
        reportData.set訪問リハビリテーション_介護計(getValue(map, 数値_819));
        reportData.set訪問リハビリテーション_合計(getValue(map, 数値_1219));
        reportData.set居宅療養管理指導_要支援１(getValue(map, 数値_926));
        reportData.set居宅療養管理指導_要支援２(getValue(map, 数値_1026));
        reportData.set居宅療養管理指導_予防計(getValue(map, 数値_1126));
        reportData.set居宅療養管理指導_非該当(getValue(map, 数値_126));
        reportData.set居宅療養管理指導_経過的要介護(getValue(map, 数値_226));
        reportData.set居宅療養管理指導_要介護１(getValue(map, 数値_326));
        reportData.set居宅療養管理指導_要介護２(getValue(map, 数値_426));
        reportData.set居宅療養管理指導_要介護３(getValue(map, 数値_526));
        reportData.set居宅療養管理指導_要介護４(getValue(map, 数値_626));
        reportData.set居宅療養管理指導_要介護５(getValue(map, 数値_726));
        reportData.set居宅療養管理指導_介護計(getValue(map, 数値_826));
        reportData.set居宅療養管理指導_合計(getValue(map, 数値_1226));
        reportData.set通所サービス_要支援１(getValue(map, 数値_930));
        reportData.set通所サービス_要支援２(getValue(map, 数値_1030));
        reportData.set通所サービス_予防計(getValue(map, 数値_1130));
        reportData.set通所サービス_非該当(getValue(map, 数値_130));
        reportData.set通所サービス_経過的要介護(getValue(map, 数値_230));
        reportData.set通所サービス_要介護１(getValue(map, 数値_330));
        reportData.set通所サービス_要介護２(getValue(map, 数値_430));
        reportData.set通所サービス_要介護３(getValue(map, 数値_530));
        reportData.set通所サービス_要介護４(getValue(map, 数値_630));
        reportData.set通所サービス_要介護５(getValue(map, 数値_730));
        reportData.set通所サービス_介護計(getValue(map, 数値_830));
        reportData.set通所サービス_合計(getValue(map, 数値_1230));
        reportData.set通所介護_要支援１(getValue(map, 数値_920));
        reportData.set通所介護_要支援２(getValue(map, 数値_1020));
        reportData.set通所介護_予防計(getValue(map, 数値_1120));
        reportData.set通所介護_非該当(getValue(map, 数値_120));
        reportData.set通所介護_経過的要介護(getValue(map, 数値_220));
        reportData.set通所介護_要介護１(getValue(map, 数値_320));
        reportData.set通所介護_要介護２(getValue(map, 数値_420));
        reportData.set通所介護_要介護３(getValue(map, 数値_520));
        reportData.set通所介護_要介護４(getValue(map, 数値_620));
        reportData.set通所介護_要介護５(getValue(map, 数値_720));
        reportData.set通所介護_介護計(getValue(map, 数値_820));
        reportData.set通所介護_合計(getValue(map, 数値_1220));
        reportData.set通所リハビリテーション_要支援１(getValue(map, 数値_921));
        reportData.set通所リハビリテーション_要支援２(getValue(map, 数値_1021));
        reportData.set通所リハビリテーション_予防計(getValue(map, 数値_1121));
        reportData.set通所リハビリテーション_非該当(getValue(map, 数値_121));
        reportData.set通所リハビリテーション_経過的要介護(getValue(map, 数値_221));
        reportData.set通所リハビリテーション_要介護１(getValue(map, 数値_321));
        reportData.set通所リハビリテーション_要介護２(getValue(map, 数値_421));
        reportData.set通所リハビリテーション_要介護３(getValue(map, 数値_521));
        reportData.set通所リハビリテーション_要介護４(getValue(map, 数値_621));
        reportData.set通所リハビリテーション_要介護５(getValue(map, 数値_721));
        reportData.set通所リハビリテーション_介護計(getValue(map, 数値_821));
        reportData.set通所リハビリテーション_合計(getValue(map, 数値_1221));
        reportData.set短期入所サービス_要支援１(getValue(map, 数値_902));
        reportData.set短期入所サービス_要支援２(getValue(map, 数値_1002));
        reportData.set短期入所サービス_予防計(getValue(map, 数値_1102));
        reportData.set短期入所サービス_非該当(getValue(map, 数値_102));
        reportData.set短期入所サービス_経過的要介護(getValue(map, 数値_202));
        reportData.set短期入所サービス_要介護１(getValue(map, 数値_302));
        reportData.set短期入所サービス_要介護２(getValue(map, 数値_402));
        reportData.set短期入所サービス_要介護３(getValue(map, 数値_502));
        reportData.set短期入所サービス_要介護４(getValue(map, 数値_602));
        reportData.set短期入所サービス_要介護５(getValue(map, 数値_702));
        reportData.set短期入所サービス_介護計(getValue(map, 数値_802));
        reportData.set短期入所サービス_合計(getValue(map, 数値_1202));
        reportData.set短期入所生活介護_要支援１(getValue(map, 数値_923));
        reportData.set短期入所生活介護_要支援２(getValue(map, 数値_1023));
        reportData.set短期入所生活介護_予防計(getValue(map, 数値_1123));
        reportData.set短期入所生活介護_非該当(getValue(map, 数値_123));
        reportData.set短期入所生活介護_経過的要介護(getValue(map, 数値_223));
        reportData.set短期入所生活介護_要介護１(getValue(map, 数値_323));
        reportData.set短期入所生活介護_要介護２(getValue(map, 数値_423));
        reportData.set短期入所生活介護_要介護３(getValue(map, 数値_523));
        reportData.set短期入所生活介護_要介護４(getValue(map, 数値_623));
        reportData.set短期入所生活介護_要介護５(getValue(map, 数値_723));
        reportData.set短期入所生活介護_介護計(getValue(map, 数値_823));
        reportData.set短期入所生活介護_合計(getValue(map, 数値_1223));
        return set集計結果ア(reportData, map);
    }

    private JigyohokokuCompYoshiki202Data set集計結果ア(JigyohokokuCompYoshiki202Data reportData, Map<Decimal, Decimal> map) {
        reportData.set短期入所療養介護_介護老人保健施設_要支援１(getValue(map, 数値_924));
        reportData.set短期入所療養介護_介護老人保健施設_要支援２(getValue(map, 数値_1024));
        reportData.set短期入所療養介護_介護老人保健施設_予防計(getValue(map, 数値_1124));
        reportData.set短期入所療養介護_介護老人保健施設_非該当(getValue(map, 数値_124));
        reportData.set短期入所療養介護_介護老人保健施設_経過的要介護(getValue(map, 数値_224));
        reportData.set短期入所療養介護_介護老人保健施設_要介護１(getValue(map, 数値_324));
        reportData.set短期入所療養介護_介護老人保健施設_要介護２(getValue(map, 数値_424));
        reportData.set短期入所療養介護_介護老人保健施設_要介護３(getValue(map, 数値_524));
        reportData.set短期入所療養介護_介護老人保健施設_要介護４(getValue(map, 数値_624));
        reportData.set短期入所療養介護_介護老人保健施設_要介護５(getValue(map, 数値_724));
        reportData.set短期入所療養介護_介護老人保健施設_介護計(getValue(map, 数値_824));
        reportData.set短期入所療養介護_介護老人保健施設_合計(getValue(map, 数値_1224));
        reportData.set短期入所療養介護_介護療養型医療施設等_要支援１(getValue(map, 数値_925));
        reportData.set短期入所療養介護_介護療養型医療施設等_要支援２(getValue(map, 数値_1025));
        reportData.set短期入所療養介護_介護療養型医療施設等_予防計(getValue(map, 数値_1125));
        reportData.set短期入所療養介護_介護療養型医療施設等_非該当(getValue(map, 数値_125));
        reportData.set短期入所療養介護_介護療養型医療施設等_経過的要介護(getValue(map, 数値_225));
        reportData.set短期入所療養介護_介護療養型医療施設等_要介護１(getValue(map, 数値_325));
        reportData.set短期入所療養介護_介護療養型医療施設等_要介護２(getValue(map, 数値_425));
        reportData.set短期入所療養介護_介護療養型医療施設等_要介護３(getValue(map, 数値_525));
        reportData.set短期入所療養介護_介護療養型医療施設等_要介護４(getValue(map, 数値_625));
        reportData.set短期入所療養介護_介護療養型医療施設等_要介護５(getValue(map, 数値_725));
        reportData.set短期入所療養介護_介護療養型医療施設等_介護計(getValue(map, 数値_825));
        reportData.set短期入所療養介護_介護療養型医療施設等_合計(getValue(map, 数値_1225));
        reportData.set福祉用具_住宅改修サービス_要支援１(getValue(map, 数値_903));
        reportData.set福祉用具_住宅改修サービス_要支援２(getValue(map, 数値_1003));
        reportData.set福祉用具_住宅改修サービス_予防計(getValue(map, 数値_1103));
        reportData.set福祉用具_住宅改修サービス_非該当(getValue(map, 数値_103));
        reportData.set福祉用具_住宅改修サービス_経過的要介護(getValue(map, 数値_203));
        reportData.set福祉用具_住宅改修サービス_要介護１(getValue(map, 数値_303));
        reportData.set福祉用具_住宅改修サービス_要介護２(getValue(map, 数値_403));
        reportData.set福祉用具_住宅改修サービス_要介護３(getValue(map, 数値_503));
        reportData.set福祉用具_住宅改修サービス_要介護４(getValue(map, 数値_603));
        reportData.set福祉用具_住宅改修サービス_要介護５(getValue(map, 数値_703));
        reportData.set福祉用具_住宅改修サービス_介護計(getValue(map, 数値_803));
        reportData.set福祉用具_住宅改修サービス_合計(getValue(map, 数値_1203));
        reportData.set福祉用具貸与_要支援１(getValue(map, 数値_922));
        reportData.set福祉用具貸与_要支援２(getValue(map, 数値_1022));
        reportData.set福祉用具貸与_予防計(getValue(map, 数値_1122));
        reportData.set福祉用具貸与_非該当(getValue(map, 数値_122));
        reportData.set福祉用具貸与_経過的要介護(getValue(map, 数値_222));
        reportData.set福祉用具貸与_要介護１(getValue(map, 数値_322));
        reportData.set福祉用具貸与_要介護２(getValue(map, 数値_422));
        reportData.set福祉用具貸与_要介護３(getValue(map, 数値_522));
        reportData.set福祉用具貸与_要介護４(getValue(map, 数値_622));
        reportData.set福祉用具貸与_要介護５(getValue(map, 数値_722));
        reportData.set福祉用具貸与_介護計(getValue(map, 数値_822));
        reportData.set福祉用具貸与_合計(getValue(map, 数値_1222));
        reportData.set特定施設入居者生活介護_要支援１(getValue(map, 数値_928));
        reportData.set特定施設入居者生活介護_要支援２(getValue(map, 数値_1028));
        reportData.set特定施設入居者生活介護_予防計(getValue(map, 数値_1128));
        reportData.set特定施設入居者生活介護_非該当(getValue(map, 数値_128));
        reportData.set特定施設入居者生活介護_経過的要介護(getValue(map, 数値_228));
        reportData.set特定施設入居者生活介護_要介護１(getValue(map, 数値_328));
        reportData.set特定施設入居者生活介護_要介護２(getValue(map, 数値_428));
        reportData.set特定施設入居者生活介護_要介護３(getValue(map, 数値_528));
        reportData.set特定施設入居者生活介護_要介護４(getValue(map, 数値_628));
        reportData.set特定施設入居者生活介護_要介護５(getValue(map, 数値_728));
        reportData.set特定施設入居者生活介護_介護計(getValue(map, 数値_828));
        reportData.set特定施設入居者生活介護_合計(getValue(map, 数値_1228));
        reportData.set介護予防支援_居宅介護支援_要支援１(getValue(map, 数値_929));
        reportData.set介護予防支援_居宅介護支援_要支援２(getValue(map, 数値_1029));
        reportData.set介護予防支援_居宅介護支援_予防計(getValue(map, 数値_1129));
        reportData.set介護予防支援_居宅介護支援_非該当(getValue(map, 数値_129));
        reportData.set介護予防支援_居宅介護支援_経過的要介護(getValue(map, 数値_229));
        reportData.set介護予防支援_居宅介護支援_要介護１(getValue(map, 数値_329));
        reportData.set介護予防支援_居宅介護支援_要介護２(getValue(map, 数値_429));
        reportData.set介護予防支援_居宅介護支援_要介護３(getValue(map, 数値_529));
        reportData.set介護予防支援_居宅介護支援_要介護４(getValue(map, 数値_629));
        reportData.set介護予防支援_居宅介護支援_要介護５(getValue(map, 数値_729));
        reportData.set介護予防支援_居宅介護支援_介護計(getValue(map, 数値_829));
        reportData.set介護予防支援_居宅介護支援_合計(getValue(map, 数値_1229));
        reportData.set地域密着型_介護予防_サービス_要支援１(getValue(map, 数値_931));
        reportData.set地域密着型_介護予防_サービス_要支援２(getValue(map, 数値_1031));
        reportData.set地域密着型_介護予防_サービス_予防計(getValue(map, 数値_1131));
        reportData.set地域密着型_介護予防_サービス_非該当(getValue(map, 数値_131));
        reportData.set地域密着型_介護予防_サービス_経過的要介護(getValue(map, 数値_231));
        reportData.set地域密着型_介護予防_サービス_要介護１(getValue(map, 数値_331));
        reportData.set地域密着型_介護予防_サービス_要介護２(getValue(map, 数値_431));
        reportData.set地域密着型_介護予防_サービス_要介護３(getValue(map, 数値_531));
        reportData.set地域密着型_介護予防_サービス_要介護４(getValue(map, 数値_631));
        reportData.set地域密着型_介護予防_サービス_要介護５(getValue(map, 数値_731));
        reportData.set地域密着型_介護予防_サービス_介護計(getValue(map, 数値_831));
        reportData.set地域密着型_介護予防_サービス_合計(getValue(map, 数値_1231));
        reportData.set定期巡回_随時対応型訪問介護看護_要支援１(getValue(map, 数値_937));
        reportData.set定期巡回_随時対応型訪問介護看護_要支援２(getValue(map, 数値_1037));
        reportData.set定期巡回_随時対応型訪問介護看護_予防計(getValue(map, 数値_1137));
        reportData.set定期巡回_随時対応型訪問介護看護_非該当(getValue(map, 数値_137));
        reportData.set定期巡回_随時対応型訪問介護看護_経過的要介護(getValue(map, 数値_237));
        reportData.set定期巡回_随時対応型訪問介護看護_要介護１(getValue(map, 数値_337));
        reportData.set定期巡回_随時対応型訪問介護看護_要介護２(getValue(map, 数値_437));
        reportData.set定期巡回_随時対応型訪問介護看護_要介護３(getValue(map, 数値_537));
        reportData.set定期巡回_随時対応型訪問介護看護_要介護４(getValue(map, 数値_637));
        reportData.set定期巡回_随時対応型訪問介護看護_要介護５(getValue(map, 数値_737));
        reportData.set定期巡回_随時対応型訪問介護看護_介護計(getValue(map, 数値_837));
        reportData.set定期巡回_随時対応型訪問介護看護_合計(getValue(map, 数値_1237));
        reportData.set夜間対応型訪問介護_要支援１(getValue(map, 数値_932));
        reportData.set夜間対応型訪問介護_要支援２(getValue(map, 数値_1032));
        reportData.set夜間対応型訪問介護_予防計(getValue(map, 数値_1132));
        reportData.set夜間対応型訪問介護_非該当(getValue(map, 数値_132));
        reportData.set夜間対応型訪問介護_経過的要介護(getValue(map, 数値_232));
        reportData.set夜間対応型訪問介護_要介護１(getValue(map, 数値_332));
        reportData.set夜間対応型訪問介護_要介護２(getValue(map, 数値_432));
        reportData.set夜間対応型訪問介護_要介護３(getValue(map, 数値_532));
        reportData.set夜間対応型訪問介護_要介護４(getValue(map, 数値_632));
        reportData.set夜間対応型訪問介護_要介護５(getValue(map, 数値_732));
        reportData.set夜間対応型訪問介護_介護計(getValue(map, 数値_832));
        reportData.set夜間対応型訪問介護_合計(getValue(map, 数値_1232));
        reportData.set地域密着型通所介護_要支援１(getValue(map, 数値_939));
        reportData.set地域密着型通所介護_要支援２(getValue(map, 数値_1039));
        reportData.set地域密着型通所介護_予防計(getValue(map, 数値_1139));
        reportData.set地域密着型通所介護_非該当(getValue(map, 数値_139));
        reportData.set地域密着型通所介護_経過的要介護(getValue(map, 数値_239));
        reportData.set地域密着型通所介護_要介護１(getValue(map, 数値_339));
        reportData.set地域密着型通所介護_要介護２(getValue(map, 数値_439));
        reportData.set地域密着型通所介護_要介護３(getValue(map, 数値_539));
        reportData.set地域密着型通所介護_要介護４(getValue(map, 数値_639));
        reportData.set地域密着型通所介護_要介護５(getValue(map, 数値_739));
        reportData.set地域密着型通所介護_介護計(getValue(map, 数値_839));
        reportData.set地域密着型通所介護_合計(getValue(map, 数値_1239));
        return set集計結果イ(reportData, map);
    }

    private JigyohokokuCompYoshiki202Data set集計結果イ(JigyohokokuCompYoshiki202Data reportData, Map<Decimal, Decimal> map) {
        reportData.set認知症対応型通所介護_要支援１(getValue(map, 数値_933));
        reportData.set認知症対応型通所介護_要支援２(getValue(map, 数値_1033));
        reportData.set認知症対応型通所介護_予防計(getValue(map, 数値_1133));
        reportData.set認知症対応型通所介護_非該当(getValue(map, 数値_133));
        reportData.set認知症対応型通所介護_経過的要介護(getValue(map, 数値_233));
        reportData.set認知症対応型通所介護_要介護１(getValue(map, 数値_333));
        reportData.set認知症対応型通所介護_要介護２(getValue(map, 数値_433));
        reportData.set認知症対応型通所介護_要介護３(getValue(map, 数値_533));
        reportData.set認知症対応型通所介護_要介護４(getValue(map, 数値_633));
        reportData.set認知症対応型通所介護_要介護５(getValue(map, 数値_733));
        reportData.set認知症対応型通所介護_介護計(getValue(map, 数値_833));
        reportData.set認知症対応型通所介護_合計(getValue(map, 数値_1233));
        reportData.set小規模多機能型居宅介護_要支援１(getValue(map, 数値_934));
        reportData.set小規模多機能型居宅介護_要支援２(getValue(map, 数値_1034));
        reportData.set小規模多機能型居宅介護_予防計(getValue(map, 数値_1134));
        reportData.set小規模多機能型居宅介護_非該当(getValue(map, 数値_134));
        reportData.set小規模多機能型居宅介護_経過的要介護(getValue(map, 数値_234));
        reportData.set小規模多機能型居宅介護_要介護１(getValue(map, 数値_334));
        reportData.set小規模多機能型居宅介護_要介護２(getValue(map, 数値_434));
        reportData.set小規模多機能型居宅介護_要介護３(getValue(map, 数値_534));
        reportData.set小規模多機能型居宅介護_要介護４(getValue(map, 数値_634));
        reportData.set小規模多機能型居宅介護_要介護５(getValue(map, 数値_734));
        reportData.set小規模多機能型居宅介護_介護計(getValue(map, 数値_834));
        reportData.set小規模多機能型居宅介護_合計(getValue(map, 数値_1234));
        reportData.set認知症対応型共同生活介護_要支援１(getValue(map, 数値_927));
        reportData.set認知症対応型共同生活介護_要支援２(getValue(map, 数値_1027));
        reportData.set認知症対応型共同生活介護_予防計(getValue(map, 数値_1127));
        reportData.set認知症対応型共同生活介護_非該当(getValue(map, 数値_127));
        reportData.set認知症対応型共同生活介護_経過的要介護(getValue(map, 数値_227));
        reportData.set認知症対応型共同生活介護_要介護１(getValue(map, 数値_327));
        reportData.set認知症対応型共同生活介護_要介護２(getValue(map, 数値_427));
        reportData.set認知症対応型共同生活介護_要介護３(getValue(map, 数値_527));
        reportData.set認知症対応型共同生活介護_要介護４(getValue(map, 数値_627));
        reportData.set認知症対応型共同生活介護_要介護５(getValue(map, 数値_727));
        reportData.set認知症対応型共同生活介護_介護計(getValue(map, 数値_827));
        reportData.set認知症対応型共同生活介護_合計(getValue(map, 数値_1227));
        reportData.set地域密着型特定施設入居者生活介護_要支援１(getValue(map, 数値_935));
        reportData.set地域密着型特定施設入居者生活介護_要支援２(getValue(map, 数値_1035));
        reportData.set地域密着型特定施設入居者生活介護_予防計(getValue(map, 数値_1135));
        reportData.set地域密着型特定施設入居者生活介護_非該当(getValue(map, 数値_135));
        reportData.set地域密着型特定施設入居者生活介護_経過的要介護(getValue(map, 数値_235));
        reportData.set地域密着型特定施設入居者生活介護_要介護１(getValue(map, 数値_335));
        reportData.set地域密着型特定施設入居者生活介護_要介護２(getValue(map, 数値_435));
        reportData.set地域密着型特定施設入居者生活介護_要介護３(getValue(map, 数値_535));
        reportData.set地域密着型特定施設入居者生活介護_要介護４(getValue(map, 数値_635));
        reportData.set地域密着型特定施設入居者生活介護_要介護５(getValue(map, 数値_735));
        reportData.set地域密着型特定施設入居者生活介護_介護計(getValue(map, 数値_835));
        reportData.set地域密着型特定施設入居者生活介護_合計(getValue(map, 数値_1235));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要支援１(getValue(map, 数値_936));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要支援２(getValue(map, 数値_1036));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_予防計(getValue(map, 数値_1136));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_非該当(getValue(map, 数値_136));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_経過的要介護(getValue(map, 数値_236));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要介護１(getValue(map, 数値_336));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要介護２(getValue(map, 数値_436));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要介護３(getValue(map, 数値_536));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要介護４(getValue(map, 数値_636));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_要介護５(getValue(map, 数値_736));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_介護計(getValue(map, 数値_836));
        reportData.set地域密着型介護老人福祉施設入居者生活介護_合計(getValue(map, 数値_1236));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要支援１(getValue(map, 数値_938));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要支援２(getValue(map, 数値_1038));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_予防計(getValue(map, 数値_1138));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_非該当(getValue(map, 数値_138));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_経過的要介護(getValue(map, 数値_238));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要介護１(getValue(map, 数値_338));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要介護２(getValue(map, 数値_438));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要介護３(getValue(map, 数値_538));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要介護４(getValue(map, 数値_638));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_要介護５(getValue(map, 数値_738));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_介護計(getValue(map, 数値_838));
        reportData.set複合型サービス_看護小規模多機能型居宅介護_合計(getValue(map, 数値_1238));
        reportData.set施設介護サービス_要支援１(getValue(map, 数値_906));
        reportData.set施設介護サービス_要支援２(getValue(map, 数値_1006));
        reportData.set施設介護サービス_予防計(getValue(map, 数値_1106));
        reportData.set施設介護サービス_非該当(getValue(map, 数値_106));
        reportData.set施設介護サービス_経過的要介護(getValue(map, 数値_206));
        reportData.set施設介護サービス_要介護１(getValue(map, 数値_306));
        reportData.set施設介護サービス_要介護２(getValue(map, 数値_406));
        reportData.set施設介護サービス_要介護３(getValue(map, 数値_506));
        reportData.set施設介護サービス_要介護４(getValue(map, 数値_606));
        reportData.set施設介護サービス_要介護５(getValue(map, 数値_706));
        reportData.set施設介護サービス_介護計(getValue(map, 数値_806));
        reportData.set施設介護サービス_合計(getValue(map, 数値_1206));
        reportData.set介護老人福祉施設_要支援１(getValue(map, 数値_907));
        reportData.set介護老人福祉施設_要支援２(getValue(map, 数値_1007));
        reportData.set介護老人福祉施設_予防計(getValue(map, 数値_1107));
        reportData.set介護老人福祉施設_非該当(getValue(map, 数値_107));
        reportData.set介護老人福祉施設_経過的要介護(getValue(map, 数値_207));
        reportData.set介護老人福祉施設_要介護１(getValue(map, 数値_307));
        reportData.set介護老人福祉施設_要介護２(getValue(map, 数値_407));
        reportData.set介護老人福祉施設_要介護３(getValue(map, 数値_507));
        reportData.set介護老人福祉施設_要介護４(getValue(map, 数値_607));
        reportData.set介護老人福祉施設_要介護５(getValue(map, 数値_707));
        reportData.set介護老人福祉施設_介護計(getValue(map, 数値_807));
        reportData.set介護老人福祉施設_合計(getValue(map, 数値_1207));
        reportData.set介護老人保健施設_要支援１(getValue(map, 数値_908));
        reportData.set介護老人保健施設_要支援２(getValue(map, 数値_1008));
        reportData.set介護老人保健施設_予防計(getValue(map, 数値_1108));
        reportData.set介護老人保健施設_非該当(getValue(map, 数値_108));
        reportData.set介護老人保健施設_経過的要介護(getValue(map, 数値_208));
        reportData.set介護老人保健施設_要介護１(getValue(map, 数値_308));
        reportData.set介護老人保健施設_要介護２(getValue(map, 数値_408));
        reportData.set介護老人保健施設_要介護３(getValue(map, 数値_508));
        reportData.set介護老人保健施設_要介護４(getValue(map, 数値_608));
        reportData.set介護老人保健施設_要介護５(getValue(map, 数値_708));
        reportData.set介護老人保健施設_介護計(getValue(map, 数値_808));
        reportData.set介護老人保健施設_合計(getValue(map, 数値_1208));
        reportData.set介護療養型医療施設_要支援１(getValue(map, 数値_909));
        reportData.set介護療養型医療施設_要支援２(getValue(map, 数値_1009));
        reportData.set介護療養型医療施設_予防計(getValue(map, 数値_1109));
        reportData.set介護療養型医療施設_非該当(getValue(map, 数値_109));
        reportData.set介護療養型医療施設_経過的要介護(getValue(map, 数値_209));
        reportData.set介護療養型医療施設_要介護１(getValue(map, 数値_309));
        reportData.set介護療養型医療施設_要介護２(getValue(map, 数値_409));
        reportData.set介護療養型医療施設_要介護３(getValue(map, 数値_509));
        reportData.set介護療養型医療施設_要介護４(getValue(map, 数値_609));
        reportData.set介護療養型医療施設_要介護５(getValue(map, 数値_709));
        reportData.set介護療養型医療施設_介護計(getValue(map, 数値_809));
        reportData.set介護療養型医療施設_合計(getValue(map, 数値_1209));
        reportData.set総計_要支援１(getValue(map, 数値_914));
        reportData.set総計_要支援２(getValue(map, 数値_1014));
        reportData.set総計_予防計(getValue(map, 数値_1114));
        reportData.set総計_非該当(getValue(map, 数値_114));
        reportData.set総計_経過的要介護(getValue(map, 数値_214));
        reportData.set総計_要介護１(getValue(map, 数値_314));
        reportData.set総計_要介護２(getValue(map, 数値_414));
        reportData.set総計_要介護３(getValue(map, 数値_514));
        reportData.set総計_要介護４(getValue(map, 数値_614));
        reportData.set総計_要介護５(getValue(map, 数値_714));
        reportData.set総計_介護計(getValue(map, 数値_814));
        reportData.set総計_合計(getValue(map, 数値_1214));
        return reportData;
    }
}
