/// <reference path="../d.ts/jquery.d.ts" />
/// <reference path="../d.ts/UzViewControls.d.ts" />
/// <reference path="../d.ts/UzaConverter.d.ts" />

module DBD {
    /**
     * 自動生成コードです。修正しないでください。
     * FutanGendogakuNinteiクラスのみで継承して使えます。
     */
    export class FutanGendogakuNintei_Design extends Uz.CommonChildDiv {
    
        public get visible_Kyusochisha() {
            return Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2].items[4]["fieldName"])["visible"];
        }
        
        public set visible_Kyusochisha(value) {
            if ( $("#" + this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2].items[4]["fieldName"]).length > 0 && 
                 Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2].items[4]["fieldName"]) != undefined ) {
                Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2].items[4]["fieldName"])["visible"] = value;
            } else {
                this.layout.items[0].items[2].items[2].items[4]["visible"] = value;
                this.raisePropertyChanged(this.layout);
            }
        }
        
        constructor($parentElement: JQuery, isDesignMode: bool, fieldName: string) {
            super($parentElement, isDesignMode, FutanGendogakuNintei_Design.myLayout, fieldName);
        }
        
        /**
         * レイアウト情報のプロパティを登録します
         * @method registProperty
         */
        public registProperty() {
            super.registProperty();
            Uz.JSControlUtil.registProperty("visible_Kyusochisha");
        }
        
        /**
         * コントロール内で編集させたいプロパティをまとめたEditablePropertyInfoオブジェクトを返却します。
         * @method getEditableProperty
         * @return EditablePropertyInfoオブジェクト
         */
        public getEditablePropertyInfo(): any {
            var editablePropertyInfo = super.getEditablePropertyInfo();
            editablePropertyInfo["visible_Kyusochisha"] = Uz.JSControlUtil.getJSControl(this.fieldName + "_" + this.layout.items[0]["fieldName"] + "_" + this.layout.items[0].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2]["fieldName"] + "_" + this.layout.items[0].items[2].items[2].items[4]["fieldName"]).getEditablePropertyInfo()["visible"];
            
            return editablePropertyInfo;
        }
        public static myLayout = {
 "fieldName": "defaultLayout",
 "items": [
  {
   "fieldName": "FutanGendogakuNintei",
   "items": [
    {
     "fieldName": "txtHiddenHihokenshaNo",
     "items": [],
     "controlType": "TextBox",
     "width": "XS",
     "visible": false,
     "displayNone": true,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "selectControlID": "txtHiddenHihokenshaNo_core",
     "helpMessageID": "",
     "jpControlName": "",
     "readOnly": true,
     "required": false,
     "maxLength": 100000000,
     "minLength": 0,
     "textAlign": 0,
     "placeHolder": "",
     "textKind": 0,
     "isPrivateInfo": false,
     "isPassword": false,
     "isComboBox": false,
     "onFocus": "",
     "onBlur": "",
     "onChange": "",
     "onKeyPress": "",
     "text": "",
     "suggest": [],
     "value": "",
     "labelLText": "",
     "labelRText": "",
     "labelLWidth": "S",
     "labelRWidth": "S",
     "labelLAlign": 2,
     "labelRAlign": 0,
     "decorationClass": "",
     "permitCharactor": ""
    },
    {
     "fieldName": "dgFutanGendogakuNinteiList",
     "items": [],
     "controlType": "DataGrid",
     "width": "910px",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": false,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "selectControlID": "dgFutanGendogakuNinteiList",
     "helpMessageID": "",
     "jpControlName": "",
     "readOnly": false,
     "height": "185px",
     "gridSetting": {
      "rowHeight": 25,
      "isMultiSelectable": false,
      "isShowHeader": true,
      "isShowFooter": true,
      "isShowFilter": false,
      "isShowFilterButton": false,
      "isShowRowState": false,
      "isShowSelectButtonColumn": false,
      "isShowModifyButtonColumn": false,
      "isShowDeleteButtonColumn": false,
      "limitRowCount": 0,
      "selectedRowCount": 0,
      "header": {
       "combineColumns": [],
       "frozenColumn": "",
       "headerHeight": 0
      },
      "columns": [
       {
        "columnName": "申請日",
        "dataName": "shinseiDate",
        "toolTip": "",
        "bgColor": 0,
        "width": 80,
        "visible": true,
        "cellType": 7,
        "cellDetails": {
         "cellType": 7,
         "ymdKubun": 2,
         "displayFormat": 0,
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "shinseiDate"
       },
       {
        "columnName": "決定日",
        "dataName": "ketteiDate",
        "toolTip": "",
        "bgColor": 0,
        "width": 80,
        "visible": true,
        "cellType": 7,
        "cellDetails": {
         "cellType": 7,
         "ymdKubun": 2,
         "displayFormat": 0,
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "ketteiDate"
       },
       {
        "columnName": "決定区分",
        "dataName": "ketteiKubun",
        "toolTip": "",
        "bgColor": 0,
        "width": 100,
        "visible": true,
        "cellType": 0,
        "cellDetails": {
         "cellType": 0
        },
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "ketteiKubun"
       },
       {
        "columnName": "適用日",
        "dataName": "tekiyoDate",
        "toolTip": "",
        "bgColor": 0,
        "width": 80,
        "visible": true,
        "cellType": 7,
        "cellDetails": {
         "cellType": 7,
         "ymdKubun": 2,
         "displayFormat": 0,
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "tekiyoDate"
       },
       {
        "columnName": "有効期限",
        "dataName": "yukoKigen",
        "toolTip": "",
        "bgColor": 0,
        "width": 80,
        "visible": true,
        "cellType": 7,
        "cellDetails": {
         "cellType": 7,
         "ymdKubun": 2,
         "displayFormat": 0,
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "yukoKigen"
       },
       {
        "columnName": "申請理由",
        "dataName": "shinseiRiyu",
        "toolTip": "",
        "bgColor": 0,
        "width": 180,
        "visible": true,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "shinseiRiyu"
       },
       {
        "columnName": "承認しない理由",
        "dataName": "fushoninRiyu",
        "toolTip": "",
        "bgColor": 0,
        "width": 180,
        "visible": true,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "fushoninRiyu"
       },
       {
        "columnName": "負担段階",
        "dataName": "futanDankai",
        "toolTip": "",
        "bgColor": 0,
        "width": 100,
        "visible": true,
        "cellType": 0,
        "cellDetails": null,
        "align": 1,
        "resize": true,
        "isPrivateInfo": false,
        "sortKey": "futanDankai"
       },
       {
        "columnName": "旧措置",
        "dataName": "kyushochisha",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "kyushochisha"
       },
       {
        "columnName": "居室種別",
        "dataName": "kyoshitsuType",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "kyoshitsuType"
       },
       {
        "columnName": "境界層",
        "dataName": "kyokaiso",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "kyokaiso"
       },
       {
        "columnName": "激変緩和",
        "dataName": "gekihenKanwa",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 0,
        "cellDetails": null,
        "align": 0,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "gekihenKanwa"
       },
       {
        "columnName": "食費",
        "dataName": "shokuhi",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "shokuhi"
       },
       {
        "columnName": "ユニット型個室",
        "dataName": "unitKoshitsu",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "unitKoshitsu"
       },
       {
        "columnName": "ユニット型準個室",
        "dataName": "unitJunKoshitsu",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "unitJunKoshitsu"
       },
       {
        "columnName": "多床室",
        "dataName": "tashoshitsu",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "tashoshitsu"
       },
       {
        "columnName": "従来型個室(特養等)",
        "dataName": "juraigataKoshitsuTokuyo",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "juraigataKoshitsuTokuyo"
       },
       {
        "columnName": "従来型個室(老健)",
        "dataName": "juraigataKoshitsuRoken",
        "toolTip": "",
        "bgColor": 0,
        "width": 0,
        "visible": false,
        "cellType": 5,
        "cellDetails": {
         "cellType": 5,
         "maxLength": "1000000000000",
         "minLength": "0",
         "maxValue": "1.7976931348623157e+308",
         "minValue": "0",
         "isCurrency": false,
         "isComma": false,
         "decimalPointLength": "0",
         "onChange": "",
         "isSetValueToToolTip": false,
         "readOnly": true
        },
        "align": 2,
        "resize": false,
        "isPrivateInfo": false,
        "sortKey": "juraigataKoshitsuRoken"
       }
      ]
     },
     "onSort": "",
     "onSelect": "onSelect_dgFutanGendogakuNinteiList",
     "onSelectByDblClick": "",
     "onSelectBySelectButton": "",
     "onSelectByModifyButton": "",
     "onSelectByDeleteButton": "",
     "onAfterRequest": "",
     "onAfterRequestByDblClick": "",
     "onAfterRequestBySelectButton": "",
     "onAfterRequestByModifyButton": "",
     "onAfterRequestByDeleteButton": "",
     "onOnlyRow": "",
     "onNoRow": "",
     "onMultiRows": "",
     "dataSource": [],
     "sortOrder": "riyoshaFutangaku",
     "isAscending": true,
     "filterList": [],
     "activeRowId": -1,
     "gridAction": []
    },
    {
     "fieldName": "FutanGendogakuNinteiDetail",
     "items": [
      {
       "fieldName": "txtShinseiDate",
       "items": [],
       "controlType": "TextBoxFlexibleDate",
       "width": "80px",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "S",
       "marginRight": "XS",
       "selectControlID": "txtShinseiDate_core",
       "helpMessageID": "",
       "jpControlName": "",
       "readOnly": true,
       "required": false,
       "placeHolder": "",
       "isPrivateInfo": false,
       "isPassword": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "value": "",
       "labelLText": "申請日",
       "labelRText": "",
       "labelLWidth": "S",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "decorationClass": "",
       "ymdKubun": 2,
       "displayFormat": 0,
       "permitCharactor": "./_-"
      },
      {
       "fieldName": "txtShinseiRiyu",
       "items": [],
       "controlType": "TextBox",
       "width": "L",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": false,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "selectControlID": "txtShinseiRiyu_core",
       "helpMessageID": "",
       "jpControlName": "",
       "readOnly": true,
       "required": false,
       "maxLength": 100000000,
       "minLength": 0,
       "textAlign": 0,
       "placeHolder": "",
       "textKind": 0,
       "isPrivateInfo": false,
       "isPassword": false,
       "isComboBox": false,
       "onFocus": "",
       "onBlur": "",
       "onChange": "",
       "onKeyPress": "",
       "text": "",
       "suggest": [],
       "value": "",
       "labelLText": "申請理由",
       "labelRText": "",
       "labelLWidth": "S",
       "labelRWidth": "S",
       "labelLAlign": 2,
       "labelRAlign": 0,
       "decorationClass": "",
       "permitCharactor": ""
      },
      {
       "fieldName": "FutanGendogakuNinteiRiyoshaFutan",
       "items": [
        {
         "fieldName": "txtKetteiDate",
         "items": [],
         "controlType": "TextBoxFlexibleDate",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtKetteiDate_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "placeHolder": "",
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "value": "",
         "labelLText": "決定日",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "ymdKubun": 2,
         "displayFormat": 0,
         "permitCharactor": "./_-"
        },
        {
         "fieldName": "txtKetteiKubun",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtKetteiKubun_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "決定区分",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "txtTekiyoDate",
         "items": [],
         "controlType": "TextBoxFlexibleDate",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtTekiyoDate_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "placeHolder": "",
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "value": "",
         "labelLText": "適用日",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "ymdKubun": 2,
         "displayFormat": 0,
         "permitCharactor": "./_-"
        },
        {
         "fieldName": "txtYukokigenDate",
         "items": [],
         "controlType": "TextBoxFlexibleDate",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtYukokigenDate_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "placeHolder": "",
         "isPrivateInfo": false,
         "isPassword": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "value": "",
         "labelLText": "有効期限",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "ymdKubun": 2,
         "displayFormat": 0,
         "permitCharactor": "./_-"
        },
        {
         "fieldName": "txtKyushochisha",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtKyushochisha_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "旧措置",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "txtFutanDankai",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtFutanDankai_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "負担段階",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "txtKyoshitsuType",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtKyoshitsuType_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "居室種別",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "txtKyokaiso",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtKyokaiso_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "境界層",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "txtGekihenKanwa",
         "items": [],
         "controlType": "TextBox",
         "width": "80px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtGekihenKanwa_core",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "required": false,
         "maxLength": 100000000,
         "minLength": 0,
         "textAlign": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "isPassword": false,
         "isComboBox": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "suggest": [],
         "value": "",
         "labelLText": "激変緩和",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "permitCharactor": ""
        },
        {
         "fieldName": "FutanGendogaku",
         "items": [
          {
           "fieldName": "txtShokuhi",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "selectControlID": "txtShokuhi_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": "5",
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "食費",
           "labelRText": "円",
           "labelLWidth": "S",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          },
          {
           "fieldName": "txtUnitKoshitsu",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "selectControlID": "txtUnitKoshitsu_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": "5",
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "ユニット型個室",
           "labelRText": "円",
           "labelLWidth": "160px",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          },
          {
           "fieldName": "txtUnitJunKoshitsu",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "",
           "selectControlID": "txtUnitJunKoshitsu_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": 100000000,
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "ユニット型準個室",
           "labelRText": "円",
           "labelLWidth": "160px",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          },
          {
           "fieldName": "txtTashoshitsu",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": true,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "selectControlID": "txtTashoshitsu_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": "5",
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "多床室",
           "labelRText": "円",
           "labelLWidth": "S",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          },
          {
           "fieldName": "txtJuraigataKoshitsuTokuyo",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "XS",
           "selectControlID": "txtJuraigataKoshitsuTokuyo_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": "5",
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "従来型個室(特養等)",
           "labelRText": "円",
           "labelLWidth": "160px",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": true,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          },
          {
           "fieldName": "txtJuraigataKoshitsuRoken",
           "items": [],
           "controlType": "TextBoxNum",
           "width": "60px",
           "visible": true,
           "displayNone": false,
           "disabled": false,
           "accessKey": "",
           "nextFocusFieldName": "",
           "wrap": false,
           "dependencies": [],
           "float": 0,
           "toolTip": "",
           "authorityMode": 0,
           "marginLeft": "XS",
           "marginRight": "",
           "selectControlID": "txtJuraigataKoshitsuRoken_core",
           "helpMessageID": "",
           "jpControlName": "",
           "readOnly": true,
           "required": false,
           "maxLength": "5",
           "minLength": 0,
           "textAlign": 2,
           "placeHolder": "",
           "textKind": 2,
           "isPrivateInfo": false,
           "isPassword": false,
           "isComboBox": false,
           "onFocus": "",
           "onBlur": "",
           "onChange": "",
           "onKeyPress": "",
           "text": "",
           "suggest": [],
           "value": "",
           "labelLText": "従来型個室(老健)",
           "labelRText": "円",
           "labelLWidth": "160px",
           "labelRWidth": "16px",
           "labelLAlign": 2,
           "labelRAlign": 0,
           "decorationClass": "",
           "maxValue": "99999",
           "minValue": 0,
           "isCurrency": false,
           "isComma": false,
           "decimalPointLength": 0,
           "permitCharactor": "+-,.\\"
          }
         ],
         "controlType": "Panel",
         "width": "875px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": true,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "FutanGendogaku",
         "helpMessageID": "",
         "jpControlName": "",
         "onLoad": "",
         "title": "負担限度額",
         "marginTop": "Default",
         "marginBottom": "Default",
         "isOpen": true,
         "canOpenAndClose": false,
         "postParameterPanelNames": [
          {
           "postParameterPanelNames": "FutanGendogaku"
          }
         ],
         "requestSettings": [],
         "hiddenInput": [],
         "onOpen": "",
         "onClose": "",
         "session": {},
         "eraseBorder": false,
         "backgroundColor": 0,
         "widthAuto": false,
         "panelDisplay": 1,
         "isGroupBox": false,
         "readOnly": false,
         "height": "Auto",
         "canPost": true
        },
        {
         "fieldName": "txtFushoninRiyu",
         "items": [],
         "controlType": "TextBoxMultiLine",
         "width": "750px",
         "visible": true,
         "displayNone": false,
         "disabled": false,
         "accessKey": "",
         "nextFocusFieldName": "",
         "wrap": false,
         "dependencies": [],
         "float": 0,
         "toolTip": "",
         "authorityMode": 0,
         "marginLeft": "XS",
         "marginRight": "XS",
         "selectControlID": "txtFushoninRiyu_text_area",
         "helpMessageID": "",
         "jpControlName": "",
         "readOnly": true,
         "height": "XS",
         "required": false,
         "maxLength": "200",
         "minLength": 0,
         "placeHolder": "",
         "textKind": 0,
         "isPrivateInfo": false,
         "onFocus": "",
         "onBlur": "",
         "onChange": "",
         "onKeyPress": "",
         "text": "",
         "value": "",
         "labelLText": "承認しない理由",
         "labelRText": "",
         "labelLWidth": "S",
         "labelRWidth": "S",
         "labelLAlign": 2,
         "labelRAlign": 0,
         "decorationClass": "",
         "limitLength": "200",
         "countDisp": false
        }
       ],
       "controlType": "Panel",
       "width": "892px",
       "visible": true,
       "displayNone": false,
       "disabled": false,
       "accessKey": "",
       "nextFocusFieldName": "",
       "wrap": true,
       "dependencies": [],
       "float": 0,
       "toolTip": "",
       "authorityMode": 0,
       "marginLeft": "XS",
       "marginRight": "XS",
       "selectControlID": "FutanGendogakuNinteiRiyoshaFutan",
       "helpMessageID": "",
       "jpControlName": "",
       "onLoad": "",
       "title": "利用者負担",
       "marginTop": "Default",
       "marginBottom": "Default",
       "isOpen": true,
       "canOpenAndClose": false,
       "postParameterPanelNames": [
        {
         "postParameterPanelNames": "FutanGendogakuNinteiRiyoshaFutan"
        }
       ],
       "requestSettings": [],
       "hiddenInput": [],
       "onOpen": "",
       "onClose": "",
       "session": {},
       "eraseBorder": false,
       "backgroundColor": 0,
       "widthAuto": false,
       "panelDisplay": 1,
       "isGroupBox": false,
       "readOnly": false,
       "height": "Auto",
       "canPost": true
      }
     ],
     "controlType": "Panel",
     "width": "910px",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 0,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "selectControlID": "FutanGendogakuNinteiDetail",
     "helpMessageID": "",
     "jpControlName": "",
     "onLoad": "",
     "title": "詳細",
     "marginTop": "Default",
     "marginBottom": "Default",
     "isOpen": true,
     "canOpenAndClose": true,
     "postParameterPanelNames": [
      {
       "postParameterPanelNames": "FutanGendogakuNinteiDetail"
      }
     ],
     "requestSettings": [],
     "hiddenInput": [],
     "onOpen": "",
     "onClose": "",
     "session": {},
     "eraseBorder": false,
     "backgroundColor": 0,
     "widthAuto": false,
     "panelDisplay": 0,
     "isGroupBox": false,
     "readOnly": false,
     "height": "Auto",
     "canPost": true
    },
    {
     "fieldName": "btnClose",
     "items": [],
     "controlType": "Button",
     "width": "S",
     "visible": true,
     "displayNone": false,
     "disabled": false,
     "accessKey": "",
     "nextFocusFieldName": "",
     "wrap": true,
     "dependencies": [],
     "float": 1,
     "toolTip": "",
     "authorityMode": 0,
     "marginLeft": "XS",
     "marginRight": "XS",
     "selectControlID": "btnClose",
     "helpMessageID": "",
     "jpControlName": "",
     "text": "閉じる",
     "onBeforeClick": "",
     "onAfterClick": "",
     "onClick": "CloseOK",
     "appearance": 0,
     "imageFileUrl": "",
     "imageWidth": "",
     "imageHeight": "",
     "icon": 0,
     "heightTextBoxMatches": false
    }
   ],
   "controlType": "Panel",
   "width": "G10",
   "visible": true,
   "displayNone": false,
   "disabled": false,
   "accessKey": "",
   "nextFocusFieldName": "",
   "wrap": false,
   "dependencies": [],
   "float": 0,
   "toolTip": "",
   "authorityMode": 0,
   "marginLeft": "0em",
   "marginRight": "XS",
   "selectControlID": "FutanGendogakuNintei",
   "helpMessageID": "",
   "jpControlName": "",
   "onLoad": "",
   "title": "負担限度額認定",
   "marginTop": "Default",
   "marginBottom": "Default",
   "isOpen": true,
   "canOpenAndClose": true,
   "postParameterPanelNames": [
    {
     "postParameterPanelNames": "FutanGendogakuNintei"
    }
   ],
   "requestSettings": [
    {
     "eventName": "onLoad",
     "requestUrl": "dbd/db/dbd/FutanGendogakuNintei/onLoad"
    },
    {
     "eventName": "onSelect_dgFutanGendogakuNinteiList",
     "requestUrl": "dbd/db/dbd/FutanGendogakuNintei/onSelect_dgFutanGendogakuNinteiList"
    }
   ],
   "hiddenInput": [],
   "onOpen": "",
   "onClose": "",
   "session": {},
   "eraseBorder": false,
   "backgroundColor": 0,
   "widthAuto": false,
   "panelDisplay": 0,
   "isGroupBox": false,
   "readOnly": false,
   "height": "560px",
   "canPost": true
  }
 ],
 "controlType": "CommonChildDiv",
 "width": "XS",
 "visible": true,
 "displayNone": false,
 "disabled": false,
 "accessKey": "",
 "nextFocusFieldName": "",
 "wrap": false,
 "dependencies": [],
 "float": 0,
 "toolTip": "",
 "authorityMode": 0,
 "marginLeft": "0em",
 "marginRight": "0em",
 "selectControlID": "defaultLayout",
 "helpMessageID": "",
 "jpControlName": "",
 "relation": [],
 "packageName": "",
 "businessId": "DBD",
 "controlName": "FutanGendogakuNintei",
 "marginTop": "0em",
 "marginBottom": "0em",
 "originalProperty": [
  {
   "publicChildFieldName": "txtKyushochisha",
   "publicChildProperty": "visible",
   "newPropertyName": "visible_Kyusochisha"
  }
 ],
 "dataPassingForDialog": [
  {
   "key": "hihokenshaNo",
   "controlName": "txtHiddenHihokenshaNo"
  }
 ],
 "dialogOkEventNameForDialog": "CloseOK",
 "dialogCancelEventNameForDialog": "",
 "canTransferEvent": true,
 "heightForDialog": "600px",
 "firstFocusFieldName": "",
 "lastFocusFieldName": "",
 "modes": [],
 "publicEvents": [],
 "publicEventsAlias": []
}        
    }

     export module FutanGendogakuNintei {

        export class Events {

            public static onSelect_dgFutanGendogakuNinteiList(): string {
                return "onSelect_dgFutanGendogakuNinteiList";
            }

            public static CloseOK(): string {
                return "CloseOK";
            }

        }

        export class Controls {
            private _myName: string;

            public static myType(): string {
                return "FutanGendogakuNintei";
            }

            constructor(fieldName: string) {
                this._myName = fieldName;
            }

            public convFiledNameSelf(): string {
                return this._myName + "_" + DBD.FutanGendogakuNintei.Controls.myType();
            }

            public convFiledName(fieldName: string): string {
                return this._myName + "_" + DBD.FutanGendogakuNintei.Controls.myType() + "_" + fieldName;
            }

            public FutanGendogakuNintei(): UZA.Panel {
                return new UZA.Panel(this.convFiledNameSelf());
            }

            public txtHiddenHihokenshaNo(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtHiddenHihokenshaNo"));
            }

            public dgFutanGendogakuNinteiList(): UZA.DataGrid {
                return new UZA.DataGrid(this.convFiledName("dgFutanGendogakuNinteiList"));
            }

            public FutanGendogakuNinteiDetail(): UZA.Panel {
                return new UZA.Panel(this.convFiledName("FutanGendogakuNinteiDetail"));
            }

            public txtShinseiDate(): UZA.TextBoxFlexibleDate {
                return new UZA.TextBoxFlexibleDate(this.convFiledName("txtShinseiDate"));
            }

            public txtShinseiRiyu(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtShinseiRiyu"));
            }

            public FutanGendogakuNinteiRiyoshaFutan(): UZA.Panel {
                return new UZA.Panel(this.convFiledName("FutanGendogakuNinteiDetail_FutanGendogakuNinteiRiyoshaFutan"));
            }

            public txtKetteiDate(): UZA.TextBoxFlexibleDate {
                return new UZA.TextBoxFlexibleDate(this.convFiledName("txtKetteiDate"));
            }

            public txtKetteiKubun(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtKetteiKubun"));
            }

            public txtTekiyoDate(): UZA.TextBoxFlexibleDate {
                return new UZA.TextBoxFlexibleDate(this.convFiledName("txtTekiyoDate"));
            }

            public txtYukokigenDate(): UZA.TextBoxFlexibleDate {
                return new UZA.TextBoxFlexibleDate(this.convFiledName("txtYukokigenDate"));
            }

            public txtKyushochisha(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtKyushochisha"));
            }

            public txtFutanDankai(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtFutanDankai"));
            }

            public txtKyoshitsuType(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtKyoshitsuType"));
            }

            public txtKyokaiso(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtKyokaiso"));
            }

            public txtGekihenKanwa(): UZA.TextBox {
                return new UZA.TextBox(this.convFiledName("txtGekihenKanwa"));
            }

            public FutanGendogaku(): UZA.Panel {
                return new UZA.Panel(this.convFiledName("FutanGendogakuNinteiDetail_FutanGendogakuNinteiRiyoshaFutan_FutanGendogaku"));
            }

            public txtShokuhi(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtShokuhi"));
            }

            public txtUnitKoshitsu(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtUnitKoshitsu"));
            }

            public txtUnitJunKoshitsu(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtUnitJunKoshitsu"));
            }

            public txtTashoshitsu(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtTashoshitsu"));
            }

            public txtJuraigataKoshitsuTokuyo(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtJuraigataKoshitsuTokuyo"));
            }

            public txtJuraigataKoshitsuRoken(): UZA.TextBoxNum {
                return new UZA.TextBoxNum(this.convFiledName("txtJuraigataKoshitsuRoken"));
            }

            public txtFushoninRiyu(): UZA.TextBoxMultiLine {
                return new UZA.TextBoxMultiLine(this.convFiledName("txtFushoninRiyu"));
            }

            public btnClose(): UZA.Button {
                return new UZA.Button(this.convFiledName("btnClose"));
            }

        }

     }

}

