var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var DBD;
(function (DBD) {
    var HomonkaigoRiyoshaFutangakuGengaku_Design = (function (_super) {
        __extends(HomonkaigoRiyoshaFutangakuGengaku_Design, _super);
        function HomonkaigoRiyoshaFutangakuGengaku_Design($parentElement, isDesignMode, fieldName) {
            _super.call(this, $parentElement, isDesignMode, HomonkaigoRiyoshaFutangakuGengaku_Design.myLayout, fieldName);
        }
        HomonkaigoRiyoshaFutangakuGengaku_Design.prototype.registProperty = function () {
            _super.prototype.registProperty.call(this);
        };

        HomonkaigoRiyoshaFutangakuGengaku_Design.prototype.getEditablePropertyInfo = function () {
            var editablePropertyInfo = _super.prototype.getEditablePropertyInfo.call(this);

            return editablePropertyInfo;
        };
        HomonkaigoRiyoshaFutangakuGengaku_Design.myLayout = {
            "fieldName": "defaultLayout",
            "items": [
                {
                    "fieldName": "HomonkaigoRiyoshaFutangakuGengaku",
                    "items": [
                        {
                            "fieldName": "dgTaishoshaList",
                            "items": [],
                            "controlType": "DataGrid",
                            "width": "830",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "gridSetting": {
                                "rowHeight": 25,
                                "isMultiSelectable": false,
                                "isShowFooter": true,
                                "isShowFilter": false,
                                "isShowFilterButton": false,
                                "isShowRowState": false,
                                "header": {
                                    "combineColumns": [],
                                    "frozenColumn": "",
                                    "headerHeight": 1
                                },
                                "columns": [
                                    {
                                        "columnName": "申請日",
                                        "dataName": "shinseiDate",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 75,
                                        "visible": true,
                                        "cellType": 7,
                                        "cellDetails": {
                                            "cellType": 7,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "onChange": ""
                                        },
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "shinseiDate"
                                    },
                                    {
                                        "columnName": "適用日",
                                        "dataName": "tekiyoDate",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 75,
                                        "visible": true,
                                        "cellType": 7,
                                        "cellDetails": {
                                            "cellType": 7,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "onChange": ""
                                        },
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "tekiyoDate"
                                    },
                                    {
                                        "columnName": "有効期限",
                                        "dataName": "yukoKigen",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 90,
                                        "visible": true,
                                        "cellType": 7,
                                        "cellDetails": {
                                            "cellType": 7,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "onChange": ""
                                        },
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "yukoKigen"
                                    },
                                    {
                                        "columnName": "決定区分",
                                        "dataName": "ketteiKubun",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 100,
                                        "visible": true,
                                        "cellType": 0,
                                        "cellDetails": {
                                            "cellType": 0
                                        },
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "ketteiKubun"
                                    },
                                    {
                                        "columnName": "決定日",
                                        "dataName": "ketteiDate",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 75,
                                        "visible": true,
                                        "cellType": 7,
                                        "cellDetails": {
                                            "cellType": 7,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "onChange": ""
                                        },
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "ketteiDate"
                                    },
                                    {
                                        "columnName": "法別区分",
                                        "dataName": "hobetsuKubun",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 100,
                                        "visible": true,
                                        "cellType": 0,
                                        "cellDetails": null,
                                        "align": 0,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "hobetsuKubun"
                                    },
                                    {
                                        "columnName": "給付率",
                                        "dataName": "kyufuRitsu",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 75,
                                        "visible": true,
                                        "cellType": 0,
                                        "cellDetails": null,
                                        "align": 2,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "kyufuRitsu"
                                    },
                                    {
                                        "columnName": "公費<br>受給者番号",
                                        "dataName": "kohiJukyushaNo",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 120,
                                        "visible": true,
                                        "cellType": 0,
                                        "cellDetails": null,
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "kohiJukyushaNo"
                                    },
                                    {
                                        "columnName": "障害者手帳<br>番号",
                                        "dataName": "shogaishaTechoNo",
                                        "toolTip": "",
                                        "bgColor": 0,
                                        "width": 120,
                                        "visible": true,
                                        "cellType": 0,
                                        "cellDetails": null,
                                        "align": 1,
                                        "resize": true,
                                        "isPrivateInfo": false,
                                        "sortKey": "shogaishaTechoNo"
                                    }
                                ]
                            },
                            "height": "185",
                            "onSort": "",
                            "onSelect": "",
                            "onSelectByDblClick": "",
                            "onOnlyRow": "",
                            "onNoRow": "",
                            "onMultiRows": "",
                            "dataSource": [],
                            "sortOrder": "tekiyoKaishiDate",
                            "isAscending": true,
                            "filterList": [],
                            "activeRowId": -1
                        },
                        {
                            "fieldName": "HomonkaigoRiyoshaFutangakuGengakuDetail",
                            "items": [
                                {
                                    "fieldName": "lblShinseiDate",
                                    "items": [],
                                    "controlType": "Label",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "align": 2,
                                    "text": "申請日",
                                    "isPrivateInfo": false
                                },
                                {
                                    "fieldName": "txtShinseiDate",
                                    "items": [],
                                    "controlType": "TextBoxDate",
                                    "width": "75",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "readOnly": true,
                                    "placeHolder": "",
                                    "textKind": 0,
                                    "isPassword": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "ymdKubun": 2,
                                    "displayFormat": 0,
                                    "value": "",
                                    "permitCharactor": "./_-"
                                },
                                {
                                    "fieldName": "lblShinseiRiyu",
                                    "items": [],
                                    "controlType": "Label",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "align": 2,
                                    "text": "申請理由",
                                    "isPrivateInfo": false
                                },
                                {
                                    "fieldName": "txtShinseiRiyu",
                                    "items": [],
                                    "controlType": "TextBox",
                                    "width": "L",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "readOnly": true,
                                    "placeHolder": "",
                                    "textKind": 0,
                                    "isPassword": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "value": "",
                                    "maxLength": 1000000000000,
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "isComboBox": false,
                                    "suggest": [],
                                    "permitCharactor": ""
                                },
                                {
                                    "fieldName": "lblHobetsuKubun",
                                    "items": [],
                                    "controlType": "Label",
                                    "width": "S",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "align": 2,
                                    "text": "法別区分",
                                    "isPrivateInfo": false
                                },
                                {
                                    "fieldName": "txtHobetsuKubun",
                                    "items": [],
                                    "controlType": "TextBox",
                                    "width": "75",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "readOnly": true,
                                    "placeHolder": "",
                                    "textKind": 0,
                                    "isPassword": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "S",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "value": "",
                                    "maxLength": 1000000000000,
                                    "minLength": 0,
                                    "textAlign": 0,
                                    "isComboBox": false,
                                    "suggest": [],
                                    "permitCharactor": ""
                                },
                                {
                                    "fieldName": "ShogaishaTechoDetail",
                                    "items": [
                                        {
                                            "fieldName": "chkShogakushaTechoUmu",
                                            "items": [],
                                            "controlType": "RadioButton",
                                            "width": "S",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "dataSource": [
                                                {
                                                    "key": "0",
                                                    "value": "無"
                                                },
                                                {
                                                    "key": "1",
                                                    "value": "有"
                                                }
                                            ],
                                            "required": false,
                                            "onChange": "",
                                            "labelLText": "",
                                            "labelLWidth": "S",
                                            "labelLAlign": 2,
                                            "selectedItem": "0",
                                            "onClick": "",
                                            "newLineItemNumber": 2,
                                            "spaceSize": 1
                                        },
                                        {
                                            "fieldName": "lblShogaishaTechoTokyu",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "XS",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "等級",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtShogaishaTechoTokyu",
                                            "items": [],
                                            "controlType": "TextBox",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 0,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "permitCharactor": ""
                                        },
                                        {
                                            "fieldName": "lblShogaishaTechoNo",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "XS",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "番号",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtShogaishaTechoNo",
                                            "items": [],
                                            "controlType": "TextBoxCode",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 2,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 0,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "permitCharactor": "",
                                            "formatLength": 1
                                        }
                                    ],
                                    "controlType": "Panel",
                                    "width": "200",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "3",
                                    "marginRight": "XS",
                                    "onLoad": "",
                                    "title": "障害者手帳",
                                    "marginTop": "Default",
                                    "marginBottom": "Default",
                                    "isOpen": true,
                                    "canOpenAndClose": false,
                                    "postParameterPanelNames": [
                                        {
                                            "postParameterPanelNames": "ShogaishaTechoDetail"
                                        }
                                    ],
                                    "requestSettings": [],
                                    "hiddenInput": [],
                                    "onOpen": "",
                                    "onClose": "",
                                    "session": {},
                                    "eraseBorderTop": false,
                                    "eraseBorderBottom": false,
                                    "eraseBorderRight": false,
                                    "eraseBorderLeft": false,
                                    "backgroundColor": 0,
                                    "widthAuto": true,
                                    "isGroupBox": true
                                },
                                {
                                    "fieldName": "HomonkaigoRiyoshaFutangakuGengakuRiyoshaFutan",
                                    "items": [
                                        {
                                            "fieldName": "lblKetteiDate",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "120",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": true,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "決定日",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtKetteiDate",
                                            "items": [],
                                            "controlType": "TextBoxDate",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "value": "",
                                            "permitCharactor": "./_-"
                                        },
                                        {
                                            "fieldName": "lblKetteiKubun",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "105",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "決定区分",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtKetteiKubun",
                                            "items": [],
                                            "controlType": "TextBox",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 0,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "permitCharactor": ""
                                        },
                                        {
                                            "fieldName": "lblTekiyoDate",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "70",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "適用日",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtTekiyoDate",
                                            "items": [],
                                            "controlType": "TextBoxDate",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "value": "",
                                            "permitCharactor": "./_-"
                                        },
                                        {
                                            "fieldName": "lblYukokigenDate",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "70",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "有効期限",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtYukokigenDate",
                                            "items": [],
                                            "controlType": "TextBoxDate",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "ymdKubun": 2,
                                            "displayFormat": 0,
                                            "value": "",
                                            "permitCharactor": "./_-"
                                        },
                                        {
                                            "fieldName": "lblKyufuRitsu",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "120",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": true,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "給付率",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtKyufuRitsu",
                                            "items": [],
                                            "controlType": "TextBoxNum",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 2,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 2,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "maxValue": 1.7976931348623157e+308,
                                            "minValue": 0,
                                            "isCurrency": false,
                                            "isComma": false,
                                            "decimalPointLength": 0,
                                            "permitCharactor": "+-,.\\"
                                        },
                                        {
                                            "fieldName": "lblFushoninRiyu",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "120",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": true,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "承認しない理由",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtHishoninRiyu",
                                            "items": [],
                                            "controlType": "TextBoxMultiLine",
                                            "width": "650",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "height": "45",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 0,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": "200",
                                            "minLength": 0,
                                            "limitLength": "200",
                                            "countDisp": false
                                        },
                                        {
                                            "fieldName": "lblKohiFutanshaNo",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "120",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": true,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "公費負担者番号",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtKohiFutanshaNo",
                                            "items": [],
                                            "controlType": "TextBoxCode",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 2,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 0,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "permitCharactor": "",
                                            "formatLength": 1
                                        },
                                        {
                                            "fieldName": "lblKohiJukyushaNo",
                                            "items": [],
                                            "controlType": "Label",
                                            "width": "105",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "align": 2,
                                            "text": "公費受給者番号",
                                            "isPrivateInfo": false
                                        },
                                        {
                                            "fieldName": "txtKohiJukyushaNo",
                                            "items": [],
                                            "controlType": "TextBoxCode",
                                            "width": "75",
                                            "visible": true,
                                            "displayNone": false,
                                            "disabled": false,
                                            "accessKey": "",
                                            "nextFocusFieldName": "",
                                            "wrap": false,
                                            "dependencies": [],
                                            "float": 0,
                                            "toolTip": "",
                                            "authorityMode": 0,
                                            "marginLeft": "XS",
                                            "marginRight": "XS",
                                            "required": false,
                                            "text": "",
                                            "isPrivateInfo": false,
                                            "readOnly": true,
                                            "placeHolder": "",
                                            "textKind": 2,
                                            "isPassword": false,
                                            "onFocus": "",
                                            "onBlur": "",
                                            "onChange": "",
                                            "onKeyPress": "",
                                            "labelLText": "",
                                            "labelRText": "",
                                            "labelLWidth": "S",
                                            "labelRWidth": "S",
                                            "labelLAlign": 2,
                                            "labelRAlign": 0,
                                            "value": "",
                                            "maxLength": 1000000000000,
                                            "minLength": 0,
                                            "textAlign": 0,
                                            "isComboBox": false,
                                            "suggest": [],
                                            "permitCharactor": "",
                                            "formatLength": 1
                                        }
                                    ],
                                    "controlType": "Panel",
                                    "width": "810",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": true,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "onLoad": "",
                                    "title": "利用者負担",
                                    "marginTop": "Default",
                                    "marginBottom": "Default",
                                    "isOpen": true,
                                    "canOpenAndClose": false,
                                    "postParameterPanelNames": [
                                        {
                                            "postParameterPanelNames": "HomonkaigoRiyoshaFutangakuGengakuRiyoshaFutan"
                                        }
                                    ],
                                    "requestSettings": [],
                                    "hiddenInput": [],
                                    "onOpen": "",
                                    "onClose": "",
                                    "session": {},
                                    "eraseBorderTop": false,
                                    "eraseBorderBottom": false,
                                    "eraseBorderRight": false,
                                    "eraseBorderLeft": false,
                                    "backgroundColor": 0,
                                    "widthAuto": false,
                                    "isGroupBox": true
                                }
                            ],
                            "controlType": "Panel",
                            "width": "830",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "onLoad": "",
                            "title": "詳細",
                            "marginTop": "Default",
                            "marginBottom": "Default",
                            "isOpen": true,
                            "canOpenAndClose": true,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "HomonkaigoRiyoshaFutangakuGengakuDetail"
                                }
                            ],
                            "requestSettings": [],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorderTop": false,
                            "eraseBorderBottom": false,
                            "eraseBorderRight": false,
                            "eraseBorderLeft": false,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "isGroupBox": false
                        }
                    ],
                    "controlType": "Panel",
                    "width": "M",
                    "visible": true,
                    "displayNone": false,
                    "disabled": false,
                    "accessKey": "",
                    "nextFocusFieldName": "",
                    "wrap": false,
                    "dependencies": [],
                    "float": 0,
                    "toolTip": "",
                    "authorityMode": 0,
                    "marginLeft": "XS",
                    "marginRight": "XS",
                    "onLoad": "",
                    "title": "訪問介護利用者負担額減免情報",
                    "marginTop": "Default",
                    "marginBottom": "Default",
                    "isOpen": true,
                    "canOpenAndClose": true,
                    "postParameterPanelNames": [
                        {
                            "postParameterPanelNames": "HomonkaigoRiyoshaFutangakuGengaku"
                        }
                    ],
                    "requestSettings": [],
                    "hiddenInput": [],
                    "onOpen": "",
                    "onClose": "",
                    "session": {},
                    "eraseBorderTop": false,
                    "eraseBorderBottom": false,
                    "eraseBorderRight": false,
                    "eraseBorderLeft": false,
                    "backgroundColor": 0,
                    "widthAuto": true,
                    "isGroupBox": false
                }
            ],
            "controlType": "CommonChildDiv",
            "width": "XS",
            "visible": true,
            "displayNone": false,
            "disabled": false,
            "accessKey": "",
            "nextFocusFieldName": "",
            "wrap": false,
            "dependencies": [],
            "float": 0,
            "toolTip": "",
            "authorityMode": 0,
            "marginLeft": 0,
            "marginRight": 0,
            "relation": [],
            "businessId": "DBD",
            "controlName": "HomonkaigoRiyoshaFutangakuGengaku",
            "marginTop": 0,
            "marginBottom": 0,
            "originalProperty": [],
            "dataPassingForDialog": [],
            "dialogOkEventNameForDialog": "",
            "dialogCancelEventNameForDialog": ""
        };
        return HomonkaigoRiyoshaFutangakuGengaku_Design;
    })(Uz.CommonChildDiv);
    DBD.HomonkaigoRiyoshaFutangakuGengaku_Design = HomonkaigoRiyoshaFutangakuGengaku_Design;
})(DBD || (DBD = {}));
