/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbu.definition.core.hihokenshashochohyo;

import java.util.List;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.RString;

/**
 * 被保険者証帳票Entity作成クラスです。
 *
 * @reamsid_L DBU-0490-021 zhangzhiming
 */
@lombok.Getter
@lombok.Setter
@SuppressWarnings("PMD.UnusedPrivateField")
public class HihokenshashoChohyoParameter {

    private FlexibleDate kofuYMD;
    private RString gyoseiku;
    private RString yubinno;
    private boolean umareflg;
    private RString hihokana;
    private RString seibetsu;
    private YubinNo hihokenshaNo;
    private RString shikibetsuCode;
    private RString shichosonCode;
    private RString updateTimestamp;
    private RString insertTimestamp;
    private RString idoYMD;
    private RString edaNo;
    private RString idoJiyuCode;
    private RString shikakuShutokuJiyuCode;
    private RString shikakuShutokuYMD;
    private RString shikakuShutokuTodokedeYMD;
    private RString ichigoShikakuShutokuYMD;
    private RString hihokennshaKubunCode;
    private RString shikakuSoshitsuJiyuCode;
    private RString shikakuSoshitsuYMD;
    private RString shikakuSoshitsuTodokedeYMD;
    private RString shikakuHenkoJiyuCode;
    private RString shikakuHenkoYMD;
    private RString shikakuHenkoTodokedeYMD;
    private RString jushochitokureiTekiyoJiyuCode;
    private RString jushochitokureiTekiyoYMD;
    private RString jushochitokureiTodokedeYMD;
    private RString jushochitokureiKaijoJiyuCode;
    private RString jushochitokureiKaijoYMD;
    private RString jushochiKaijoTodokedeYMD;
    private RString jushochiTokureiFlag;
    private RString koikinaiJushochiTokureiFlag;
    private RString koikinaiShichosonCode;
    private RString kyuShichosonCode;
    private RString logicalDeletedFlag;
    private RString syouRiTimestamp;
    private RString daichoShubetsu;
    private RString nyushoShoriYMD;
    private List<NyushoShisetsuParameter> nyushoParameter;
    private RString taishoShoriYMD;
    private RString roomKigoNo;
    private RString rirekiNo;
    private RString shinseishoKanriNo;
    private RString shinseiJokyoKubun;
    private RString shishoCode;
    private RString chokkinFlag;
    private RString jukyuShinseiJiyu;
    private RString shinseiRiyu;
    private RString shinseishaKankeiCode;
    private RString homninKankei;
    private RString jukyuShinseiYMD;
    private RString nigoTokuteiShippeiCode;
    private RString shinsakaiIraiYMD;
    private RString yokaigoJotaiKubunCode;
    private FlexibleDate ninteiYukoKikanKaishiYMD;
    private FlexibleDate ninteiYukoKikanShuryoYMD;
    private FlexibleDate ninteiYMD;
    private RString shiteiServiceShurui01;
    private RString shiteiServiceShurui02;
    private RString shiteiServiceShurui03;
    private RString shiteiServiceShurui04;
    private RString shiteiServiceShurui05;
    private RString shiteiServiceShurui06;
    private RString shiteiServiceShurui07;
    private RString shiteiServiceShurui08;
    private RString shiteiServiceShurui09;
    private RString shiteiServiceShurui10;
    private RString shiteiServiceShurui11;
    private RString shiteiServiceShurui12;
    private RString shiteiServiceShurui13;
    private RString shiteiServiceShurui14;
    private RString shiteiServiceShurui15;
    private RString shiteiServiceShurui16;
    private RString shiteiServiceShurui17;
    private RString shiteiServiceShurui18;
    private RString shiteiServiceShurui19;
    private RString shiteiServiceShurui20;
    private RString shiteiServiceShurui21;
    private RString shiteiServiceShurui22;
    private RString shiteiServiceShurui23;
    private RString shiteiServiceShurui24;
    private RString shiteiServiceShurui25;
    private RString shiteiServiceShurui26;
    private RString shiteiServiceShurui27;
    private RString shiteiServiceShurui28;
    private RString shiteiServiceShurui29;
    private RString shiteiServiceShurui30;
    private RString soshitsuYMD;
    private RString chokkinIdoYMD;
    private RString chokkinIdoJiyuCode;
    private RString yukoMukoKubun;
    private RString dataKubun;
    private RString remban;
    private RString idoRiyu;
    private RString shinseishoKubun;
    private RString sakujoJiyuCode;
    private RString yoshienshaNinteiShinseiFlag;
    private RString shikyuGendoTanisu;
    private FlexibleDate shikyuGendoKaishiYMD;
    private FlexibleDate shikyuGendoShuryoYMD;
    private RString tankiSikyuGendoNissu;
    private RString tankiShikyuGendoKaishiYMD;
    private RString tankiShikyuGendoShuryoYMD;
    private RString toshoNinteiYukoKaishiYMD;
    private RString toshoNinteiYukoShuryoYMD;
    private RString jukyuShikakuShomeishoHakkoYMD1;
    private RString jukyuShikakuShomeishoHakkoYMD2;
    private RString shindanMeireishoHakkoYMD;
    private RString nigoShinseiTsuchishoHakkoYMD;
    private RString ninteiKekkaTsuchishoHakkoYMD;
    private RString kubunHenkoTsuchishoHakkoYMD;
    private RString serviceHenkoTsuchishoHakkoYMD;
    private RString ninteiKyakkaTsuchishoHakkoYMD;
    private RString ninteiTorikeshiHakkoYMD;
    private RString shikakuShutokuMaeShinseiFlag;
    private RString kyuSochishaFlag;
    private RString nijiHanteiYMD;
    private RString nijiHanteiJotaiKubunCode;
    private RString nijiHanteiNinteiYukoKikan;
    private RString nijiHanteiNinteiYukoKaishiYMD;
    private RString nijiHanteiNinteiYukoShuryoYMD;
    private RString shinsakaiKaisaiNo;
    private RString shinsakaiIken;
    private RString ichijiHanteiKekkaHenkoRiyu;
    private RString yokaigoJotaizoReiCode;
    private RString ninteishinsakaiIkenShurui;
    private RString shinsakaiMemo;
    private RString nijiHanteiKekkaInputHoho;
    private RString nijiHanteiKekkaInputYMD;
    private RString shoKisaiHokenshaNo;
    private RString kanriKubun;
    private RString torokuKubun;
    private RString shuryoKubun;
    private RString yokoku_TorokuYMD;
    private RString sashitome_IraiJuriYMD;
    private RString yokoku_TsuchiHakkoYMD;
    private RString yokoku_TsuchiSaiHakkoFlag;
    private RString bemmei_TeishutsuYMD;
    private RString bemmei_UketsukeYMD;
    private RString bemmei_RiyuCode;
    private RString bemmei_ShinsaKetteiYMD;
    private RString bemmei_ShinsaKekkaKubun;
    private RString shokan_KetteiYMD;
    private RString shokan_TsuchiHakkoYMD;
    private RString shokan_TsuchiSaiHakkoFlag;
    private RString hihokenshaShoTeishutsuYMD;
    private RString sashitome_Flag;
    private RString sashitome_KetteiYMD;
    private RString sashitome_KaijoYMD;
    private RString gemmen_KetteiYMD;
    private RString gemmen_TsuchiHakkoYMD;
    private RString gemmen_TsuchiSaiHakkoFlag;
    private RString kyufuRitsu;
    private RString shuryoShinsei_UketsukeYMD;
    private RString shuryoShinsei_YMD;
    private RString shuryoShinsei_RiyuCode;
    private RString shuryoShinsei_ShinsaKetteiYMD;
    private RString shuryoShinsei_ShinsaKekkaKubun;
    private RString mukoKubun;
    private List<TaishoNoParameter> taishoNoParameter;
    private RString todokedeKubun;
    private List<FlexibleDate> todokedeYMD;
    private RString todokedeshaShimei;
    private RString todokedeshaShimeiKana;
    private RString todokedeshaYubinNo;
    private RString todokedeshaJusho;
    private RString todokedeshaTelNo;
    private RString todokedeshaKankeiKubun;
    private RString zanteiKubun;
    private RString itakusakiJigyoshaNo;
    private RString atenaShimei;
    private FlexibleDate seinengappiYMD;
    private RString juminShubetsuCode;
    private RString juminJotaiCode;
    private RString kannaiKangaiKubun;
    private RString jusho;
    private RString banchi;
    private RString katagaki;
    private RString shinseiJokyoFlg;
    private RString jukyushaKubun;
    private RString sort;
    private RString page;
}
