var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
var DBB;
(function (DBB) {
    var ShunoJoho_Design = (function (_super) {
        __extends(ShunoJoho_Design, _super);
        function ShunoJoho_Design($parentElement, isDesignMode, fieldName) {
            _super.call(this, $parentElement, isDesignMode, ShunoJoho_Design.myLayout, fieldName);
        }
        ShunoJoho_Design.prototype.registProperty = function () {
            _super.prototype.registProperty.call(this);
        };

        ShunoJoho_Design.prototype.getEditablePropertyInfo = function () {
            var editablePropertyInfo = _super.prototype.getEditablePropertyInfo.call(this);

            return editablePropertyInfo;
        };
        ShunoJoho_Design.myLayout = {
            "fieldName": "defaultLayout",
            "items": [
                {
                    "fieldName": "ShunoJoho",
                    "items": [
                        {
                            "fieldName": "txtChoteiNendo",
                            "items": [],
                            "controlType": "TextBox",
                            "width": "40",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "txtChoteiNendo_core",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "readOnly": true,
                            "required": false,
                            "text": "",
                            "isPrivateInfo": false,
                            "decorationClass": "",
                            "maxLength": 100000000,
                            "minLength": 0,
                            "textAlign": 0,
                            "placeHolder": "平26",
                            "textKind": 0,
                            "isPassword": false,
                            "isComboBox": false,
                            "onFocus": "",
                            "onBlur": "",
                            "onChange": "",
                            "onKeyPress": "",
                            "suggest": [],
                            "value": "",
                            "labelLText": "調定年度",
                            "labelRText": "",
                            "labelLWidth": "70",
                            "labelRWidth": "S",
                            "labelLAlign": 2,
                            "labelRAlign": 0,
                            "permitCharactor": ""
                        },
                        {
                            "fieldName": "txtFukaNendo",
                            "items": [],
                            "controlType": "TextBox",
                            "width": "40",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "txtFukaNendo_core",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "readOnly": true,
                            "required": false,
                            "text": "",
                            "isPrivateInfo": false,
                            "decorationClass": "",
                            "maxLength": 100000000,
                            "minLength": 0,
                            "textAlign": 0,
                            "placeHolder": "平26",
                            "textKind": 0,
                            "isPassword": false,
                            "isComboBox": false,
                            "onFocus": "",
                            "onBlur": "",
                            "onChange": "",
                            "onKeyPress": "",
                            "suggest": [],
                            "value": "",
                            "labelLText": "賦課年度",
                            "labelRText": "",
                            "labelLWidth": "88",
                            "labelRWidth": "S",
                            "labelLAlign": 2,
                            "labelRAlign": 0,
                            "permitCharactor": ""
                        },
                        {
                            "fieldName": "txtTsuchiNo",
                            "items": [],
                            "controlType": "TextBoxCode",
                            "width": "130",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "txtTsuchiNo_core",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "readOnly": true,
                            "required": false,
                            "text": "",
                            "isPrivateInfo": false,
                            "decorationClass": "",
                            "maxLength": 100000000,
                            "minLength": 0,
                            "textAlign": 0,
                            "placeHolder": "1234567890123456",
                            "textKind": 2,
                            "isPassword": false,
                            "isComboBox": false,
                            "onFocus": "",
                            "onBlur": "",
                            "onChange": "",
                            "onKeyPress": "",
                            "suggest": [],
                            "value": "",
                            "labelLText": "通知書番号",
                            "labelRText": "",
                            "labelLWidth": "100",
                            "labelRWidth": "S",
                            "labelLAlign": 2,
                            "labelRAlign": 0,
                            "permitCharactor": "",
                            "formatLength": 1
                        },
                        {
                            "fieldName": "ddlChoteiNendo",
                            "items": [],
                            "controlType": "DropDownList",
                            "width": "60",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "ddlChoteiNendo_core",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "readOnly": false,
                            "onFocus": "",
                            "onBlur": "",
                            "onChange": "",
                            "labelLText": "調定年度",
                            "labelRText": "",
                            "labelLWidth": "70",
                            "labelRWidth": "S",
                            "labelLAlign": 2,
                            "labelRAlign": 0,
                            "selectedItem": "key0",
                            "dataSource": [
                                {
                                    "key": "key0",
                                    "value": "平26"
                                },
                                {
                                    "key": "key1",
                                    "value": "平25"
                                },
                                {
                                    "key": "key2",
                                    "value": "平24"
                                }
                            ]
                        },
                        {
                            "fieldName": "ddlFukaNendo",
                            "items": [],
                            "controlType": "DropDownList",
                            "width": "60",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "ddlFukaNendo_core",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "readOnly": false,
                            "onFocus": "",
                            "onBlur": "",
                            "onChange": "",
                            "labelLText": "賦課年度",
                            "labelRText": "",
                            "labelLWidth": "70",
                            "labelRWidth": "S",
                            "labelLAlign": 2,
                            "labelRAlign": 0,
                            "selectedItem": "key0",
                            "dataSource": [
                                {
                                    "key": "key0",
                                    "value": "平26"
                                },
                                {
                                    "key": "key1",
                                    "value": "平25"
                                },
                                {
                                    "key": "key2",
                                    "value": "平24"
                                }
                            ]
                        },
                        {
                            "fieldName": "btnNendoChange",
                            "items": [],
                            "controlType": "Button",
                            "width": "S",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": false,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "btnNendoChange",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "text": "年度を変更する",
                            "onClick": "",
                            "appearance": 0,
                            "imageFileUrl": "",
                            "imageWidth": "",
                            "imageHeight": "",
                            "icon": 0,
                            "heightTextBoxMatches": false
                        },
                        {
                            "fieldName": "ShunoJohoTokucho",
                            "items": [
                                {
                                    "fieldName": "dgTokucho",
                                    "items": [],
                                    "controlType": "DataGrid",
                                    "width": "850",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "dgTokucho",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": false,
                                    "height": "Auto",
                                    "dataSource": [],
                                    "gridSetting": {
                                        "rowHeight": 25,
                                        "isMultiSelectable": false,
                                        "isShowHeader": true,
                                        "isShowFooter": true,
                                        "isShowFilter": false,
                                        "isShowFilterButton": false,
                                        "isShowRowState": false,
                                        "isShowSelectButtonColumn": false,
                                        "isShowModifyButtonColumn": false,
                                        "isShowDeleteButtonColumn": false,
                                        "limitRowCount": 0,
                                        "selectedRowCount": 0,
                                        "header": {
                                            "combineColumns": [],
                                            "frozenColumn": "",
                                            "headerHeight": 0
                                        },
                                        "columns": [
                                            {
                                                "columnName": "期",
                                                "dataName": "txtKi",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 50,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtKi"
                                            },
                                            {
                                                "columnName": "調定額",
                                                "dataName": "txtChoteiGaku",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtChoteiGaku"
                                            },
                                            {
                                                "columnName": "収入額",
                                                "dataName": "txtShunyuGaku",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtShunyuGaku"
                                            },
                                            {
                                                "columnName": "収入日",
                                                "dataName": "txtShunyuYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtShunyuYMD"
                                            },
                                            {
                                                "columnName": "領収日",
                                                "dataName": "txtRyosyuYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtRyosyuYMD"
                                            },
                                            {
                                                "columnName": "督促手数料",
                                                "dataName": "txtTokusokuTesuryo",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtTokusokuTesuryo"
                                            },
                                            {
                                                "columnName": "延滞金",
                                                "dataName": "txtEntaikin",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtEntaikin"
                                            },
                                            {
                                                "columnName": "調定日",
                                                "dataName": "txtChoteiYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtChoteiYMD"
                                            },
                                            {
                                                "columnName": "納期限",
                                                "dataName": "txtNokigen",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtNokigen"
                                            }
                                        ]
                                    },
                                    "onSort": "",
                                    "onSelect": "",
                                    "onSelectByDblClick": "",
                                    "onSelectBySelectButton": "",
                                    "onSelectByModifyButton": "",
                                    "onSelectByDeleteButton": "",
                                    "onOnlyRow": "",
                                    "onNoRow": "",
                                    "onMultiRows": "",
                                    "sortOrder": "defaultDataName3",
                                    "isAscending": true,
                                    "filterList": [],
                                    "activeRowId": -1
                                },
                                {
                                    "fieldName": "txtTokuChoteiGeoukei",
                                    "items": [],
                                    "controlType": "TextBoxNum",
                                    "width": "90",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "0",
                                    "selectControlID": "txtTokuChoteiGeoukei_core",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": true,
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "decorationClass": "",
                                    "maxLength": "16",
                                    "minLength": 0,
                                    "textAlign": 2,
                                    "placeHolder": "12,345,678",
                                    "textKind": 2,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "suggest": [],
                                    "value": "",
                                    "labelLText": "合計",
                                    "labelRText": "",
                                    "labelLWidth": "50",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "permitCharactor": "+-,.\\",
                                    "maxValue": 1.7976931348623157e+308,
                                    "minValue": 0,
                                    "isCurrency": false,
                                    "isComma": false,
                                    "decimalPointLength": 0
                                },
                                {
                                    "fieldName": "txtTokuShunyuGeoukei",
                                    "items": [],
                                    "controlType": "TextBoxNum",
                                    "width": "90",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtTokuShunyuGeoukei_core",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": true,
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "decorationClass": "",
                                    "maxLength": "16",
                                    "minLength": 0,
                                    "textAlign": 2,
                                    "placeHolder": "12,345,678",
                                    "textKind": 2,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "suggest": [],
                                    "value": "",
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "50",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "permitCharactor": "+-,.\\",
                                    "maxValue": 1.7976931348623157e+308,
                                    "minValue": 0,
                                    "isCurrency": false,
                                    "isComma": false,
                                    "decimalPointLength": 0
                                }
                            ],
                            "controlType": "Panel",
                            "width": "G10",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "ShunoJohoTokucho",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "onLoad": "",
                            "title": "特別徴収",
                            "marginTop": "Default",
                            "marginBottom": "Default",
                            "isOpen": true,
                            "canOpenAndClose": true,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "ShunoJohoTokucho"
                                }
                            ],
                            "requestSettings": [],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorder": false,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "panelDisplay": 0,
                            "isGroupBox": false,
                            "readOnly": false,
                            "height": "Auto",
                            "focusPositionID": "ShunoJoho_panel_body_area"
                        },
                        {
                            "fieldName": "ShunoJohoFucho",
                            "items": [
                                {
                                    "fieldName": "dgFucho",
                                    "items": [],
                                    "controlType": "DataGrid",
                                    "width": "850",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "dgFucho",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": false,
                                    "height": "Auto",
                                    "dataSource": [],
                                    "gridSetting": {
                                        "rowHeight": 25,
                                        "isMultiSelectable": false,
                                        "isShowHeader": true,
                                        "isShowFooter": true,
                                        "isShowFilter": false,
                                        "isShowFilterButton": false,
                                        "isShowRowState": false,
                                        "isShowSelectButtonColumn": false,
                                        "isShowModifyButtonColumn": false,
                                        "isShowDeleteButtonColumn": false,
                                        "limitRowCount": 0,
                                        "selectedRowCount": 0,
                                        "header": {
                                            "combineColumns": [],
                                            "frozenColumn": "",
                                            "headerHeight": 0
                                        },
                                        "columns": [
                                            {
                                                "columnName": "期",
                                                "dataName": "txtKi",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 50,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtKi"
                                            },
                                            {
                                                "columnName": "調定額",
                                                "dataName": "txtChoteiGaku",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtChoteiGaku"
                                            },
                                            {
                                                "columnName": "収入額",
                                                "dataName": "txtShunyuGaku",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtShunyuGaku"
                                            },
                                            {
                                                "columnName": "収入日",
                                                "dataName": "txtShunyuYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtShunyuYMD"
                                            },
                                            {
                                                "columnName": "領収日",
                                                "dataName": "txtRyosyuYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": {
                                                    "cellType": 0
                                                },
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtRyosyuYMD"
                                            },
                                            {
                                                "columnName": "督促手数料",
                                                "dataName": "txtTokusokuTesuryo",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtTokusokuTesuryo"
                                            },
                                            {
                                                "columnName": "延滞金",
                                                "dataName": "txtEntaikin",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 2,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtEntaikin"
                                            },
                                            {
                                                "columnName": "調定日",
                                                "dataName": "txtChoteiYMD",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtChoteiYMD"
                                            },
                                            {
                                                "columnName": "納期限",
                                                "dataName": "txtNokigen",
                                                "toolTip": "",
                                                "bgColor": 0,
                                                "width": 100,
                                                "visible": true,
                                                "cellType": 0,
                                                "cellDetails": null,
                                                "align": 1,
                                                "resize": false,
                                                "isPrivateInfo": false,
                                                "sortKey": "txtNokigen"
                                            }
                                        ]
                                    },
                                    "onSort": "",
                                    "onSelect": "",
                                    "onSelectByDblClick": "",
                                    "onSelectBySelectButton": "",
                                    "onSelectByModifyButton": "",
                                    "onSelectByDeleteButton": "",
                                    "onOnlyRow": "",
                                    "onNoRow": "",
                                    "onMultiRows": "",
                                    "sortOrder": "defaultDataName3",
                                    "isAscending": true,
                                    "filterList": [],
                                    "activeRowId": -1
                                },
                                {
                                    "fieldName": "txtFuChoteiGeoukei",
                                    "items": [],
                                    "controlType": "TextBoxNum",
                                    "width": "90",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "0",
                                    "selectControlID": "txtFuChoteiGeoukei_core",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": true,
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "decorationClass": "",
                                    "maxLength": "16",
                                    "minLength": 0,
                                    "textAlign": 2,
                                    "placeHolder": "12,345,678",
                                    "textKind": 2,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "suggest": [],
                                    "value": "",
                                    "labelLText": "合計",
                                    "labelRText": "",
                                    "labelLWidth": "50",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "permitCharactor": "+-,.\\",
                                    "maxValue": 1.7976931348623157e+308,
                                    "minValue": 0,
                                    "isCurrency": false,
                                    "isComma": false,
                                    "decimalPointLength": 0
                                },
                                {
                                    "fieldName": "txtFuShunyuGeoukei",
                                    "items": [],
                                    "controlType": "TextBoxNum",
                                    "width": "90",
                                    "visible": true,
                                    "displayNone": false,
                                    "disabled": false,
                                    "accessKey": "",
                                    "nextFocusFieldName": "",
                                    "wrap": false,
                                    "dependencies": [],
                                    "float": 0,
                                    "toolTip": "",
                                    "authorityMode": 0,
                                    "marginLeft": "XS",
                                    "marginRight": "XS",
                                    "selectControlID": "txtFuShunyuGeoukei_core",
                                    "helpMessageID": "",
                                    "jpControlName": "",
                                    "readOnly": true,
                                    "required": false,
                                    "text": "",
                                    "isPrivateInfo": false,
                                    "decorationClass": "",
                                    "maxLength": "16",
                                    "minLength": 0,
                                    "textAlign": 2,
                                    "placeHolder": "12,345,678",
                                    "textKind": 2,
                                    "isPassword": false,
                                    "isComboBox": false,
                                    "onFocus": "",
                                    "onBlur": "",
                                    "onChange": "",
                                    "onKeyPress": "",
                                    "suggest": [],
                                    "value": "",
                                    "labelLText": "",
                                    "labelRText": "",
                                    "labelLWidth": "50",
                                    "labelRWidth": "S",
                                    "labelLAlign": 2,
                                    "labelRAlign": 0,
                                    "permitCharactor": "+-,.\\",
                                    "maxValue": 1.7976931348623157e+308,
                                    "minValue": 0,
                                    "isCurrency": false,
                                    "isComma": false,
                                    "decimalPointLength": 0
                                }
                            ],
                            "controlType": "Panel",
                            "width": "G10",
                            "visible": true,
                            "displayNone": false,
                            "disabled": false,
                            "accessKey": "",
                            "nextFocusFieldName": "",
                            "wrap": true,
                            "dependencies": [],
                            "float": 0,
                            "toolTip": "",
                            "authorityMode": 0,
                            "marginLeft": "XS",
                            "marginRight": "XS",
                            "selectControlID": "ShunoJohoFucho",
                            "helpMessageID": "",
                            "jpControlName": "",
                            "onLoad": "",
                            "title": "普通徴収",
                            "marginTop": "Default",
                            "marginBottom": "Default",
                            "isOpen": true,
                            "canOpenAndClose": true,
                            "postParameterPanelNames": [
                                {
                                    "postParameterPanelNames": "ShunoJohoTokucho"
                                }
                            ],
                            "requestSettings": [],
                            "hiddenInput": [],
                            "onOpen": "",
                            "onClose": "",
                            "session": {},
                            "eraseBorder": false,
                            "backgroundColor": 0,
                            "widthAuto": false,
                            "panelDisplay": 0,
                            "isGroupBox": false,
                            "readOnly": false,
                            "height": "Auto",
                            "focusPositionID": "ShunoJoho_panel_body_area"
                        }
                    ],
                    "controlType": "Panel",
                    "width": "950",
                    "visible": true,
                    "displayNone": false,
                    "disabled": false,
                    "accessKey": "",
                    "nextFocusFieldName": "",
                    "wrap": false,
                    "dependencies": [],
                    "float": 0,
                    "toolTip": "",
                    "authorityMode": 0,
                    "marginLeft": "Default",
                    "marginRight": "Default",
                    "selectControlID": "ShunoJoho",
                    "helpMessageID": "",
                    "jpControlName": "",
                    "onLoad": "",
                    "title": "",
                    "marginTop": "Default",
                    "marginBottom": "Default",
                    "isOpen": true,
                    "canOpenAndClose": true,
                    "postParameterPanelNames": [
                        {
                            "postParameterPanelNames": "ShunoJoho"
                        }
                    ],
                    "requestSettings": [],
                    "hiddenInput": [],
                    "onOpen": "",
                    "onClose": "",
                    "session": {},
                    "eraseBorder": true,
                    "backgroundColor": 0,
                    "widthAuto": false,
                    "panelDisplay": 0,
                    "isGroupBox": false,
                    "readOnly": false,
                    "height": "Auto",
                    "focusPositionID": "createFile"
                }
            ],
            "controlType": "CommonChildDiv",
            "width": "XS",
            "visible": true,
            "displayNone": false,
            "disabled": false,
            "accessKey": "",
            "nextFocusFieldName": "",
            "wrap": false,
            "dependencies": [],
            "float": 0,
            "toolTip": "",
            "authorityMode": 0,
            "marginLeft": "0",
            "marginRight": "0",
            "selectControlID": "defaultLayout",
            "helpMessageID": "",
            "jpControlName": "",
            "relation": [],
            "businessId": "DBB",
            "controlName": "ShunoJoho",
            "marginTop": 0,
            "marginBottom": 0,
            "originalProperty": [],
            "dataPassingForDialog": [],
            "dialogOkEventNameForDialog": "",
            "dialogCancelEventNameForDialog": "",
            "canTransferEvent": true,
            "heightForDialog": "M"
        };
        return ShunoJoho_Design;
    })(Uz.CommonChildDiv);
    DBB.ShunoJoho_Design = ShunoJoho_Design;
})(DBB || (DBB = {}));
