/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jp.co.ndensan.reams.db.dbe.business.core.orca;

import java.io.Serializable;
import jp.co.ndensan.reams.db.dbe.entity.core.orca.OrcaIkenshoCsvEntity;
import jp.co.ndensan.reams.uz.uza.biz.YubinNo;
import jp.co.ndensan.reams.uz.uza.lang.FlexibleDate;
import jp.co.ndensan.reams.uz.uza.lang.RString;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * 主治医意見書（オルカ）のBusinessクラスです。
 *
 * @reamsid_L DBE-1600-020 lishengli
 */
@Setter(AccessLevel.PROTECTED)
@Getter
@SuppressWarnings("PMD.UnusedPrivateField")
public class OrcaIkenshoCsv implements Serializable {

    private static final RString 同意する = new RString("1");
    private static final RString 有 = new RString("1");
    private RString タイムスタンプ;
    private FlexibleDate 記入日;
    private RString 事業所番号;
    private FlexibleDate 送付日;
    private RString 依頼番号;
    private RString 保険者番号;
    private RString 保険者名称;
    private RString 被保険者番号;
    private FlexibleDate 申請日;
    private FlexibleDate 作成依頼日;
    private RString 患者名;
    private RString 患者名かな;
    private FlexibleDate 生年月日;
    private RString 患者_年齢;
    private RString 性別;
    private RString 郵便番号;
    private RString 住所;
    private RString 連絡先電話番号;
    private boolean 同意の有無;
    private RString 医師氏名;
    private RString 医師番号;
    private RString 医療機関名;
    private YubinNo 医療機関郵便番号;
    private RString 医療機関所在地;
    private RString 医療機関電話番号;
    private RString 医療機関FAX番号;
    private FlexibleDate 最終診察日;
    private RString 意見書作成回数;
    private RString 種別;
    private boolean 他科受診有無;
    private RString 他科名;
    private RString その他の他科名;
    private RString 診断名1;
    private RString 発症年月日1;
    private RString 診断名2;
    private RString 発症年月日2;
    private RString 診断名3;
    private RString 発症年月日3;
    private RString 症状安定性;
    private RString 症状不安定時の具体的状況;
    private RString 経過及び治療内容;
    private RString 処置内容;
    private RString 特別な対応;
    private RString 失禁への対応;
    private RString 寝たきり度;
    private RString 認知症高齢者の日常生活自立度;
    private RString 短期記憶;
    private RString 認知能力;
    private RString 伝達能力;
    private RString 周辺症状有無;
    private RString 周辺症状詳細;
    private RString その他の周辺症状;
    private RString 精神神経症状有無;
    private RString 精神神経症状名;
    private RString 専門医受診有無;
    private RString 専門医受診科名;
    private RString 利き腕;
    private RString 身長;
    private RString 体重;
    private RString 体重の変化;
    private RString 四肢欠損;
    private RString 四肢欠損部位;
    private RString 麻痺;
    private RString 麻痺右上肢;
    private RString 麻痺右上肢程度;
    private RString 麻痺左上肢;
    private RString 麻痺左上肢程度;
    private RString 麻痺右下肢;
    private RString 麻痺右下肢程度;
    private RString 麻痺左下肢;
    private RString 麻痺左下肢程度;
    private RString 麻痺その他;
    private RString 麻痺その他部位;
    private RString 麻痺その他程度;
    private RString 筋力低下;
    private RString 筋力低下部位;
    private RString 筋力低下程度;
    private RString 関節拘縮;
    private RString 関節拘縮部位;
    private RString 関節拘縮程度;
    private RString 関節痛み;
    private RString 関節痛み部位;
    private RString 関節痛み程度;
    private RString 失調不随意運動;
    private RString 失調不随意運動上肢;
    private RString 失調不随意運動下肢;
    private RString 体幹;
    private RString 褥瘡;
    private RString 褥瘡部位;
    private RString 褥瘡程度;
    private RString その他皮膚疾患;
    private RString その他皮膚疾患部;
    private RString その他皮膚疾程度;
    private RString 屋外歩行;
    private RString 車いすの使用;
    private RString 歩行補助具_装具の使用;
    private RString 食事行為;
    private RString 現在の栄養状態;
    private RString 栄養_食生活上の留意点;
    private RString 発生可能性状態;
    private RString その他の状態名;
    private RString 対処方針内容;
    private RString サービス利用による生活機能の維持_改善の見通し;
    private RString 医学的管理の必要性;
    private RString その他の医学的管理;
    private RString サービス提供血圧;
    private RString サービス提供血圧留意事項;
    private RString サービス提供摂食;
    private RString サービス提供摂食留意事項;
    private RString サービス提供嚥下;
    private RString サービス提供嚥下留意事項;
    private RString サービス提供移動;
    private RString サービス提供移動留意事項;
    private RString サービス提供運動;
    private RString サービス提供運動留意事項;
    private RString サービス提供その他の留意事項;
    private RString 感染症有無;
    private RString 感染症名;
    private RString その他特記事項;

    OrcaIkenshoCsv(OrcaIkenshoCsvEntity csvEntity) {
        this.setタイムスタンプ(csvEntity.getタイムスタンプ());
        this.set記入日(RString.isNullOrEmpty(csvEntity.get記入日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get記入日()));
        this.set事業所番号(csvEntity.get事業所番号());
        this.set送付日(RString.isNullOrEmpty(csvEntity.get送付日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get送付日()));
        this.set依頼番号(csvEntity.get依頼番号());
        this.set保険者番号(csvEntity.get保険者番号());
        this.set保険者名称(csvEntity.get保険者名称());
        this.set被保険者番号(csvEntity.get被保険者番号());
        this.set申請日(RString.isNullOrEmpty(csvEntity.get申請日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get申請日()));
        this.set作成依頼日(RString.isNullOrEmpty(csvEntity.get作成依頼日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get作成依頼日()));
        this.set患者名(csvEntity.get患者名());
        this.set患者名かな(csvEntity.get患者名かな());
        this.set生年月日(RString.isNullOrEmpty(csvEntity.get生年月日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get生年月日()));
        this.set患者_年齢(csvEntity.get患者_年齢());
        this.set性別(csvEntity.get性別());
        this.set郵便番号(csvEntity.get郵便番号());
        this.set住所(csvEntity.get住所());
        this.set連絡先電話番号(csvEntity.get連絡先電話番号());
        this.set同意の有無(同意する.equals(csvEntity.get同意の有無()));
        this.set医師氏名(csvEntity.get医師氏名());
        this.set医師番号(csvEntity.get医師番号());
        this.set医療機関名(csvEntity.get医療機関名());
        this.set医療機関郵便番号(RString.isNullOrEmpty(csvEntity.get医療機関郵便番号())
                ? YubinNo.EMPTY : new YubinNo(csvEntity.get医療機関郵便番号()));
        this.set医療機関所在地(csvEntity.get医療機関所在地());
        this.set医療機関電話番号(csvEntity.get医療機関電話番号());
        this.set医療機関FAX番号(csvEntity.get医療機関FAX番号());
        this.set最終診察日(RString.isNullOrEmpty(csvEntity.get最終診察日()) ? FlexibleDate.EMPTY : new FlexibleDate(csvEntity.get最終診察日()));
        this.set意見書作成回数(csvEntity.get意見書作成回数());
        this.set種別(csvEntity.get種別());
        this.set他科受診有無(有.equals(csvEntity.get他科受診有無()));
        this.set他科名(csvEntity.get他科名());
        this.setその他の他科名(csvEntity.getその他の他科名());
        this.set診断名1(csvEntity.get診断名1());
        this.set発症年月日1(csvEntity.get発症年月日1());
        this.set診断名2(csvEntity.get診断名2());
        this.set発症年月日2(csvEntity.get発症年月日2());
        this.set診断名3(csvEntity.get診断名3());
        this.set発症年月日3(csvEntity.get発症年月日3());
        this.set症状安定性(csvEntity.get症状安定性());
        this.set症状不安定時の具体的状況(csvEntity.get症状不安定時の具体的状況());
        this.set経過及び治療内容(csvEntity.get経過及び治療内容());
        this.set処置内容(csvEntity.get処置内容());
        this.set特別な対応(csvEntity.get特別な対応());
        this.set失禁への対応(csvEntity.get失禁への対応());
        this.set寝たきり度(csvEntity.get寝たきり度());
        this.set認知症高齢者の日常生活自立度(csvEntity.get認知症高齢者の日常生活自立度());
        this.set短期記憶(csvEntity.get短期記憶());
        this.set認知能力(csvEntity.get認知能力());
        this.set伝達能力(csvEntity.get伝達能力());
        this.set周辺症状有無(csvEntity.get周辺症状有無());
        this.set周辺症状詳細(csvEntity.get周辺症状詳細());
        this.setその他の周辺症状(csvEntity.getその他の周辺症状());
        this.set精神神経症状有無(csvEntity.get精神神経症状有無());
        this.set精神神経症状名(csvEntity.get精神神経症状名());
        this.set専門医受診有無(csvEntity.get専門医受診有無());
        this.set専門医受診科名(csvEntity.get専門医受診科名());
        this.set利き腕(csvEntity.get利き腕());
        this.set身長(csvEntity.get身長());
        this.set体重(csvEntity.get体重());
        this.set体重の変化(csvEntity.get体重の変化());
        this.set四肢欠損(csvEntity.get四肢欠損());
        this.set四肢欠損部位(csvEntity.get四肢欠損部位());
        this.set麻痺(csvEntity.get麻痺());
        this.set麻痺右上肢(csvEntity.get麻痺右上肢());
        this.set麻痺右上肢程度(csvEntity.get麻痺右上肢程度());
        this.set麻痺左上肢(csvEntity.get麻痺左上肢());
        this.set麻痺左上肢程度(csvEntity.get麻痺左上肢程度());
        this.set麻痺右下肢(csvEntity.get麻痺右下肢());
        this.set麻痺右下肢程度(csvEntity.get麻痺右下肢程度());
        this.set麻痺左下肢(csvEntity.get麻痺左下肢());
        this.set麻痺左下肢程度(csvEntity.get麻痺左下肢程度());
        this.set麻痺その他(csvEntity.get麻痺その他());
        this.set麻痺その他部位(csvEntity.get麻痺その他部位());
        this.set麻痺その他程度(csvEntity.get麻痺その他程度());
        this.set筋力低下(csvEntity.get筋力低下());
        this.set筋力低下部位(csvEntity.get筋力低下部位());
        this.set筋力低下程度(csvEntity.get筋力低下程度());
        this.set関節拘縮(csvEntity.get関節拘縮());
        this.set関節拘縮部位(csvEntity.get関節拘縮部位());
        this.set関節拘縮程度(csvEntity.get関節拘縮程度());
        this.set関節痛み(csvEntity.get関節痛み());
        this.set関節痛み部位(csvEntity.get関節痛み部位());
        this.set関節痛み程度(csvEntity.get関節痛み程度());
        this.set失調不随意運動(csvEntity.get失調不随意運動());
        this.set失調不随意運動上肢(csvEntity.get失調不随意運動上肢());
        this.set失調不随意運動下肢(csvEntity.get失調不随意運動下肢());
        this.set体幹(csvEntity.get体幹());
        this.set褥瘡(csvEntity.get褥瘡());
        this.set褥瘡部位(csvEntity.get褥瘡部位());
        this.set褥瘡程度(csvEntity.get褥瘡程度());
        this.setその他皮膚疾患(csvEntity.getその他皮膚疾患());
        this.setその他皮膚疾患部(csvEntity.getその他皮膚疾患部());
        this.setその他皮膚疾程度(csvEntity.getその他皮膚疾程度());
        this.set屋外歩行(csvEntity.get屋外歩行());
        this.set車いすの使用(csvEntity.get車いすの使用());
        this.set歩行補助具_装具の使用(csvEntity.get歩行補助具_装具の使用());
        this.set食事行為(csvEntity.get食事行為());
        this.set現在の栄養状態(csvEntity.get現在の栄養状態());
        this.set栄養_食生活上の留意点(csvEntity.get栄養_食生活上の留意点());
        this.set発生可能性状態(csvEntity.get発生可能性状態());
        this.setその他の状態名(csvEntity.getその他の状態名());
        this.set対処方針内容(csvEntity.get対処方針内容());
        this.setサービス利用による生活機能の維持_改善の見通し(csvEntity.getサービス利用による生活機能の維持_改善の見通し());
        this.set医学的管理の必要性(csvEntity.get医学的管理の必要性());
        this.setその他の医学的管理(csvEntity.getその他の医学的管理());
        this.setサービス提供血圧(csvEntity.getサービス提供血圧());
        this.setサービス提供血圧留意事項(csvEntity.getサービス提供血圧留意事項());
        this.setサービス提供摂食(csvEntity.getサービス提供摂食());
        this.setサービス提供摂食留意事項(csvEntity.getサービス提供摂食留意事項());
        this.setサービス提供嚥下(csvEntity.getサービス提供嚥下());
        this.setサービス提供嚥下留意事項(csvEntity.getサービス提供嚥下留意事項());
        this.setサービス提供移動(csvEntity.getサービス提供移動());
        this.setサービス提供移動留意事項(csvEntity.getサービス提供移動留意事項());
        this.setサービス提供運動(csvEntity.getサービス提供運動());
        this.setサービス提供運動留意事項(csvEntity.getサービス提供運動留意事項());
        this.setサービス提供その他の留意事項(csvEntity.getサービス提供その他の留意事項());
        this.set感染症有無(csvEntity.get感染症有無());
        this.set感染症名(csvEntity.get感染症名());
        this.setその他特記事項(csvEntity.getその他特記事項());
    }

}
